### ISSUE TITLE
repo.aptly.info domain has expired

### ISSUE THREAD

**Issue by cindy** [aptly-dev/aptly#1009]
## Detailed Description
http://repo.aptly.info no longer hosts aptly packages

<img width="609" alt="Screen Shot 2022-01-19 at 10 13 12 PM" src="https://user-images.githubusercontent.com/5558813/150283669-1c924351-c34e-4a06-9218-6637a296a6f4.png">

**Comment by fihufil** [comment]
I know aptly in unmaintained and hosting costs money so can we (we as a community) get a tar.gz dump of the site to host it elsewhere? Even just the documentation part of site.

**Comment by ghubz** [comment]
> I know aptly in unmaintained and hosting costs money so can we (we as a community) get a tar.gz dump of the site to host it elsewhere? Even just the documentation part of site.

Aptly is unmaintained??

**Comment by iliis** [comment]
> I know aptly in unmaintained and hosting costs money so can we (we as a community) get a tar.gz dump of the site to host it elsewhere? Even just the documentation part of site.

The website source is available at https://github.com/aptly-dev/www.aptly.info

**Comment by fihufil** [comment]
> > I know aptly in unmaintained and hosting costs money so can we (we as a community) get a tar.gz dump of the site to host it elsewhere? Even just the documentation part of site.
> 
> Aptly is unmaintained??

For some time it was not. See https://github.com/aptly-dev/aptly/issues/920 but looks like there is some activity recently which is great!

**Comment by ghubz** [comment]
> > > I know aptly in unmaintained and hosting costs money so can we (we as a community) get a tar.gz dump of the site to host it elsewhere? Even just the documentation part of site.
> > 
> > 
> > Aptly is unmaintained??
> 
> For some time it was not. See #920 but looks like there is some activity recently which is great!

I've seen that but there hasn't been any activity on the project/code. I would help if I could but unfortunately I am not a developer.

**Comment by Raboo** [comment]
@smira I think my company can sponor the domain.

**Comment by ghubz** [comment]
> @smira I think my company can sponor the domain.

I think an official donation link should be posted by the admins so that we can contribute/donate in order for the domains to remain active.

**Comment by moritz** [comment]
I work for [a company](https://noris.net/) that (among other things) provides virtual machines and the likes for hosting.

We are using aptly internally, should I ask if my sales colleagues if we can provide a free VM and some network bandwith for hosting the website, on an ongoing basis?

**Comment by smira** [comment]
I'm sorry, somehow my auto-payment settings went south. I did the payment, service should be restored in a few.

**Comment by smira** [comment]
it seems to work fine now, closing the issue

**Comment by neolynx** [comment]
Hi all,

we took over the maintenance last year, and are still in the process of
transferring the hosting and migriting the testing to github actions.

> I know aptly in unmaintained and hosting costs money so can we (we as a community) get a tar.gz dump of the site to host it elsewhere? Even just the documentation part of site.

we are preparing the new hosting of aptly.info (which is also used for
testing in CI/CD). As soon as we have this, we can publish a roadmap
and plan a next release, update the website and get things rolling
again ;-)

Kind Regards,

 André
