### ISSUE TITLE
Installer location for Ubuntu focal has changed.

### ISSUE THREAD

**Issue by rldleblanc** [aptly-dev/aptly#1018]
Ubuntu Focal has changed the installer to the `live` installer and has moved the location of the installer from
https://atl.mirrors.clouvider.net/ubuntu/dists/focal/main/installer-amd64/current/**images**/SHA256SUMS
to
https://atl.mirrors.clouvider.net/ubuntu/dists/focal/main/installer-amd64/current/**legacy-images**/SHA256SUMS

## Detailed Description
Aptly should know that focal and possibly newer versions have a different path for the install images.

## Context
We can't cache and snapshot installer images for focal.

## Possible Implementation
I'm going to see if I can create a patch and share it. I haven't dug into the code yet.

## Your Environment
We are mirroring 116 mirrors and consolidating them down to three for three flavors of Ubuntu (nine total). We keep snapshot indefinitely and rotate them with `tags` (symlinks) of common names to the actual snapshot. We are adding critical patches to the snapshot and republishing as needed.

**Comment by idl0r** [comment]
It's not just focal, jammy is also affected by this. Probably, as for now, anything as of focal.

**Comment by markkrj** [comment]
Apparently, Ubuntu's debian-installer based installations "are not coming back" (https://discourse.ubuntu.com/t/spec-publishing-netboot-artifacts/28256/4)

**Comment by iofq** [comment]
This was fixed in https://github.com/aptly-dev/aptly/pull/1248
