### ISSUE TITLE
ERROR: unable to drop: local repo is published

### ISSUE THREAD

**Issue by morpheyesh** [aptly-dev/aptly#102]
How to drop a repo once it is published? aptly repo drop does not work

**Comment by petronii** [comment]
> How to drop a repo once it is published? aptly repo drop does not work

also stucked

> You should to use
> 
> ```
> aptly publish drop
> ```
> 
> first

doesnt work too in my case :(

```
$ aptly publish list
Published repositories:
  * -component=main,contrib,non-free/jessie [source] publishes {main: [jessie-updates-all]}
```

needed options like ~
```
$ aptly publish drop all
$ aptly repo drop -cascade|-recursive|-unpublish-too <name>
```
