### ISSUE TITLE
Consider adding timeouts to CI jobs to avoid runaway tests

### ISSUE THREAD

**Issue by lbolla** [aptly-dev/aptly#1032]
## Detailed Description

See https://github.com/aptly-dev/aptly/pull/1023#issuecomment-1035983552

In order to avoid running out of our limited quota of GH Actions, I think it would make sense to add a timeout to CI jobs.
I don't know if GH Actions supports it.

**Comment by ximon18** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
