### ISSUE TITLE
GPG key for aptly repo about to expire

### ISSUE THREAD

**Issue by phosei** [aptly-dev/aptly#1037]
## Detailed Description

https://www.aptly.info/download/ lists https://www.aptly.info/pubkey.txt as the GPG key to use for the Debian/Ubuntu repo. This key will expire in a couple of days:

```
$ gpg pubkey.txt 
pub   rsa4096 2018-03-15 [SC] [expires: 2022-03-16]
      26DA9D8630302E0B86A7A2CBED75B5A4483DA07C
uid           Andrey Smirnov <me@smira.ru>
sub   rsa4096 2018-03-15 [E] [expires: 2022-03-16]
```
Could you please renew this key to avoid a [situation like in 2020](https://github.com/aptly-dev/aptly/issues/911)? Thanks!

**Comment by randombenj** [comment]
Thanks for the notification! @neolynx do we have permission to update this key?

**Comment by neolynx** [comment]
Hi,

> Thanks for the notification! @neolynx do we have permission to update this key?

aptly.info domain is ours, transferring s3 repo almost done.
we will switch to our hosting in the next weeks, then we can update the
key...

thanks for your patience !

Kind Regards,

 André

**Comment by phosei** [comment]
Any news on this? Expiry date is tomorrow. :-)

Thanks!

**Comment by neolynx** [comment]
Hi all,

migration is done, repo.aptly.info is republished with new key: 

    A0546A43624A8331 Aptly Repository <repo@aptly.info>

Key is downloadable from keyserver.ubuntu.com, see http://repo.aptly.info

Let us know if that works as expected !

Kind Regards,

 André

**Comment by phosei** [comment]
@neolynx Looks good, thank you!
