### ISSUE TITLE
Aptly website unavailable

### ISSUE THREAD

**Issue by gmloose** [aptly-dev/aptly#1039]
The website https://www.aptly.info has been unavailable for several days now.

## Detailed Description

Firefox gives the following error message: 

```Secure Connection Failed

An error occurred during a connection to www.aptly.info.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the web site owners to inform them of this problem.
``` 

## Context

The website hosts the API documentation, which I depend on.

## Your Environment

Also tried using Chromium browser, which gives the following, even less informative, error:
```
This page isn’t workingwww.aptly.info didn’t send any data.
ERR_EMPTY_RESPONSE
```

**Comment by randombenj** [comment]
Sorry to hear that, we will have a look at this. There is currently some effort ongoing to migrate from s3 to github pages but DNS and bucket access is still not fully figured out yet ...
As a workaround, you can go to https://aptly-dev.github.io/www.aptly.info/ to view the docs untill it's fixed.

We will have a look at this.

**Comment by neolynx** [comment]
Working on migration to github pages, as part of the maintainer transfer. We need to wait for DNS updates and AWS workflows to happen...

**Comment by neolynx** [comment]
we are back online: http://www.aptly.info

https still missing, work in progress...

**Comment by mcnewton** [comment]
Just FYI in case you didn't know, the Debian repo is also currently broken - the lists are there but the actual .deb is missing (it's trying to download from Amazon).

**Comment by neolynx** [comment]
@mcnewton thanks for reporting this.. 

somehow this file was not copied, working on restoring it

**Comment by neolynx** [comment]
please try again, version 1.4.0 should be available now :)

**Comment by mcnewton** [comment]
All looking good! Thanks! :-D
