### ISSUE TITLE
sign repo.aptly.info ATP key from maintainers, publish checksum

### ISSUE THREAD

**Issue by neolynx** [aptly-dev/aptly#1047]
Olle E. Johansson](https://twitter.com/oej)

Replying to 
[@smira](https://twitter.com/smira)

It would be great if this could be announced on mail list, if the key could be signed by the team and a checksum published on the web. Thanks!

## Detailed Description

New key was added to replace expiring one.

**Comment by oej** [comment]
Copy of #1046
