### ISSUE TITLE
S3/Azure do not remove paths from storage.pathCache

### ISSUE THREAD

**Issue by TheDJVG** [aptly-dev/aptly#1054]
When a publish is dropped and files are removed from S3/Azure the paths are not removed from their "storage.pathCache" causing a strange situation when publishing the same path again from the API.

## Detailed Description
When new files are "Linked" a pathCache is created:
https://github.com/aptly-dev/aptly/blob/cbf0416d7e5070f58d0b40fc1be3e771b0baacf4/s3/public.go#L303-L314

And there's a check if a file is in this cache:
https://github.com/aptly-dev/aptly/blob/cbf0416d7e5070f58d0b40fc1be3e771b0baacf4/s3/public.go#L316

The problem is that if you remove a publish this pathCache is not updated to make sure files are removed from this list.
This is generally only a problem when running the API as it will keep the same `PublishedStorage` throught it's lifetime. Running 1 single command on the CLI is not affected by this.

## Context
While performing some tests I had to drop a published repository and publish it again with the same distribution/prefix using the API. After it published successfully I noticed the `pool/` directory did not exist.

## Possible Implementation
As we know the path to be deleted we could probably simple remove it from "storage.pathCache", not sure how we would do that for `RemoveDirs`, just remove all the paths that start with `path`? Or just drop the cache all together?

I will try to create a patch but my go is not very strong ;)

## Your Environment
Tested with the `master` branch.

**Comment by neolynx** [comment]
Thanks for reporting, this should be fixed on latest master, please test and reopen the issue if needed !
