### ISSUE TITLE
`aptly publish update` fails for azure

### ISSUE THREAD

**Issue by floriankramer** [aptly-dev/aptly#1060]
## Detailed Description
Running `aptly publish update focal azure:<name>:` fails with 
```
ERROR: unable to update: error deleting pool/main/a from Azure: https://<>.blob.core.windows.net/$web/apt/debian: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=DirectoryIsNotEmpty) =====
Description=This operation is not permitted on a non-empty directory.
RequestId:cb72bd80-e01e-00ab-3a50-4e9ea7000000
Time:2022-04-12T09:37:31.5467576Z, Details: 
   Code: DirectoryIsNotEmpty
   DELETE https://<>.blob.core.windows.net/$web/apt/debian/pool/main/a?timeout=61
   Authorization: REDACTED
   User-Agent: [Azure-Storage/0.13 (go1.18; linux)]
   X-Ms-Client-Request-Id: [0ddb6995-a305-4d36-4c3f-1821097aaccd]
   X-Ms-Date: [Tue, 12 Apr 2022 09:37:31 GMT]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   RESPONSE Status: 409 This operation is not permitted on a non-empty directory.
   Content-Length: [245]
   Content-Type: [application/xml]
   Date: [Tue, 12 Apr 2022 09:37:31 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [0ddb6995-a305-4d36-4c3f-1821097aaccd]
   X-Ms-Error-Code: [DirectoryIsNotEmpty]
   X-Ms-Request-Id: [cb72bd80-e01e-00ab-3a50-4e9ea7000000]
   X-Ms-Version: [2019-12-12]


: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=DirectoryIsNotEmpty) =====
Description=This operation is not permitted on a non-empty directory.
RequestId:cb72bd80-e01e-00ab-3a50-4e9ea7000000
Time:2022-04-12T09:37:31.5467576Z, Details: 
   Code: DirectoryIsNotEmpty
   DELETE https://<>.blob.core.windows.net/$web/apt/debian/pool/main/a?timeout=61
   Authorization: REDACTED
   User-Agent: [Azure-Storage/0.13 (go1.18; linux)]
   X-Ms-Client-Request-Id: [0ddb6995-a305-4d36-4c3f-1821097aaccd]
   X-Ms-Date: [Tue, 12 Apr 2022 09:37:31 GMT]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   RESPONSE Status: 409 This operation is not permitted on a non-empty directory.
   Content-Length: [245]
   Content-Type: [application/xml]
   Date: [Tue, 12 Apr 2022 09:37:31 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [0ddb6995-a305-4d36-4c3f-1821097aaccd]
   X-Ms-Error-Code: [DirectoryIsNotEmpty]
   X-Ms-Request-Id: [cb72bd80-e01e-00ab-3a50-4e9ea7000000]
   X-Ms-Version: [2019-12-12]

```

## Context
Currently, the only workaround I've found is to un-publish and re-publish the repo.

## Your Environment
A local repo for ubuntu focal with several packages and a azure storage account with a `$web` container the repo is published to.

**Comment by chuan** [comment]
I cannot repro this locally. Can you check what are the files that are still under `https://<>.blob.core.windows.net/$web/apt/debian/pool/main/a`?

**Comment by floriankramer** [comment]
There is an `aptly` folder with a single file `aptly_1.4.0-2.deb` (we packaged the master branch of aptly, as the last release doesn't yet contain the azure support).

**Comment by chuan** [comment]
I still cannot repo this. I am also using the latest (at commit 4c04e77) master branch build. I tested the following two simple scenarios: 1) add 2 packages; then update the publish; 2) remove 1 package; then update the publish. Both are working for me. Is it possible to share the commands used that led to the error above? 

```
aptly repo add myrepo aptly_1.2.0_amd64.deb
aptly publish myrepo -distribution focal azure:aptlydev:

aptly repo add myrepo aptly_1.3.0_amd64.deb
aptly repo add gaia aptly_1.4.0_amd64.deb
aptly publish update focal azure:aptlydev:

aptly repo remove myrepo aptly_1.2.0_amd64
aptly publish update focal azure:aptlydev:
```

**Comment by floriankramer** [comment]
Strange. I'm gonna try and find a sequence of commands that produces the error and come back to you.

**Comment by floriankramer** [comment]
I've decided to do some debugging myself, that seemed easier. Turns out, I've got `Hierarchical Namespace` enabled on my azure container.
As a result `ListBlobsSegmentOptions` which is used to determine which files exist on the storage when `dpkg.publish.CleanupPrefixComponentFiles` is called also returns directories. When existing files are listed only .deb files, not directories are returned though. As a result the cleanup tries to delete all folders.

**Comment by floriankramer** [comment]
I've done a little more digging. There is a function from azblob to determine if a storage is Hierarchical (`ServiceGetAccountInfoResponse.IsHierarchicalNamespaceEnabled`) but that requires a `ServiceURL` and we currently only store a container url in the public storage implementation.

**Comment by chuan** [comment]
Thanks for digging into it. Yes, hierarchical namespaces are not supported in the current Azure publish implementation.

**Comment by floriankramer** [comment]
I recreated the storage as non-hierarchical and the update now works. Thanks for the quick replies!
