### ISSUE TITLE
Aptly does not support publishing objects without ACL rules

### ISSUE THREAD

**Issue by mdebord-dlr** [aptly-dev/aptly#1067]
## Description

Amazon now suggests to DISABLE ACL's for object ownership.
It's even marked as "**recommended**" in the AWS S3 console. 

Aptly does not support publishing objects without ACL rules. When I attempt to publish to a bucket with this recommended setting, it throws `AccessControlListNotSupported: The bucket does not allow ACLs status code: 400`

See: https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-object-ownership-simplify-access-management-data-s3/ for more info. 

## Context
I originally found this when my account resources couldn't pull objects from S3 that were published by Aptly in a different account. So I investigated permissions and found that the account that published the objects to S3 owned them, and regardless of the bucket policy permissions, resources within the bucket owner account could not retrieve the files. 

My use-case has a single Aptly instance that manages snapshots for all environments, it then pushes objects into S3 buckets in **various accounts**. It publishes from this single Aptly instance to ensure snapshots are identical across all environments/accounts. 

The ability to publish from a single mirror repo to many S3 publish endpoints across accounts is a useful functionality and mission-critical for my use-case. 

## Possible Implementation
- Do not publish any `acl` information when publishing objects to S3 if the `acl` parameter is missing from config. Alternatively, to support backwards compatibility, leave `private` acl as default and support a null/None keyword to tell Aptly to ignore setting `acl` when publishing objects.

**Comment by wadey** [comment]
I ran into the same issue, so I opened a PR to fix it: #1087
