### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by eilandert** [aptly-dev/aptly#1075]
Hello,

The site www.aptly.info is down.

$ host www.aptly.info
Host www.aptly.info not found: 2(SERVFAIL)

Can someone take a look at it? I need some documentation ;-)

**Comment by ledmonster** [comment]
This seems to be a documentation, but I want the site to be recovered...
- https://github.com/aptly-dev/www.aptly.info

**Comment by ledmonster** [comment]
You can temporarily see the site by adding this to `/etc/hosts`
```
185.199.108.153 www.aptly.info
```

**Comment by randombenj** [comment]
Sorry about that, there seems to be a problem in the account we managed the domain with :) 
We are fixing that.

**Comment by neolynx** [comment]
Hello,

> The site www.aptly.info is down.

we are back online again !

sorry for the inconvenience.

Kind Regards,

 André

**Comment by ledmonster** [comment]
Thank you.
But http://repo.aptly.info/ seems to be still down. Could you please recover this?
