### ISSUE TITLE
(suggestion) After Ubuntu 22.04 trusted gpg issue

### ISSUE THREAD

**Issue by bdh1993** [aptly-dev/aptly#1098]
The aptly homepage does not seem to show how to resolve issues related to "Key is stored in legacy trusted.gpg keyring".

In Ubuntu's 22.04 version, aptly works well, but it is inconvenient to add repository.

aptly in Ubuntu 22.04 repository has zstd problem. (ver : 1.4.0)

I think you can add it like a docker repository.

1) add repository in sources.list or sources.list.d/xxx.list
deb [signed-by=/etc/apt/keyrings/aptly.gpg] http://repo.aptly.info/ squeeze main

2) import key
curl -fsSL https://www.aptly.info/pubkey.txt | sudo gpg --dearmor -o /etc/apt/keyrings/aptly.gpg

3) update&install
sudo apt update
sudo apt install aptly

**Reference**
https://askubuntu.com/questions/1403556/key-is-stored-in-legacy-trusted-gpg-keyring-after-ubuntu-22-04-update
https://docs.docker.com/engine/install/ubuntu/

**Comment by NeroBurner** [comment]
if you trust the aptly gpg key enough you can add it as `/etc/apt/trusted.gpg.d/aptly.gpg` system wide. Then you don't have to explicitly set the `signed-by=` path

```
deb http://repo.aptly.info/ squeeze main
```
```sh
curl -fsSL https://www.aptly.info/pubkey.txt | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/aptly.gpg
```

when on a minimal install the package `gnupg2` needs to be installed to get the `gpg` command. I'm using the following commands in my scripts to install this dependency

```sh
sudo apt-get update -q
sudo apt-get install -qy gnupg2 --no-install-recommends
```

**Comment by bdh1993** [comment]
Thank you for telling me more accurate information.
I hope this information will be announced on the homepage.
https://www.aptly.info/download/
