### ISSUE TITLE
W: Conflicting distribution: http://reposerver wheezy/updates Release (expected wheezy but got wheezy/updates)

### ISSUE THREAD

**Issue by erickeller** [aptly-dev/aptly#110]
Hi Andrey,

After mirroring security.debian.org in aptly, I get the following Warning:

```
sudo apt-get update
...
W: Conflicting distribution: http://reposerver wheezy/updates Release (expected wheezy but got wheezy/updates)
```

the sources.list looks like:

```
deb http://reposerver:8080/debian/daily wheezy main
deb http://reposerver:8080/debian/daily wheezy/updates main
```

the command I used to create the wheezy/update:

```
aptly -config=/home/repo/.aptly.conf -architectures=amd64,i386 mirror create wheezy-security-archive http://security.debian.org/ wheezy/updates main
```

do you have an idea why this warning is shown?

Regards

**Comment by woifi** [comment]
I just had the same issue when I tried to publish snapshots from Debian mirrors with the following URLs:

* http://security.debian.org/debian-security/ stretch/updates
* http://ftp.at.debian.org/debian/ stretch-updates

Is there any way to resolve this? I'm currently using aptly 0.9.7-1+b1 from Debian Stretch.
