### ISSUE TITLE
Concurrent update of aptly repo.

### ISSUE THREAD

**Issue by goldendeng** [aptly-dev/aptly#1107]
https://github.com/aptly-dev/aptly/blob/b3d9055059e24e1d96a462dc080f46071ced81b7/deb/local.go#L160

In the concurrent update scenario of aptly's repo, it seems to me that the existing software package index update process of aptly's repo may be missed. In fact, I have encountered it when using the etcd database. I wonder whether the existing software package index update process is deeply bound with the batch operation of leveldb?

**Comment by neolynx** [comment]
the etcd database implementation lacked transactions and batch operations. please test with latest master, as support has been merged.
