### ISSUE TITLE
[Question] Is it possible to configure repositories requiring authentication?

### ISSUE THREAD

**Issue by iieklund** [aptly-dev/aptly#1112]
Hi,

we are evaluating if we could use Aptly to manage our .deb packages for public and private use.
Some of the repositories would need to be behind authentication,
i.e. the user needs to provide user+pass to access given repositories (/etc/apt/auth.conf(.d)).

I didn't find related Aptly documentation how to configure this, if supported by Aptly?

**Comment by aol-nnov** [comment]
Neither api nor published files are auth-protected by aptly itself, but you can place it behind reverse proxy with auth support and/or export to S3-compatible storage with auth support.

**Comment by randombenj** [comment]
@aol-nnov exactly, thats how we are hosting repo.aptly.info. 
https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by iieklund** [comment]
Thanks, this is clear now :+1:
