### ISSUE TITLE
[BUG] aptly publish fails with same distro version even though different repo

### ISSUE THREAD

**Issue by L1ghtn1ng** [aptly-dev/aptly#1128]
## Detailed Description
When you mirror the hashicorp apt repo after importing the gpg key so you can talk to there repo and mirror it you run into issues when you publish it as it say the prefix/distribution already exists.

## Context

Please see the screenshots for details jammy-hashicorp mirror
![Screenshot 2022-11-15 154138](https://user-images.githubusercontent.com/3628354/201962686-4497cf44-2be8-46f3-8f5f-602b08541def.png)
![Screenshot 2022-11-15-mirrors](https://user-images.githubusercontent.com/3628354/201963348-49843ab3-9feb-4a95-afa4-b6aa58a17109.png)

## Your Environment
Using aplty version 1.5.0

**Comment by L1ghtn1ng** [comment]
If I could get a response on this asap would much appreciate it as it is holding up a bit of work

**Comment by randombenj** [comment]
I think you need to publish to a `prefix` (see the docs: https://www.aptly.info/doc/aptly/publish/snapshot/) otherwise all the mirrors you have will be published to the root (which obviously causes conflicts).

```sh
aptly publish snapshot [YOUR_OPTIONS] jammy-hashicorp hashicorop
```

**Comment by L1ghtn1ng** [comment]
@randombenj Sorry did not see you had left an example, I in the end managed to get it working like you said with a prefix, just would of been quicker if I saw your example lol The thing that I find interesting though is that I had no issues doing this with the Ubuntu OS repos though so I thought me ding the same with the hashicorp repo would be fine as well, if that makes sense? Not sure if there is some edge case though as it turns out the hashicorp repo is an Artifactory repo so not sure if that would make a difference at all?

**Comment by randombenj** [comment]
No that shouldn't make a difference as the apt repo is just a directory structure. The probme for you was that you have both distro names named `jammy` in the hashicorp and ubuntu repo.
