### ISSUE TITLE
Support for '/' in distribution names

### ISSUE THREAD

**Issue by smira** [aptly-dev/aptly#115]
Requires special component naming, etc. To be investigated.

Requested by @erickeller in #110.

**Comment by sandrotosi** [comment]
yeah exactly, / is replaced with - so we cannot mimicwhat Debian is doing for the security updates, where the distribution is set to 'wheezy/updates' but with aptly we ended up with "wheezy-security", but what we really want is 'wheezy/updates'

please allow / in distribution name

**Comment by wwarmus** [comment]
Hey, I think same issues concerns the prefix values. 
While trying to publish via api I'm hitting 404, but can publish via cli, though...
Is it possible to add support for /api for the :prefix names containing "/" too?

**Comment by rottenbytes** [comment]
:+1: on this one. allowing "/" in names via api would be great.

**Comment by richard-scott** [comment]
Looking forward to testing this one as it is the last thing I need to have working for aptly to be the perfect tool for my needs :-)

**Comment by mauricemeyer** [comment]
This relates to #561.

**Comment by ksalman** [comment]
This would be nice to have.

**Comment by richard-scott** [comment]
Wow, I'd forgotten about this tool.... 
Will this feature get into v1.3.0?

Would be great if it did.

**Comment by YotamAlon** [comment]
Could also use this feature

**Comment by adalessandro** [comment]
Following up on this thread, what's the reason to forbid slash `/` characters in the publish distribution name? I.e. I'm trying to understand this line of code: https://github.com/aptly-dev/aptly/blob/v1.4.0/deb/publish.go#L265
