### ISSUE TITLE
consider adding git backend

### ISSUE THREAD

**Issue by james-lawrence** [aptly-dev/aptly#1169]
git is fairly universal; many hosting providers; easy to setup secure access to and golang libraries exist for interacting with git repositories.

just a thought; don't personally need this but would make it easier to use aptly given a git host service is in every company.

**Comment by r4co0n** [comment]
You are right, git is ubiquitous. But git is also a really bad place to store package mirrors, especially the pool which consists solely of compressed files, as you don't delete things from a git branch without rewriting history.

I don't see how git would be a viable storage target - Btw, you can already have your data in git, just install something like etckeeper, configure it to use git and keep track of your aptly base directory. (Only do this for giggles, this is a bad idea, as outlined previously.)

**Comment by james-lawrence** [comment]
git is perfectly fine for this; been doing it for ages. the only reason git would be bad is if you are updating individual binary files. which aptly doesn't do.

**Comment by james-lawrence** [comment]
the history is fairly immaterial to the problem; you're serving a set of files. the history doesn't play into it. the only reason you care about the size is when you're deep cloning the repository. but as I've said if you're really concerned about the size its fairly trivial to clean up the history.

```
git branch -D tmpmain
git add --all . && git commit -m 'release WDS packages'
git rev-parse HEAD^^^^ > git.sha
git checkout --orphan tmpmain $(cat git.sha)
git commit -m 'release WDS packages'
git rebase --onto tmpmain $(cat git.sha) main
git branch -D tmpmain
git push --force origin HEAD:main
```

**Comment by r4co0n** [comment]
I still think aptly's users expect `aptly snapshot drop <snapshot_name>` to remove a snapshot and `aptly db cleanup` to tidy up all remnants of these snapshots. If git was treated as a storage backend, this is no longer a trivial task, you can't just unlink unreferenced files, but need to rewrite GIT history (`git push --force main`). So I suppose `aptly db cleanup` should do your "quick and efficient cleanup" - This is potentially destructive, depending on what other stuff the user tracked in this repository. Our current backends do not have that problem, as we just remove the files we know are ours and no longer referenced.

If you want to use aptly to host a small personal project, I think you can also just commit the resulting publication, and not care about aptly metadata, throw away your db and your instance, and start with a fresh aptly instance for the new release. As long as you keep the same config and use the same GPG key, your new publication version committed to your git repo will look no different than if you kept the db.

**Comment by james-lawrence** [comment]
I covered rewriting the history above with a trailing window in my previous commit. its something that can be handled by aptly trivially.
