### ISSUE TITLE
CI Failure after jenkins repo change

### ISSUE THREAD

**Issue by randombenj** [aptly-dev/aptly#1173]
The current pipeline seems to fail due to some upstream repo change, must be fixed for community contributions:

- https://github.com/aptly-dev/aptly/actions/runs/4709459874/jobs/8352539945?pr=1168

**Comment by reglim** [comment]
I think it's related to this key rotation:
https://www.jenkins.io/blog/2023/03/27/repository-signing-keys-changing/

**Comment by randombenj** [comment]
@reglim @neolynx We should mirror the internet repos to: http://repo.aptly.info/ so we don't have sporadic faillures.

**Comment by reglim** [comment]
@randombenj Could we create a mirror such as http://deb.aptly.info for these testing purposes?

**Comment by reglim** [comment]
Fixed with #1180
