### ISSUE TITLE
multiple time stamped published repos.

### ISSUE THREAD

**Issue by foster82** [aptly-dev/aptly#1188]
Hi all, 

My company is looking to posssibly use aptly to host our internal repos. However i do have a question. Our currently setup requires that some of our servers point to  specific dated repo.  Is it possible to have multiple published repos based on time stamps ? So that we can point a server to a specific time stamped repo.

Many thanks
Jonathan

**Comment by randombenj** [comment]
You can create snapshots with any kind of name: https://www.aptly.info/doc/aptly/snapshot/

**Comment by foster82** [comment]
OK so how many snap shots can i publish at once ? and how do i tell the server to point to s specific snapshot

**Comment by r4co0n** [comment]
Aptly does not limit the amount of snapshots you can publish, in fact, publishing the same snapshot over and over again should be rather cheap. Similarly, the amount of published snapshots is primarily limited by how many snapshots you can publish, as this is not an instant operation. It is not really a question about "How many publications can I have?", but rather "How often can I afford to republish my publications?".

You seem to think this is a support channel - It is not. Please specify your specific issue with this software, or seek help elsewhere.

**Comment by neolynx** [comment]
latest build from master should have publish performance improved...

closing, please reopen if you need more help...
