### ISSUE TITLE
FEATURE: aptly cmd line output in json format

### ISSUE THREAD

**Issue by oOHenry** [aptly-dev/aptly#1191]
We are using aptly in many scripts for example to add packages via ci to our repo servers. It would help a lot if there was a general flag to enable json output for the aptly cmd output.

**Comment by r4co0n** [comment]
Have you considered using aptly's API for you CI jobs? It should already deliver JSON responses for all implemented features.

The API documentation is funny though, as it does not really specify anything about responses to be expected, you'll have to go by the examples, which are hopefully still up-to-date.

**Comment by oOHenry** [comment]
Yeah but we don't have the aptly api running, we just export the directory via an apache. 
Also the [docs](https://www.aptly.info/doc/api/) said: `Note: HTTP REST API is not complete yet (mirroring support not implemented)` and we are using a job to create sync and update mirrors.

**Comment by randombenj** [comment]
@oOHenry Mirrors are supported since a while now: https://www.aptly.info/doc/api/mirror/
We might need to update the docs.
