### ISSUE TITLE
Aptly doesn't seem to resume download after interrupted

### ISSUE THREAD

**Issue by jax79sg** [aptly-dev/aptly#1194]
## Detailed Description
It was clearly shown that aptly has just downloaded around 10GB out of expected 108GB. But the program was interrupted due to a computer reboot. After that, when i run `aptly mirror update mymirror` again, aptly reports Mirror successfully updated.

## Context
This might cause problems when ppl perform 'apt install' and hits a missing package.

## Your Environment
Windows 11, WSL2@Ubuntu 22.04.

**Comment by neolynx** [comment]
should be fixed, please check if the nightly repo fixes your issue :)
