### ISSUE TITLE
Concurrent map writes crash after publish

### ISSUE THREAD

**Issue by russelltg** [aptly-dev/aptly#1196]
## Detailed Description

Aptly crashed with a concurrent map writes error. Log: https://gist.github.com/russelltg/6ece2a67e723b2fb7560851a69257055

This has happened a few times now, seems to happen after every few weeks or so. Let me know if there's any additional info I can provide

## Your Environment

```bash
$ aptly version
aptly version: '1.5.0+48+gecc05518'
```

**Comment by neolynx** [comment]
I think this is fixed on master, as many race confidions have been eliminated. could you please verify and close this issue ?

**Comment by russelltg** [comment]
I haven't seen this in a while. Let's close for now and I'll open a new report if I see something new.
