### ISSUE TITLE
how to package downloaded files for non-internet machine

### ISSUE THREAD

**Issue by lchunleo** [aptly-dev/aptly#1205]
hi
 i wish to download files from the ubuntu and transfer the downloaded packages to a non internet machine
 
fast forward, i had already completed the aptly update and perform snapshot "ubuntu-test" prior perform the publish command.
  
 In additional, i also create a directory called "mydist" to hold the packages. After which, i perform:

 -->  aptly publish snapshot -skip-signing ubuntu-test ./mydist
 aptly publish snapshot -skip-signing 
 However, the directory "mydist" is empty.  Please advise me. thank you

Appreciate an hello-world working example to do this. 

I also noted that there is no "public" folder created if i perform  aptly publish snapshot -distribution ubuntu -architectures="amd64" localrepo

**Comment by r4co0n** [comment]
After running `aptly publish [...]`, the `public` directory should be at `~/.aptly/public` if you have not reconfigured [aptly's root directory `rootDir`](https://www.aptly.info/doc/configuration/).

I think you assumed the folders would be created relative to your working directory - They are not, they are always created in a well known place.

**Comment by r4co0n** [comment]
To transfer the files, you can simple copy the public directory (or a subdirectory) to where you want them.

Note that your package files, all the files in the publications' `/pool/` directory, are hardlinks, meaning they refer to the same files that reside in `~/.aptly/pool` - You should not publish across filesystem boundaries, as hardlinks have to be created in the same filesystem as the file they refer to. You can of course copy them to another mount point or send them to a remote location, in which case the contents will be duplicated.
