### ISSUE TITLE
No -force-architectures flag when editing mirrors

### ISSUE THREAD

**Issue by bigon** [aptly-dev/aptly#1238]
## Detailed Description
I'm trying to use the `-force-architectures` flag with `mirror edit`, but the flag is not available in that context

## Your Environment
Version 1.5.0

**Comment by neolynx** [comment]
Hi and thanks for reporting !

could you describe the use case, why that flag is needed ?

**Comment by bigon** [comment]
TBF I'm not sure what I was trying to do anymore
