### ISSUE TITLE
small typo on homepage documentation

### ISSUE THREAD

**Issue by qyanu** [aptly-dev/aptly#1240]
Hi,

there is a small typo on the homepage.

Location: https://www.aptly.info/doc/feature/query/

> Operators:
>   * `=`: strict match, default operator is no operator is given

But it probably should be:

> Operators:
>   * `=`: strict match, default operator if no operator is given

Because this typo is within a normative section of the documentation, i would be happy to see this typo fixed; i guess i cannot help with that other than making this issue?

best regards!

Max

**Comment by qyanu** [comment]
i also made a pull request: https://github.com/aptly-dev/www.aptly.info/pull/108

**Comment by neolynx** [comment]
thanks a lot ! if you would like to contribute more, we can also add you as a project member...

there is an error in the pipeline, will need to check what is wrong there.

**Comment by qyanu** [comment]
no thanks; i'm just a user of aptly (and happy being just that).
