### ISSUE TITLE
"ERROR: unable to parse command" on `repo create`

### ISSUE THREAD

**Issue by joaopalet** [aptly-dev/aptly#1249]
When trying to create a repo using any option (flag), I always get an "ERROR: unable to parse command" error.

## Detailed Description
When I try to run, e.g.
```shell
aptly repo create my-repo --distribution=stable
```
I always get "ERROR: unable to parse command".

This also happens whenever I try to pass any other option (flag).

## Your Environment
- I am on macOS Sonoma 14.3.1
- Installed `aptly` through Homebrew (1.5.0)

**Comment by agimenez** [comment]
@joaopalet not sure if it's a typo, but you need to use single-dash options (very common in Go programs):

Can you try the following? `aptly repo create my-repo -distribution=stable`
