### ISSUE TITLE
Aptly support for resume downloads like wget

### ISSUE THREAD

**Issue by sgtcoder** [aptly-dev/aptly#1289]
`aptly mirror update` Max Retries should support resume download like wget has. This would allow a download from Spotify to complete successfully
![image](https://github.com/aptly-dev/aptly/assets/2577827/30df5477-7b18-421b-afdf-8352518aa754)

## Detailed Description
Spotify repo can only be downloaded with multiple retries with resume support. It would be nice for aptly to support resume support.

## Context

We can then download repos like Spotify where the connection keeps terminating

Others can then download updates to Spotify and other apps

## Possible Implementation
Depending on what you use to download the deb files, it would be nice to enable resume support like wget has by default.

## Your Environment
OS: Debian 12
Kernel: 6.6.28-x64v3-xanmod2
aptly version: 1.5.0+ds1-1+b4

**Comment by neolynx** [comment]
what downloader did you use ? there is the default and grab. The latter is supposed to continue download in a wget -c fashion. 

could you try to configure the downloader to grab in either the config or in as argument in the mirror update command ?

**Comment by sgtcoder** [comment]
I used whatever the default was. Spotify likes to disconnect every couple seconds so it needs to reconnect and resume.

I am using this command
```
aptly mirror update -keyring trustedkeys.gpg ${repo_name}
```

**Comment by neolynx** [comment]
Could you try using the grab downloader ?
```
aptly mirror update -downloader grab -keyring trustedkeys.gpg ${repo_name}
```

You could also add the -max-tries=10 option.

**Comment by sgtcoder** [comment]
Thank you, this actually worked along with max-tries=10 for spotify. I set max-tries just for spotify. It seemed to work and not corrupt.

**Comment by neolynx** [comment]
happy to hear that !

may I close this issue ?

**Comment by sgtcoder** [comment]
Yes, maybe add this to the documentation. Normally it's not a problem, but Spotify repo is messed up and needs the grab with max-tries
