### ISSUE TITLE
Aptly doesn't do proper url encoding?

### ISSUE THREAD

**Issue by shadeslayer** [aptly-dev/aptly#130]
I have packages that have '+' in the versioning, and stored on S3, the way they're accessible is by using %2b in the encoded URL instead of '+' . So while apt does this encoding properly, aptly doesn't seem to, and fails to HTTP GET packages with a '+' in their versioning.

**Comment by josephholsten** [comment]
if you end up here, you probably want `plusWorkaround`, fully doc'd at https://www.aptly.info/doc/feature/s3/
