### ISSUE TITLE
Failed to fetch http://repo.aptly.info/dists/squeeze/InRelease  403  Forbidden

### ISSUE THREAD

**Issue by n-rodriguez** [aptly-dev/aptly#1306]
Hi there!

I got this error when doing `apt-get update`

```sh
E: Failed to fetch http://repo.aptly.info/dists/squeeze/InRelease  403  Forbidden
E: The repository 'http://repo.aptly.info squeeze InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

It seems that the aptly repo is no longer public/published/signed.

Thank you!

**Comment by neolynx** [comment]
Thanks for reporting ! somehow the public access permissions were lost, could you try again ?

**Comment by n-rodriguez** [comment]
> Thanks for reporting ! somehow the public access permissions were lost, could you try again ?

It works! Thank you!
