### ISSUE TITLE
ERROR: unable to initialize GPG signer: unable to execute gpg

### ISSUE THREAD

**Issue by j75** [aptly-dev/aptly#1307]
Trying to publish a snapshot (`aptly publish snapshot -gpg-key=... snapshot`) generates the error in the title.

## Detailed Description
I think the error comes from the fact that my keyring contains several keys; if I save only a key in a keyring and use it as the default keyring then it works.

## Context
Debian 12.6 ; aptly version is **1.5.0+ds1-1+b4**

**Comment by j75** [comment]
I tried to play with parameters  `-gpg-key`, `-keyring` and `-secret-keyring` but they do not seem to be taken in account

**Comment by neolynx** [comment]
please provide the full command...

**Comment by j75** [comment]
`aptly publish snapshot -gpg-key=... first-snapshot`

**Comment by j75** [comment]
```
% aptly publish snapshot  -keyring="/home/devel/.gnupg/my-pubring.gpg" -secret-keyring="/home/devel/.gnupg/my-secring.gpg"  first-snapshot

ERROR: unable to initialize GPG signer: unable to execute gpg: exit status 2 (is gpg installed?): /home/devel/.gnupg/pubring.gpg
------------------------------
```

Please note that even I specified the **~/.gnupg/my-pubring.gpg** public keyring it still looks for **~/.gnupg/pubring.gpg** file.

**Comment by neolynx** [comment]
this works here:
```
aptly publish snapshot -architectures amd64 -distribution stable -keyring trustedkeys.gpg -gpg-key reposign@molior -batch -passphrase-file ./gpg-secret snapshot1 publish-test
```

maybe you can try without specifying the gpg full path ? it should also find the secret-keyring itself I guess...

**Comment by j75** [comment]
On Debian 12.6 the `gpg` version is **2.2.40**.

**Comment by neolynx** [comment]
ok, thanks. the debian version is a bit older, maybe tit has problems with gpg2.

could you try this:
```
aptly publish snapshot  -keyring my-pubring.gpg first-snapshot
```

and paste the command and output if it fails...

**Comment by j75** [comment]
I deleted one obsolete key from my keyring, I have exported all other keys (including secret ones) then in a  clean folder I have imported them, I have commented  ` list-options show-photos` line in the **gpg.conf** file... and now it works! I presume it was something wrong in my keyring...

I shall retry again the option `-keyring` to see what's happening, and if it works I shall close the bug.

**Comment by j75** [comment]
As I mentioned, now (after some manipulations) it works...
