### ISSUE TITLE
GPG error signatures were invalid: EXPKEYSIG 23F3D4EA75716059

### ISSUE THREAD

**Issue by gufeisheng001** [aptly-dev/aptly#1336]
## Detailed Description

GPG error: https://cli.github.com/packages stable InRelease: The following signatures were invalid: EXPKEYSIG 23F3D4EA75716059 GitHub CLI <opensource+cli@github.com>
## Context

did change acording this https://github.com/cli/cli/issues/6175 , but cant get it fix
## Possible Implementation

hopfully get an fix 
## Your Environment

Ubuntu 24.04.1 LTS
[Uploading log-build-84f3f0fb-a224-4da9-a1a6-c709fe82d013.log…]()
![Screenshot from 2024-09-08 13-15-48](https://github.com/user-attachments/assets/66d62fcb-2baf-45bb-ae4b-bfd249f3cab1)

**Comment by williammartin** [comment]
Hi from the GitHub CLI team and sorry for the inconvenience here. 

I see that you've closed this already but just in case, and for anyone else who might come across it, you'll probably want to check out the information and instructions at https://github.com/cli/cli/issues/9569. Good luck!

**Comment by alexanderLinear** [comment]
somewhere in your sources files - you might add a 2nd item to your like like in this generic example (from an outdated distro):

`deb [trusted=yes] http://archive.debian.org/debian jessie main`

(Just in case there is already some rectangular clamps expression, a space is the separator between the provided options in that block.)
