### ISSUE TITLE
only mirror the latest version of packages

### ISSUE THREAD

**Issue by gfrankliu** [aptly-dev/aptly#1372]
The origin repository may have historical versions of every packages. To reduce the mirror size, is it possible to configure aptly to only mirror the latest version of every packages? I see there is -filter option but it is unclear what condition/pattern to use so that aptly will only pull one version (latest) for every package.

**Comment by neolynx** [comment]
Hi @gfrankliu,

aptly currently cannot mirror the latest version. is this the same as  https://github.com/aptly-dev/aptly/issues/1315 ?

**Comment by gfrankliu** [comment]
Thanks! Looks indeed the same. We can close this as duplicate.

**Comment by neolynx** [comment]
closing as duplicate
