### ISSUE TITLE
add packages to an mirror (expand package filter)

### ISSUE THREAD

**Issue by ThorstenS-linux** [aptly-dev/aptly#139]
Hi,
is it possible to add packages to an mirror?
I created my wheezy-backports mirror like this:
`aptly mirror create -architectures=amd64 -filter='ansible | bind9 | bind9-host |  dnsutils | …' -filter-with-deps wheezy-backports http://ftp.de.debian.org/debian/ wheezy-backports main contrib non-free`
How can I expand this filter and add e.g. `linux-image-amd64` ?
I expected  `aptly mirror edit` could do this, but wasn`t able to achive my goal…

tia!
/thorsten

**Comment by Jorilx** [comment]
I'm sorry, I've tried
`aptly mirror edit -filter='newpackage | filter' mymirror`
but it just **literally** sets the filter to 'newpackage | filter'... Is this supposed to happen? I thought this was a way to tell aptly "add this package to the filter" without having to specify the already-present filter.

**Comment by smira** [comment]
@Jorilx no, aptly doesn't do that expansion for you

**Comment by kbiernat** [comment]
^ it would be great if it did :)
