### ISSUE TITLE
aptly install fails -- aptly conflicts with gnupg1

### ISSUE THREAD

**Issue by sf-nwaller** [aptly-dev/aptly#1394]
While attempting to try out the Aptly 1.6.0 RC (release candidate) build I encountered this installation error:

```console
~$ sudo dpkg -i aptly_1.6.0~rc1+20241117171302.763b810c_amd64.deb
dpkg: regarding aptly_1.6.0~rc1+20241117171302.763b810c_amd64.deb containing aptly:
 aptly conflicts with gnupg1
  gnupg1 (version 1.4.23-1.1build1) is present and installed.

dpkg: error processing archive aptly_1.6.0~rc1+20241117171302.763b810c_amd64.deb (--install):
 conflicting packages - not installing aptly
Errors were encountered while processing:
 aptly_1.6.0~rc1+20241117171302.763b810c_amd64.deb
```

I tried previous alpha and beta builds from the 1.6.0 line and they installed fine without any conflicts.

Is Aptly switching to `gnupg2` with the 1.6.0 release?

## Your Environment

I'm running Ubuntu 22.04 and I'm installing Aptly from a Debian package.

```console
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
```

**Comment by neolynx** [comment]
Thanks for reporting !

Since we synchronized with the official debian packaging, the Conflict was added. gnupg1 is depreciated, so I guess it is phased out. I will check with the upstream maintainer what the corresponding guidelines are...

However, aptly should not force this in the CI builds. I will revert the change, but until then you could add' -force-depends', as aptly has no hard dependency on gpg2.

**Comment by neolynx** [comment]
So, the official debian is already conflicting with gpg1 packages, therefore at some point it would be good to migrate to gpg2 if that is possible. The CI packages will not conflict anymore after #1396 is merged, but we might add it again for the final 1.6.0 version.

would it be possible for you to use gpg2 ?

**Comment by neolynx** [comment]
@sf-nwaller the Conflict has been removed from the Debian package in the CI builds

however, since the official Debian package also has this conflict, the final 1.6.0 aptly version will reintroduce it. Migrating to gpg2 would be recommended...

please let us know if this works for you !
