### ISSUE TITLE
Aptly snapshot verify misses "python:any"

### ISSUE THREAD

**Issue by markabey** [aptly-dev/aptly#145]
Aptly version 0.8
I made a snapshot, and have a package which depends on "python:any" and python present. Verifying it will say:

```
Loading packages...
Verifying...
Missing dependencies (1):
   python:any (>=2.7.1-0ubuntu2) [amd64]
```

However, "python" is present, and if I do "aptitude show python" it says that it provides python:any.

**Comment by freenerd** [comment]
I ran into the same problem when building `python-pip` and `build-essential`. Below is the package description for `python-pip`.

```
Package: python-pip
Priority: optional
Section: universe/python
Installed-Size: 468
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Architecture: all
Version: 1.5.4-1
Depends: python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), ca-certificates, python-colorama, python-distlib, python-html5lib, python-pkg-resources, python-setuptools (>= 0.6c1), python-six, python-requests
Recommends: build-essential, python-dev-all (>= 2.6)
Filename: pool/main/p/python-pip/python-pip_1.5.4-1_all.deb
Size: 97718
MD5sum: 8e1c420453fdf284e1ccc59adb219f97
SHA1: 31c72bbfbe09b2bed315ecb02325935231eb72de
SHA256: c27c58a2a4c72cbfacb694d7abd3afc54f85f4b4b5bade714d83fa4d0cc9343a
Description: alternative Python package installer
Description-md5: 8d21e4048f43043df36daaae334010b5
Homepage: http://www.pip-installer.org/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
```

I bounced around in the code to see if I can fix it myself, but was unsure about where to look. It must be in https://github.com/smira/aptly/blob/master/deb/package.go, not? Some pointers into the right direction would be appreciated @smira

**Comment by smira** [comment]
@freenerd dependency resolution code is here: https://github.com/smira/aptly/blob/master/deb/list.go#L256

I believe it should parse `:any` part there, but fix could be more complicated.

Some notes by @oCCtet here: https://groups.google.com/d/msg/aptly-discuss/CDXPwRamCTs/SsKPH8ABqgEJ

**Comment by hkdsun** [comment]
Any updates on this?

**Comment by rmedaer** [comment]
The commit/PR above should fix this issue.
