### ISSUE TITLE
Publishing to `all` architecture

### ISSUE THREAD

**Issue by smira** [aptly-dev/aptly#165]
Architecture `all` should be useful by itself when mirroring and publishing probably.

From gitter.im logs:

  Is there a way to publish a repository that only contains the architecture "all"?
  seaninspace January 7 2015 
  Or is there a way to get the "all" architecture accepted when you leave the architectures field in aptly.conf as so: []
   Because when you define architectures in the aptly.conf it will complain when trying to create a mirror   when "all" doesn't exist in the mirror, but you need to define it in order to publish a repo that only contains "all" architecture packages.
smira January 7 2015 
@seaninspace you don't need to put "all" into architectures list in ~/.aptly.conf. In order to publish repository with only "all" packages you need to specify some 'real' architectures (like i386 or amd64).
published repositories always have some "real" architectures, and packages with architecture all appear in all architectures' packages indexes.
seaninspace 14 hours ago 
@smira why isn't "binary-all" considered a "real" architecture?
@smira I can't define the architectures for other people since I don't know what they will contain. I can't define a set of architectures to ensure that repos/mirrors/snapshots that only contain "all" packages get published without worrying that the definition of architectures will prevent some mirrors from downloading or some repos/snapshots from breaking when Aptly tries to publish them
seaninspace 14 hours ago 
all through the aptly.conf file, I'm aware of the command line options. It's just not possible that way since I am not able to publish all items on my own. The idea of the blank architectures as a way to just "go by what the package states" is what I was hoping it would be...
smira 21 minutes ago
@seaninspace good question, probably all deserves its own place while publishing. I thought that it's useless, but now I feel it should be supported

**Comment by kumy** [comment]
FTR, `aptly` can't guess architectures for mirror `elasticsearch`.

here is an example: http://pastebin.com/1GALeZcg

**Comment by smira** [comment]
@kumy quite expected - Release file doesn't contain architectures list. there's an option to guess from filenames listed there

**Comment by neolynx** [comment]
aptly had some issues fixed with mirroring and architecture guessing, especially for flat mirrors. please try latest version...
