### ISSUE TITLE
APIs for merge/pull snapshots

### ISSUE THREAD

**Issue by smira** [aptly-dev/aptly#176]
They're non-trivial to implement in client-side code.

Extracted from #168

**Comment by findmyname666** [comment]
Hello there,

I would like to ask whether is there any timeline for implementation of API endpoint for merge operation?
Is there required any help with that?

Thx
BR

**Comment by xaoc7** [comment]
Is there any plans to introduce API for merging snapshots soon?

**Comment by randombenj** [comment]
@reglim Do you want to have a look at this?

**Comment by reglim** [comment]
@randombenj Yeah, I'll try to add that.

**Comment by iofq** [comment]
fixed in https://github.com/aptly-dev/aptly/pull/1157
