### ISSUE TITLE
Better documentation of the config file

### ISSUE THREAD

**Issue by jmoratilla** [aptly-dev/aptly#20]
Hello Andrey! Let me say that aptly is great! I'm migrating from reprepro to aptly and everything is smooth. Thanks!

I have a problem with some parameters like architectures, where doc says "architectures is a list of architectures to process; if left empty defaults to all available architectures; could be overridden with option -architectures"

I left it empty, but when I tried to publish a snapshot with this command line: 

```
# aptly publish snapshot -distribution="quantal" 20140318-stable
Loading packages...
```

it complains with:

```
ERROR: unable to publish: unable to figure out list of architectures, please supply explicit list
```

No matter what arguments or which order I pass to aptly:

```
# aptly publish snapshot -distribution="quantal" -architecture="" 20140318-stable
flag provided but not defined: -architecture
# aptly publish snapshot -distribution="quantal" -architecture="amd64" 20140318-stable
flag provided but not defined: -architecture
# aptly publish snapshot -distribution="quantal" -architecture="[amd64]" 20140318-stable
flag provided but not defined: -architecture
# aptly publish snapshot -architecture=amd64 -distribution="quantal"  20140318-stable
flag provided but not defined: -architecture
```

Finally I came up with the solution of setting the architectures in the config file (attached below).  Is this a bug, or is a documentation defect or may be I'm wrong with something?

```
{
  "rootDir": "/var/www/repository",
  "downloadConcurrency": 4,
  "architectures": ["amd64","i386"],
  "dependencyFollowSuggests": false,
  "dependencyFollowRecommends": false,
  "dependencyFollowAllVariants": false,
  "dependencyFollowSource": false,
  "gpgDisableSign": true,
  "gpgDisableVerify": true,
  "downloadSourcePackages": false,
  "ppaDistributorID": "ubuntu",
  "ppaCodename": ""
}

```

**Comment by aioue** [comment]
architecture error message is still not obvious.You can do this and get the error in 0.95:
![image](https://cloud.githubusercontent.com/assets/1254905/6714905/d664e07a-cd92-11e4-91d0-8b6a973c5354.png)

Which prompted me to do this:
![image](https://cloud.githubusercontent.com/assets/1254905/6714936/052db90e-cd93-11e4-8ed1-7e652201b56a.png)

Which led to this mess!
![image](https://cloud.githubusercontent.com/assets/1254905/6714943/1b807840-cd93-11e4-9234-88b8dde1339a.png)

**Comment by smira** [comment]
yes, if you place flags after arguments, they would be arguments :)
