### ISSUE TITLE
publish whith debian-installer image

### ISSUE THREAD

**Issue by gdbdzgd** [aptly-dev/aptly#240]
aplty is a best tools i'm using.
i'll rebuild debian installer image some time.

it's image is debian-installer-images_20150324_amd64.tar.gz
it will dcompress at `dists/DISTRIBUTION/main/`

```
dists/DISTRIBUTION/main/intstaller-ARCH/current 
```

could you please add this a feature  to manage debian-installer-images-xxx.tar.gz 
as  debian offical tools has?

**Comment by avongluck-r1soft** [comment]
<3 aptly.  This would be handy for us as well.  We build bootable iso's from repos and this would streamline the process quite a bit.
