### ISSUE TITLE
don't fail on nonexisting architecture in dist

### ISSUE THREAD

**Issue by deknos** [aptly-dev/aptly#250]
Hi,
I have following issue:
I have a release file, which has as architecture amd64 listed, but in dists/lucid/component, there is NO architecture, only binary-i386 and source. But mirroring (like in the log in the appended text) fails. It should not fail, or there should be a non/strict mode. It should issue an warning.

``` bash
user@machine:~$ cat .aptly.conf 
{
  "rootDir": "$HOME/.aptly",
  "downloadConcurrency": 4,
  "downloadSpeedLimit": 0,
  "dependencyFollowSuggests": true,
  "dependencyFollowRecommends": true,
  "dependencyFollowAllVariants": true,
  "dependencyFollowSource": true,
  "gpgDisableSign": true,
  "gpgDisableVerify": true,
  "downloadSourcePackages": true
}

user@machine:~$ aptly mirror create trinity#lucid#main http://buildserv.mydomain.com/ubuntu/trinity-v3.5.13 lucid main
user@machine:~$ aptly mirror update trinity#lucid#main
Downloading http://buildserv.mydomain.com/ubuntu/trinity-v3.5.13/dists/lucid/Release...
Downloading & parsing package files...
Downloading http://buildserv.mydomain.com/ubuntu/trinity-v3.5.13/dists/lucid/main/binary-amd64/Packages.bz2...
Downloading http://buildserv.mydomain.com/ubuntu/trinity-v3.5.13/dists/lucid/main/binary-amd64/Packages.gz...
Downloading http://buildserv.mydomain.com/ubuntu/trinity-v3.5.13/dists/lucid/main/binary-amd64/Packages...
ERROR: unable to update: HTTP code 404 while fetching http://buildserv.mydomain.com/ubuntu/trinity-v3.5.13/dists/lucid/main/binary-amd64/Packages
```

**Comment by smira** [comment]
Do you believe that aptly should use different architectures list for different components?

Btw, you can fix that by passing list of architectures to `aptly mirror create` as `-architectures=i386`.

**Comment by deknos** [comment]
I don't know, if aptly should use different architectures for different components in general. But for me it is a use case, which i cannot change in the forseeable future. sadly.

As with the architecture parameter, i had another problem, but first i have to verify if this was not my fuckup.

**Comment by neolynx** [comment]
aptly had several fixes with mirror architectures fixed. please try latest version...
