### ISSUE TITLE
copy packages from mirror/snapshot to repo

### ISSUE THREAD

**Issue by sandrotosi** [aptly-dev/aptly#265]
hello,
at the moment is not possible to copy a package from a mirror (or a snapshot) to a repo

```
$ sudo aptly repo -dry-run=true copy <mirror-name> <repo-name> <package>
ERROR: unable to copy: local repo with name <mirror-name> not found
```

but it would be interesting to have that possibility

**Comment by smira** [comment]
You can copy from mirror to repo using `aptly repo import ...`.

**Comment by kumy** [comment]
See the schema at http://www.aptly.info/doc/overview/

![](http://www.aptly.info/img/schema.png)

**Comment by sandrotosi** [comment]
oh wow I see, thanks! but i cant import from a snapshot to a repo, right? that would be helpful (maybe just extend repo import to accept also a snapshot and not only a mirror?)

**Comment by smira** [comment]
@sandrotosi it's possible to implement that (should be really easy), but there's no command to do that at the moment.

You can do it with API, but it is not exposed in CLI.

**Comment by GLolol** [comment]
:+1: for importing packages from snapshots -&gt; repos. It would make removed packages a lot easier to restore if they are ever needed again.

**Comment by FredFool** [comment]
Just realized how nice import from snapshots would be :) Would really like that to be coming. Any idea when 0.9.6 might happen?

**Comment by abh23** [comment]
I see this was removed from the milestone on 27th March 2017. Any chances of implementing this enhancement for next or subsequent release?

**Comment by fewaffles** [comment]
See issues #496 and #497 for ```aptly repo create ... from snapshot```.  It is not exactly what is requested here, but it might help to enable some use cases.

**Comment by smira** [comment]
Thanks @fewaffles 

This should be easy to do today via [aptly repo create .. from snapshot](https://www.aptly.info/doc/aptly/repo/create/) followed by [aptly repo copy](https://www.aptly.info/doc/aptly/repo/copy/).

Closing as it's already available
