### ISSUE TITLE
Unable to mirror installer-amd64

### ISSUE THREAD

**Issue by oddjobz** [aptly-dev/aptly#304]
Hi, aptly looks great and for the most part does what I want, but I can't seem to make it mirror the installer-amd64 folder ... which I need for 'debian-cd'. I have udebs turned on, is there anything else I need to do ?? (it picks up binary-amd64 and debian-installer only).

``` bash
# aptly mirror show jessie-main
Name: jessie-main
Archive Root URL: http://ftp.uk.debian.org/debian/
Distribution: jessie
Components: main
Architectures: amd64
Download Sources: no
Download .udebs: yes
Last update: 2015-09-28 19:08:29 BST
Number of packages: 42630

Information from release file:
Architectures: amd64 arm64 armel armhf i386 mips mipsel powerpc ppc64el s390x
Codename: jessie
Components: main contrib non-free
Date: Sat, 05 Sep 2015 09:41:57 UTC
Description:  Debian 8.2 Released 05 September 2015

Label: Debian
Origin: Debian
Suite: stable
Version: 8.2
```

``` bash
# ls public/dists/jessie/main/
binary-amd64  debian-installer
```

``` bash
# aptly mirror list
List of mirrors:
 * [jessie-contrib]: http://ftp.uk.debian.org/debian/ jessie [udeb]
 * [jessie-main]: http://ftp.uk.debian.org/debian/ jessie [udeb]
 * [jessie-non-free]: http://ftp.uk.debian.org/debian/ jessie [udeb]
```

**Comment by oddjobz** [comment]
(I've also been able to find out how to make it include the "doc" folder and the README files if anyone has any pointers?)

**Comment by smira** [comment]
@oddjobz installer-amd64 is not supported. you can put any additional files into `public/` folder (where aptly does publishing), aptly won't touch them

**Comment by oddjobz** [comment]
Ok, tvm.

**Comment by bymarshall** [comment]
This feature will be added in future releases??

**Comment by maltzsama** [comment]
Yeah, this feature will be added?

**Comment by smira** [comment]
no plans so far...

**Comment by mischelebuha** [comment]
Projects like elbe [https://elbe-rfs.org/](url) are already being fed by aplty. Here it would be nice if you could provide with aplty a complete debian mirror. This also includes the installers.
