### ISSUE TITLE
apt-get update failing when mirrors are being updated

### ISSUE THREAD

**Issue by antonio** [aptly-dev/aptly#313]
We have a server that is mirroring every single apt repo our infrastructure depends on. Those mirrors are imported to local repositories, which are then published. There is a cron job running several times a day that updates the mirrors, re-imports the contents to the local repositories and runs `aptly publish update`.

When another host is running `apt-get update` and the sync job is being run (which by the way takes around 20 minutes), we are sometimes experiencing the following error in the client:

```
Ign https://mirrors precise/multiverse Translation-en
Ign https://mirrors precise/restricted Translation-en
Ign https://mirrors precise/universe Translation-en
Ign https://mirrors precise-security/main Translation-en
Ign https://mirrors precise-security/multiverse Translation-en
Ign https://mirrors precise-security/restricted Translation-en
Ign https://mirrors precise-security/universe Translation-en
Ign https://mirrors precise-updates/main Translation-en
Ign https://mirrors precise-updates/multiverse Translation-en
Ign https://mirrors precise-updates/restricted Translation-en
Ign https://mirrors precise-updates/universe Translation-en
Fetched 6251 kB in 16s (380 kB/s)
W: Failed to fetch https://mirrors/precise/dists/precise/main/binary-i386/Packages  Hash Sum mismatch

W: Failed to fetch https://mirrors/precise/dists/precise/restricted/binary-i386/Packages  Hash Sum mismatch

W: Failed to fetch https://mirrors/precise/dists/precise/universe/binary-i386/Packages  Hash Sum mismatch

W: Failed to fetch https://mirrors/precise/dists/precise/multiverse/binary-i386/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

According to [this comment](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/628#note_1715018) and [also this one](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/628#note_1824330), this could be an issue in the design of `apt`, but I'd like to get a second opinion if possible.

Thanks!

**Comment by smira** [comment]
https://bugs.launchpad.net/ubuntu/+source/apt/+bug/972077

https://bugs.launchpad.net/launchpad/+bug/1430011

**Comment by smira** [comment]
https://anonscm.debian.org/cgit/apt/apt.git/diff/?id=af81ab9

**Comment by smira** [comment]
PR #354 is first step towards fixing hash sum mismatch problem

**Comment by sliverc** [comment]
I think this has been solved by introducing Acquire-By-Hash support. See https://github.com/aptly-dev/aptly/pull/664

Closing this issue. If there is still anything concerning this issue not covered by acquire by hash please comment.

**Comment by antonio** [comment]
> I think this has been solved by introducing Acquire-By-Hash support. See #664

Certainly! Thanks for cleaning up after me :smile:

**Comment by divyaan23** [comment]
Hi,
When I am using "aptly task run" using file like below. I am unable to update the mirrors with command mentioned in repos.txt
 aptly task run -filename="repos.txt"

repos.txt content
mirror create -architectures=amd64 bionic-test4 http://archive.ubuntu.com/ubuntu bionic main
mirror update bionic-test4

Kindly help.
Thanks in advance!
