### ISSUE TITLE
Feature request: publish to Azure Storage

### ISSUE THREAD

**Issue by directhex** [aptly-dev/aptly#379]
This is basically Microsoft's equivalent to S3.

There's an Azure Go SDK at https://github.com/Azure/azure-sdk-for-go

**Comment by samoz83** [comment]
Is this feature still planned?

**Comment by chuan** [comment]
@lbolla I think this issue can be closed as the PR (https://github.com/aptly-dev/aptly/pull/413) is merged.

**Comment by lbolla** [comment]
Gladly!
