### ISSUE TITLE
Issues with aptly keeping old versions in S3 bucket

### ISSUE THREAD

**Issue by lanmalkieri** [aptly-dev/aptly#394]
Hello, 

I am new to aptly and recently inherited an architecture that uses it at our company. 

I was hoping to get some insight. I generally create a deb package with jenkins using the following shell commands. 
# Create deb file out of source code

dpkg-deb --build ${WORKSPACE}/validation-scripts
# Add package to apt repo

aptly repo add -remove-files=false -force-replace=true $env ${WORKSPACE}/validation-scripts.deb
aptly publish -force-overwrite=false update $env s3:#############:

So my first few attempts at this I had some issues with some top level files not being where they should have been which I believe gave me this error. 

E: Problem parsing dependency Depends
E: Error occurred while processing validation-scripts (NewVersion2)
E: Problem with MergeList /var/lib/apt/lists/s3-us-west-2.amazonaws.com_############_aptly_dists_dev_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.

I was hoping someone here could guide me in the right direction to helping me understand what the problem is here? 

Is it possible to list s3 repos? When I run the command aptly repo list on my jenkins server I have no local repo's. So I assume they are never created here and are always pushed to our s3 bucket. 

How can I gou about cleaning up a particular package from the s3 bucket? Is this something aptly can do? I know it has added entries for old versions in it's package files and whatnot. 

Any advice here would be greatly appreciated.

**Comment by smira** [comment]
aptly itself keeps all your package files and database how those packages are organized into mirrors, snapshots and local repos.

When snapshot or local repo is published, aptly creates repository structure which is consumed by `apt-get` tool. It doesn't really matter if publishing is going to local FS or S3.

**Comment by smira** [comment]
So if you update repo or create new snapshot and publish it to S3 or local fs, aptly would perform actions matching this update: add new packages, remove outdated packages.
