### ISSUE TITLE
with architectures specified in config file source indexes are not generated

### ISSUE THREAD

**Issue by sdelafond** [aptly-dev/aptly#403]
From http://bugs.debian.org/824609:

| I noticed that even though I included --with-sources=true in my mirror
| create when I published the snapshot, source indexes were not being
| generated, even though .dsc files were being included in the public
| pool.
| 
| The issue seems to be that I included a set of architectures in my
| ~/.aptly.conf.
| 
| If I specify the architectures only on the mirror create command line,
| things seem to work correctly.
| 
| I tried including source directly in the architectures, but that
| didn't really work well either.  The mirror create failed because
| source was not in the architectures line from the Release.  And in at
| least some of my tests I ended up with either an empty Sources index
| or in one case 37 megabytes starting with a lot of nulls that was very
| definitely not a Debian index.

**Comment by sdelafond** [comment]
Any news on this one ? :)

**Comment by smira** [comment]
Sounds like a bug, I believe architecture handling in aptly today is not consistent. I'll take a look

**Comment by sdelafond** [comment]
@lbolla do you mean this is now fixed? If so, could you point me to the relevant commit(s) so I can update the Debian bugtracker accordingly?

**Comment by lbolla** [comment]
@sdelafond We couldn't reproduce it in our testing. Would you be able to help us reproduce it, with some detailed instructions?

**Comment by sdelafond** [comment]
I'll try and ask the original reporter (I'm just the Debian package maintainer) if he can help with that, and I'll get back to you then.

**Comment by lbolla** [comment]
@sdelafond I appreciate it. Sorry for the confusion.

**Comment by sdelafond** [comment]
@lbolla no worries I understand cleaning up old issues, I was just confused about the reason :)

There: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824609#16

**Comment by sdelafond** [comment]
It apparently can't be reproduced anymore, so the Debian bug was just closed; feel free to close this one as well!

**Comment by lbolla** [comment]
Cheers!
