### ISSUE TITLE
What came out of the call for new maintainers?

### ISSUE THREAD

**Issue by FredFoo** [aptly-dev/aptly#456]
Howdy!

A while ago Andrey [send out a call for new maintainers](https://groups.google.com/forum/#!topic/aptly-discuss/ZZQ6KUrVUpE) and a few guys seemed keen to join. But the thread has since gone cold and no news have surfaced. 

What came out of it? Is there a team catching up behind the curtains? Is there a fork of the project that now receives patches and updates? Transition paths? Plans?

I would like to help, too. Would like to work on rpm/yum integration. But currently it seems there is nobody who I could turn to :)

So, speak up! Let us know if we can help to pump some fresh juice into this nice project.

**Comment by smira** [comment]
That is totally my fault. I didn't have time even to follow up this thread. 

So I'm back and trying to go through the queue and restore the release schedule.

At the same time I would like to establish team of maintainers to help getting aptly development up to speed.

**Comment by smira** [comment]
See also #469 and #470

**Comment by sliverc** [comment]
A maintainer team has been been formed. See #725 for details. Hence closing this issue.
