### ISSUE TITLE
Can't mirror jenkins repository

### ISSUE THREAD

**Issue by oker1** [aptly-dev/aptly#47]
The repository is flat, but it has a component named binary:

```
$ aptly -architectures="amd64" mirror create jenkins http://pkg.jenkins-ci.org/debian-stable/ ./ binary
ERROR: unable to create mirror: components aren't supported for flat repos

$ aptly -architectures="amd64" mirror create jenkins http://pkg.jenkins-ci.org/debian-stable/binary ./
$ aptly mirror update jenkins
...
ERROR: unable to update: download errors:
  HTTP code 404 while fetching http://pkg.jenkins-ci.org/debian-stable/binary/binary/jenkins_1.554.1_all.deb
```

**Comment by geek876** [comment]
@smira and @word. Can I please clarify this ? I am trying to build http://pkg.jenkins-ci.org/debian-stable/. Can create mirror as discussed above. Howerver, can I ask how are you able to publish it ? I want to publish it in the same way as the source (see doc http://pkg.jenkins-ci.org/debian-stable/ ). This is all-distribution version so when I omit the -distribution="vivid" flag while publishing,
` aptly publish snapshot -architecture="amd64" snapshot-name /jenkins` , I don't get anything under the dists/ folder of the published repo and hence apt-get update on the clients fail with error below. And I add the repo as per the document (i.e. deb http://aptly-url/jenkins binary/)

`
Ign http://aptly-url/jenkins binary/ InRelease
Ign http://aptly-url/jenkins binary/ binary/ Release.gpg
Ign http://aptly-url/jenkins binary/ binary/ Release
Err http://aptly-url/jenkins binary/ binary/ Packages
`

**Comment by smira** [comment]
@geek876 aptly doesn't support "flat" repository format while publishing. Why do you need flat format? apt-get is able to consume both formats?

**Comment by geek876** [comment]
@smira: apt-get does consume both formats I suppose. That's what the doc suggests  http://pkg.jenkins-ci.org/debian-stable/. We are using aptly to version-control our packages. So every so often, we update the mirrors, take snap and publish it. In case of reversion, we simply revert back to the previous `good` snap. We want to bring along Jenkins repository too within our regime and hence there is a need to snap and publish it. Any alternatives ?

**Comment by smira** [comment]
@geek876 no, apt-get can handle both formats easily. Flat format is kind of legacy and it has its own problems. Mirror your repo, snapshot, publish it and take URL which aptly suggests to use to apt-get. It should work.

**Comment by phyber** [comment]
Has this changed again recently?
```$ aptly mirror create jenkins-binary-lts http://pkg.jenkins-ci.org/debian-stable binary/
Downloading http://pkg.jenkins-ci.org/debian-stable/binary/InRelease...
Downloading http://pkg.jenkins-ci.org/debian-stable/binary/Release...
ERROR: unable to fetch mirror: http://pkg.jenkins-ci.org/debian-stable/binary/Release: Get http:/debian-stable/binary/Release: dial tcp 52.202.51.185:80: i/o timeout```

Why is it trying to connect to `http://debian-stable` at the end there?

**Comment by FlorentCoppint** [comment]
@phyber I think "http:/debian-stable" is just a display issue, it tries to connect to real server "52.202.51.185:80" which is not responding. I have the problem, it's a Jenkins related issue, not Aptly's.

**Comment by phyber** [comment]
@FlorentCoppint yeah, I was just replying with that after I noticed just a single `/` in `http:/debian-stable`.
I guess the bug here is a display issue with the error message, you're right.
