### ISSUE TITLE
list deb files

### ISSUE THREAD

**Issue by philtay** [aptly-dev/aptly#479]
Is there any builtin way to list all .deb files (full absolute paths) in a given repository?
To be more clear and as a mere example: I'm looking for the kind of list that can be piped to xargs.
Please consider this as a feature request if the answer to the above question is no.

**Comment by smira** [comment]
Good question, I would imagine we should expose it via https://www.aptly.info/doc/feature/package-display/ interface? So that packages would be part of the context available to the template. Thoughts?

**Comment by philtay** [comment]
Yes, it would be a good solution. Please also consider adding a "sugar" package query to just mean "all packages". Something like `aptly repo search -format="{{.Path}}" myrepo *`.

**Comment by smira** [comment]
It's already there, but not obvious, easiest "always true" filter is `Name` (which means non-empty package name)

**Comment by philtay** [comment]
Ah, ok. Maybe we could support something more obvious, like the lack of a package query means "all". `aptly repo search -format="{{.Path}}" myrepo` instead of `aptly repo search -format="{{.Path}}" myrepo Name`.

**Comment by smira** [comment]
Good idea, thanks!
