### ISSUE TITLE
Better error messages when bzip2 fails

### ISSUE THREAD

**Issue by wolfgang42** [aptly-dev/aptly#526]
I was trying to publish a snapshot and got this error message:
```
ERROR: unable to publish: unable to compress index file: exit status 1
```
I managed to figure out by reading the source code that this exit code is coming from `bzip2`, but the bzip2 manual merely says that one means "environmental problems". In #427 this turned out to be a disk space problem; in my case it turned out that the `bzip2` I had came from BusyBox and didn't understand the `-k` flag.

It would be very helpful if the stderr from the process was also printed so the error message could be determined for the specific situation at hand.

**Comment by smira** [comment]
#547 should fix that
