### ISSUE TITLE
aptly graph deletes generated image

### ISSUE THREAD

**Issue by cobra** [aptly-dev/aptly#541]
The output file of `aptly graph` is deleted after a second after loading it into the user's image viewer. Some image viewers like eog (from gnome) monitor the file and just show a blank screen when the current file is deleted, rendering the whole process useless.

I don't see a completely ideal solution at the moment. Piling up temporary files (like aptly did before #500 was fixed) is not really elegant, but at least nothing gets lost. Launching a viewer and immediately deleting the file causes this issue. Waiting for the viewer to exit isn't sure either, as it might just be a wrapper and aptly will just keep running needlessly.

**Comment by smira** [comment]
Should we change default viewer to something like `firefox`, `chrome` ? Something which is fine with deleted file? (just a thought)

**Comment by cobra** [comment]
I don't like this idea. Personally, that'd be fine, I have chrome running most of the time anyway, but I don't think everyone is doing this. Also, how would aptly find the correct browser? `sensible-browser` maybe. Still, it'd be a weird workaround for a specific image viewer.

A different idea: why not use the same temporary file for each invocation? That does work on linux (that's what I'm doing when using LaTeX, open the output pdf once and let the viewer reload or auto-reload on each pdflatex run) and I expect that macOS would allow this as well. Windows has some problems with that, but… eh, that's what you get.

**Comment by smira** [comment]
aptly doesn't work on Windows :) 

Fixed filename implies we have attack vector on aptly predictably rewriting this file if it's in `/tmp`

**Comment by cobra** [comment]
Well, there's WSL and that should enable aptly on Windows. I don't know what happens with WSL and this "overwrite a file already opened by something else" scenario, haven't played with WSL yet. But this whole WSL thing is still beta and I'd call everything happening there unsupported unless stated otherwise.

What do you mean by attack vector? I'm not sure I can follow you here, that's a simple write-only operation, right?

**Comment by smira** [comment]
As `/tmp` allows anyone to create files there, if filename is predictable and aptly runs as root, you can trick aptly into writing to file which might overwrite something in the system. It's generic security best practice.

**Comment by cobra** [comment]
I didn't expect people to run aptly as root, but you're completely right. Might cause some other problems with graph then, as whatever aptly is starting gets executed as root, but that's to be expected.

The only other thing I can come up with would be a small helper taking care of the output image. aptly graph does what it does now until the file is generated and then launches the helper in the background which will do the magic from #500 and wait for whatever was launched to terminate. This way `/tmp` gets cleaned up and aptly is not blocked.

Alternatively just keep littering `/tmp`.
