### ISSUE TITLE
Packages which only differ in file name are seen as conflicting when added to a repository

### ISSUE THREAD

**Issue by RubenDZ** [aptly-dev/aptly#552]
When trying to add a package to a repository (repo add <repo> <package>) which only differs in file name with one that is already in the repository, aptly reports a conflict.  
However, according to the documentation a duplicate package should only occur when packages with same tuple (package name, version, arch) and *different content* are added to the same repository.

## Context
At some point, I have to change certain characters in our package file names.  In particular I change ':' into '-' before I add packages to a FAT filesystem on an ISO.  Later on, when I add the original package to this system's repository which still has a ':' in the filename, this causes a conflict.

I tried to work around the issue by using the '-force-replace=true' flag on the repo add command.  Although this works for adding the package, it later on fails again with a conflict when trying to import a mirror from this repository into another repository.  At this point I'm stuck as the repo import command has no support for a -force-replace flag.

## Details

1. Consider a repo having the package openssh-server_1-6.6p1-2ubuntu2.8_amd64.deb
2. I rename the package to openssh-server_1:6.6p1-2ubuntu2.8_amd64.deb
3. Trying to add the package to the repository fails
```
$ sudo aptly --config packagerepo.json repo add base-repository openssh-server_1:6.6p1-2ubuntu2.8_amd64.deb
Loading packages...
[!] Unable to add package to repo openssh-server_1:6.6p1-2ubuntu2.8_amd64: conflict in package openssh-server_1:6.6p1-2ubuntu2.8_amd64
[!] Some files were skipped due to errors:
  openssh-server_1:6.6p1-2ubuntu2.8+amplidata1_amd64.deb
ERROR: some files failed to be added
```
Note that the error message does seem to indicate that the metadata of the package is twice the same.  (Actually all content is exactly the same, only the filename differs.)
4. When adding -force-replace, it works to add the package.
5. However, this fails later on when on a remote machine:
   1. Create mirror from base-repository: works
   2. Update mirror: works
   3. Import mirror to a local base-repository repository fails
```
aptly --config packagerepo.json  repo import base_mirror base-repository 'Name (~ .*)']. 
Reason: Loading packages...
ERROR: unable to import: conflict in package openssh-server_1:6.6p1-2ubuntu2.8_amd64
```
6. I don't know how to work around as there are no -force-replace flags on these commands.

Rather than providing flags in these commands, I would assume that I don't have to work around these conflicts as they shouldn't really be considered as conflicts in the first place?

**Comment by smira** [comment]
aptly internally produces unique key for the package which consists of package name, arch, version and package filenames plus all the hash sums. So package is considered identical if key is the same. That's the way aptly deduplicates the packages across different sources.

At the same time all major lists (mirror, snapshot, local repo) are protected from duplicate package in Debian sense, which is "name-arch-version" key. 

So if you change filename, for aptly that's different package. We can argue whether it's good or bad, but that's how things are. Because package in the end would be deduplicated with one filename or another otherwise which you won't like as well.

So, I don't know what your package flow is, but you can't really mix packages like you described in single repo. You can keep them in different repos without any issue.

**Comment by RubenDZ** [comment]
Thanks for the clarification.

What's the reason behind not having a -force-replace flag on a repo import?  This flag does allow me to add a renamed package to a local repository, but I see no reasonable way to add/replace this renamed package to a mirrored repo (by updating the remote mirror - which works - and then importing it to a local repo on the remote, which fails on the conflict again).

**Comment by smira** [comment]
No good reason for missing `-force-replace`, PR is welcome! :)

**Comment by savon-noir** [comment]
user@hostname:~$ aptly repo add -h 2>&1|grep replace
  -force-replace: when adding package that conflicts with existing package, remove existing package
user@hostname:~$

**Comment by smira** [comment]
I think issue was around `aptly repo import`, not `aptly repo add`
