### ISSUE TITLE
API does not allow removal of snapshots with slashes in their names

### ISSUE THREAD

**Issue by GeorgeKT** [aptly-dev/aptly#561]
## Detailed Description

With the snapshot api it is possible to create a snapshot with a name containing slashes in them. Because the snapshot name is passed as a parameter in the JSON of the POST request.

However, it is impossible to drop this snapshot using the API because the  DELETE /api/snapshots/:name rest call, does not allow for slashes (you get a 404, as this is a different rest path). And the replace slashes with underscores trick, which is used in some API calls, is not done for this call. It is perfectly possible to delete the snapshot using the command line tool.

## Possible Implementation
Obviously, you could allow the same trick with the underscore, as is used in several publish calls for the prefix.
Other option would be to outlaw the use of slashes in snapshot names.

## Your Environment
Ubuntu xenial

**Comment by mauricemeyer** [comment]
This also affects the publish API (as far as I tested):

```
aptly@aptly:~$ curl -X PUT localhost:8080/api/publish/:current/tmux/bionic
404 page not found
```

I'm pretty sure it affects all API paths that are in the URL. Unfortunately, urlencoding a `/` as `%2F` does not work.

**Comment by smira** [comment]
These should be two different issues - aptly doesn't allow `/` in distribution names (nor in API neither in CLI). Snapshot name with `/` and API is a bug in aptly
