### ISSUE TITLE
When updating a published repo, custom files in updated pool component(s) are wiped

### ISSUE THREAD

**Issue by jlu5** [aptly-dev/aptly#572]
Currently, I use a script to generate deb changelogs and place them in the same folder as the relevant .deb's. However, on every "publish update" call, all changelogs for the component that was published (e.g. all .changelog files in `public/pool/main/` if I'm publishing the "main" component) are wiped. My workaround so far is to use a changelog cache folder, and hardlink the changelog files to where they should be instead of generating the changelogs whenever they're missing (this is CPU heavy).

I suspect that the cleanup step is what's causing this: `Cleaning up prefix "." components main...`, and from discussions on Gitter it seems that it's unintentional to wipe other files in `pool/`.

Version wise, I'm using aptly `1.0.0+30+ga245b72` on Debian Jessie. The changelog script is [here](https://github.com/utopia-repository/utopia-scripts/blob/master/aptlylist.py) for reference.

**Comment by smira** [comment]
Yes, that's true... aptly cleans up `pool/` subdirectory by walking every file there and checking whether it is referenced or not. 

I wonder if we should add option to ignore completely files which match some pattern?
