### ISSUE TITLE
The /debian-installer directoy should be created even if the component doesnt includes udebs

### ISSUE THREAD

**Issue by cdggcali** [aptly-dev/aptly#580]
## Detailed Description
While mirroring Ubuntu repositories we noticed the debian-installer is NOT create for all components.

For example: 
We are publishing the component s individually:
```
# ls -l public/latest/dists/trusty/
total 76
-rw-r-----. 1 www-data www-data 27672 May 25 12:07 InRelease
drwxr-x---. 5 www-data www-data  4096 May 25 12:07 main
drwxr-x---. 4 www-data www-data  4096 May 25 12:07 multiverse
-rw-r-----. 1 www-data www-data 27150 May 25 12:07 Release
-rw-r-----. 1 www-data www-data   473 May 25 12:07 Release.gpg
drwxr-x---. 4 www-data www-data  4096 May 25 12:07 restricted
drwxr-x---. 5 www-data www-data  4096 May 25 12:07 universe
#
```

But a you can see the debian-installer directory was only created for the main and universe components:
```
# find public/latest/dists/trusty -type d -name debian-installer
public/latest/dists/trusty/main/debian-installer
public/latest/dists/trusty/universe/debian-installer
#
```

The ubuntu mirrors do have the http://mirrors.mit.edu/ubuntu/dists/trusty/multiverse/debian-installer/binary-i386/ directory.

## Context
We have aptly masters and slaves servers, since the debian-installer is not present on the master server, the slave fails to update the mirror because is not able to find http://<master server>/ubuntu/latest/dists/trusty/multiverse/debian-installer/binary-i386/Packages 

```
# aptly mirror update trusty-multiverse-mirror
Downloading http://<master server>/ubuntu/latest/dists/trusty/InRelease...
gpgv: Signature made Wed 17 May 2017 12:07:08 PM GMT using RSA key ID 286E910B
gpgv: Good signature from "<signature>"
Downloading & parsing package files...
Downloading http://<master server>/ubuntu/latest/dists/trusty/multiverse/binary-i386/Packages.bz2...
ERROR: unable to update: no candidates for http://<master server>/ubuntu/latest/dists/trusty/multiverse/debian-installer/binary-i386/Packages found
# 
```

## Possible Implementation
Create the debian-installer even do it it empty.

## Your Environment
```
# aptly publish list | grep latest\/trusty\ 
  * latest/trusty [amd64, i386] 
{
    main: [trusty-main-snapshot-2017-05-25]:
    Snapshot from mirror [trusty-main-mirror]:
    http://mirrors.mit.edu/ubuntu/ trusty [udeb]
}, 
{
    multiverse: [trusty-multiverse-snapshot-2017-05-25]:
    Snapshot from mirror [trusty-multiverse-mirror]:
    http://mirrors.mit.edu/ubuntu/ trusty [udeb]
}, 
{
    restricted: [trusty-restricted-snapshot-2017-05-25]:
    Snapshot from mirror [trusty-restricted-mirror]:
    http://mirrors.mit.edu/ubuntu/ trusty [udeb]
}, 
{
    universe: [trusty-universe-snapshot-2017-05-25]:
    Snapshot from mirror [trusty-universe-mirror]:
    http://mirrors.mit.edu/ubuntu/ trusty [udeb]
}
root@tst-ubuntu-repo01:~# 
```

**Comment by rethink-neil** [comment]
What is The Aptly Way to mirror a repository with, for example, a `main/debian-installer` component?

**Comment by smira** [comment]
@rethink-neil you need to enable with flag `-with-udebs` (https://www.aptly.info/doc/aptly/mirror/create/)

**Comment by vicarious-opensource** [comment]
What is the status on this ticket? I have a production aptly mirror trying to pull from a staging aptly mirror and this is causing issues. I can create an empty debian-install directory but I'd prefer not to have to automate this every time I switch snapshots in production.

**Comment by zwyang47** [comment]
Is this being added/fixed?
