### ISSUE TITLE
Extra output when using -passphrase option

### ISSUE THREAD

**Issue by debaillie** [aptly-dev/aptly#611]
## Detailed Description

When running
```bash
aptly publish repo -passphrase=asdflkjasdf repo url
```
We still see the output asking for the passphrase:
```
You need a passphrase to unlock the secret key for
user: "User Joe <user.joe@example.com>"
4096-bit RSA key, ID ABCDEF01, created 2017-01-01 (main key ID 01ABCDEF)
```

## Context

I've built some scripts around aptly to fit my needs and I'd like to remove the extraneous output.

## Your Environment

Found on Ubuntu 16.04 server, using aptly version 1.0.1 via the ppa.

**Comment by smira** [comment]
This output is generated by `gpg` utility, not by aptly itself. I think we can try to keep it quiet via flags, but this is backwards-incompatible change.
