### ISSUE TITLE
Snapshot is not renamed in merged snapshot sources

### ISSUE THREAD

**Issue by laurvas** [aptly-dev/aptly#616]
Aptly is smart enough to rename a snapshot in every place it is mentioned. Unfortunately there is at least one place where an old name is kept. It is the source of merged snapshot.

## Detailed Description

Here is a simple example to reproduce the issue.
Create two sources for merging:
```
$ aptly mirror create -architectures=amd64 -filter=dpkg m1 \
http://deb.debian.org/debian jessie main
$ aptly mirror create -architectures=amd64 -filter=dpkg m2 \
http://deb.debian.org/debian-security jessie/updates main
$ aptly mirror update m1
$ aptly mirror update m2
$ aptly snapshot create s1 from mirror m1
$ aptly snapshot create s2 from mirror m2
```

Merge them into `s1+s2` snapshot:
```
$ aptly snapshot merge s1+s2 s1 s2
$ aptly snapshot list
List of snapshots:
 * [s1]: Snapshot from mirror [m1]: http://deb.debian.org/debian/ jessie
 * [s1+s2]: Merged from sources: 's1', 's2'
 * [s2]: Snapshot from mirror [m2]: http://deb.debian.org/debian-security/ jessie/updates
```

Rename `s1` or `s2`:
```
$ aptly snapshot rename s1 snapshot1
```

Note that old name in `s1+s2` description:
```
$ aptly snapshot list
List of snapshots:
 * [s1+s2]: Merged from sources: 's1', 's2'
 * [s2]: Snapshot from mirror [m2]: http://deb.debian.org/debian-security/ jessie/updates
 * [snapshot1]: Snapshot from mirror [m1]: http://deb.debian.org/debian/ jessie

$ aptly snapshot show s1+s2
Name: s1+s2
Created At: 2017-08-12 16:39:50 UTC
Description: Merged from sources: 's1', 's2'
Number of packages: 1
Sources:
  snapshot1 [snapshot]
  s2 [snapshot]
```

## Context
I use simple snapshot naming scheme for mirrors: `<mirror name>_<date in YYYYMMDD format>` like `debian/jessie-security_20170812`. When a new version of my software is released, I rename all snapshots that are used for that release to `<mirror name>_<software version>` like `debian/jessie-security_v4.0` and publish them as a component `<software version>`. This allows me to recreate environment for any release.

## Possible Implementation
Snapshot should be renamed in merged snapshot description.

## Your Environment
Aptly 1.1.1 on Debian Jessie.

**Comment by laurvas** [comment]
I've just noticed the same issue with mirrors: renaming a mirror don't change snapshot description.

Well, is it possible to edit snapshot description by hand?

**Comment by smira** [comment]
No, snapshot is not editable.

I think we could provide command to retrieve snapshot ancestors (with their current names).

**Comment by laurvas** [comment]
I'm sorry, but I can't imagine any cases where such a command will be helpful. I'm worried nobody will use it. And It won't resolve the original problem.

The thing is I get confused with `aptly snapshot list` output when i run it just to ensure everything is correct.

Before renaming:
```
$ aptly snapshot list
List of snapshots:
 * [debian/jessie+security+keyring_20170815-1]: Merged from sources: 'debian/jessie-security_20170815-1', 'debian/jessie_20170815-1', 'my-rep-keyring_20170807'
 * [debian/jessie+security+keyring_20170812-1]: Merged from sources: 'debian/jessie-security_20170812-1', 'debian/jessie_20170812-1', 'my-rep-keyring_20170807'
 * [debian/jessie-security_20170812-1]: Snapshot from mirror [debian/jessie-security]: http://deb.debian.org/debian-security/ jessie/updates [src]
 * [debian/jessie-security_20170815-1]: Snapshot from mirror [debian/jessie-security]: http://deb.debian.org/debian-security/ jessie/updates [src]
 * [debian/jessie_20170812-1]: Snapshot from mirror [debian/jessie]: http://deb.debian.org/debian/ jessie [src]
 * [debian/jessie_20170815-1]: Snapshot from mirror [debian/jessie]: http://deb.debian.org/debian/ jessie [src]
 * [my-rep-keyring_20170807]: Snapshot from local repo [my-rep-keyring]
...16 other snapshots
```
It's cool to see the exact sources of snapshots: mirrors, repos or other snapshots.

After renaming:
```
$ aptly snapshot list
List of snapshots:
 * [debian/jessie+security+keyring_20170815-1]: Merged from sources: 'debian/jessie-security_20170815-1', 'debian/jessie_20170815-1', 'my-rep-keyring_20170807'
 * [debian/jessie+security+keyring_v4.0]: Merged from sources: 'debian/jessie-security_20170812-1', 'debian/jessie_20170812-1', 'my-rep-keyring_20170807'
 * [debian/jessie-security_v4.0]: Snapshot from mirror [debian/jessie-security]: http://deb.debian.org/debian-security/ jessie/updates [src]
 * [debian/jessie-security_20170815-1]: Snapshot from mirror [debian/jessie-security]: http://deb.debian.org/debian-security/ jessie/updates [src]
 * [debian/jessie_v4.0]: Snapshot from mirror [debian/jessie]: http://deb.debian.org/debian/ jessie [src]
 * [debian/jessie_20170815-1]: Snapshot from mirror [debian/jessie]: http://deb.debian.org/debian/ jessie [src]
 * [my-rep-keyring_20170807]: Snapshot from local repo [my-rep-keyring]
...16 other snapshots
```

When I look at this list, I notice that `*_20170812-1` snapshots that don't exist anymore.

If snapshot description always has the same format, maybe it's a good idea to generate it on the fly?

**Comment by smira** [comment]
I understand that it gets confusing if sources are renamed, but this has pros and cons on its own. When using aptly CLI, snapshot description is generated on the fly depending on the way snapshot was generated (snapshot pull command puts more info into description). While using API, snapshot description could be literally anything. By the time we print snapshot description, source might be already removed, so we can't generate description in that case, and frozen string description is better than generating on the fly. So there are pros and cons for both approaches. 

That's why I said we might be printing current ancestor names, but I don't want to generate description on the fly always.

**Comment by laurvas** [comment]
Thank you for the answer. I found an easy workaround: merge renamed source snapshots into new snapshot and switch corresponding published repository.

**Comment by smira** [comment]
So I'll add an option to print current name of ancestors for `snapshot show`/`snapshot list`
