### ISSUE TITLE
Internal GPG provider doesn't find key

### ISSUE THREAD

**Issue by quulah** [aptly-dev/aptly#628]
## Detailed Description
I updated from 1.0.1 to 1.1.1 and tried the new internal openpgp provider for signing. It says:

```
ERROR: unable to initialize GPG signer: couldn't find key for key reference <ID>
```

I can see the key in `gpg --list-keys` and `gpg --list-secret-keys`.

Using the gpg provider works the same way it did in 1.0.1.

## Context
I'd like to change to GPG2, and this seemed like the way.  I tried with the old GPG1 key first.

## Possible Implementation
The error comes from [here](https://github.com/smira/aptly/blob/master/pgp/internal.go#L147), so the signer is nil. Didn't read the code too far, but this [line](https://github.com/smira/aptly/blob/master/pgp/internal.go#L128) uses `signer.PrimaryKeyId`. The key I have used is a subkey, is that a problem?

**Comment by smira** [comment]
yep, I think we should match on subkey ids as well
