### ISSUE TITLE
ERROR: unable to update: download errors: unexpected EOF

### ISSUE THREAD

**Issue by jjblack** [aptly-dev/aptly#631]
## Detailed Description
I am trying to make an aptly server mirror another local aptly server. The `aptly mirror update` downloads all the packages but errors at the end with `unexpected EOF` on different packages every time. Below is the mirror and what happens when I update it:
<pre>
 # aptly mirror show main
Name: main
Archive Root URL: https://<aptly-server>.<domain>.com/
Distribution: xenial
Components: staging
Architectures: amd64
Download Sources: no
Download .udebs: no
Last update: never

Information from release file:
Architectures: amd64
Codename: xenial
Components: main staging
Date: Mon, 4 Sep 2017 06:08:41 UTC
Description:  Generated by aptly

Label: . xenial
Origin: . xenial
Suite: xenial

# aptly mirror update main
...
ERROR: unable to update: download errors:
  https://<aptly-server>.<domain>.com/pool/staging/s/snapcraft/snapcraft_2.33_all.deb: unexpected EOF
  https://<aptly-server>.<domain>.com/pool/staging/k/kodi-pvr-nextpvr/kodi-pvr-nextpvr_1.10.8+git20150724-2_amd64.deb: unexpected EOF
</pre>

The packages reported are different each time and there is always two.
 
Aptly downloads all the packages and then reports the errors. But I see from #26 that this is expected. But here aptly doesn't link the packages so I have to `aptly db cleanup` to delete all the downloaded packages before I update again or else my storage space will fill up.

#538 also describes what is happening here. But I have already disabled and removed the cron job that updates the mirrors.

If I try to ignore it take a snapshot of the mirror, then I get:
<pre>
# aptly snapshot create snap-main from mirror main
ERROR: unable to create snapshot: mirror not updated
</pre>
But I expect this to happen.

## Context
I have successfully created an aptly server that mirrors the upstream (archive.ubuntu.com) mirrors and all clients can successfully pull those packages with apt. Now I want to set up an aptly server on the development network so I can test custom packages and repos with Aptly while still allowing all clients to download from the production server. I am trying to have the development server pull the packages from the production server to minimize updating time as the development server will likely be recreated (and therefor packages re-downloaded) multiple times.

The production Aptly server has two components. The `staging` component is updated weekly. The `main` component is updated one week later. I have a script that renames the staging snapshot to main, updates the staging mirrors, updates the staging snapshot and published both snapshots as multi-components. Critical servers pull only from the delayed, main component, this protects them from broken packages published upstream. Although I doubt this is the cause of my issue.

## Your Environment
Both servers are physical boxes with:
OS: Ubuntu 16.04
Aptly version: 1.1.1

**Comment by de1ayer** [comment]
Hi, I've faced same issue with aptly 1.4.0 on Debian Stretch.
My workaround is to change https:// scheme to http:// (via mirror drop / mirror create).
