### ISSUE TITLE
Partial mirror

### ISSUE THREAD

**Issue by ktosiek** [aptly-dev/aptly#64]
I'd like to create mirrors that only download a specified set of packages (+dependencies).
This would be pretty handy, as I need some packages from Ubuntu's "universe" (which is ~40GB for saucy) but I don't want to download the whole thing.

Is something like that on the roadmap? (I hope that's what "Filter repository*" on the main site is about)

**Comment by bersace** [comment]
@smira How do you mirror *some* packages ? `package0|package1` seems not to work. aptly 0.9.7 (debian stretch).

**Comment by rtennill** [comment]
What command line or `-filter `spec are you using to create the partial mirror?

**Comment by bersace** [comment]
> What command line or -filterspec are you using to create the partial mirror?

What `-filter` spec, i guess.

**Comment by smira** [comment]
It works just fine:

```
$ aptly mirror create -architectures=i386 -filter 'coreutils|dnsutils' stretch2 http://mirror.yandex.ru/debian/ stretch main
$ aptly mirror update stretch2
...
Applying filter...
Packages filtered: 50908 -> 3.
```

**Comment by bersace** [comment]
@smira you're right. The package was missing. Sorry for the noise and thanks for the point.
