### ISSUE TITLE
Error #01: file missing [file=MANIFEST-000000]

### ISSUE THREAD

**Issue by chnyda** [aptly-dev/aptly#654]
## Detailed Description
At least once a week, I have to face the following error: `Error #01: file missing [file=MANIFEST-000000]`

It is fixed by running `aptly db recover` but it would be good to not have to run that command so often.

The error is all the time the same : the same file is missing, always **MANIFEST-000000**.

## Your Environment

- aptly 1.1.1
- running inside a container (Docker Swarm)
- the container is still running
- aptly files are in glusterfs

**Comment by smira** [comment]
This seems to be failure coming from `goleveldb`, there should be `LOG` file inside db/ directory. I don't have much to say except if you can find some traces why MANIFEST is missing from the goleveldb log.

**Comment by chnyda** [comment]
Hi @smira , I have created an issue for goleveldb : https://github.com/syndtr/goleveldb/issues/180

Updating levbeldb  or adding https://github.com/syndtr/goleveldb/commit/69e19a4743fd46eff0dc32c368d8b11b8adac35c might solve the problem. Do you plan to add that fix?

**Comment by smira** [comment]
I don't think I understand how syndtr/goleveldb@69e19a4 might fix the issue you described, but I'll get new version of goleveldb for sure.

**Comment by smira** [comment]
Pushed PR #665 for that update

**Comment by smira** [comment]
@chnyda nightly build `aptly_1.1.1+42+gafd2c5f` contains the goleveldb fix

**Comment by mevatron** [comment]
@smira I've run into this problem recently. I think my issue is I have the database mounted on different network paths on different systems, which was corrupting the database. So, for example, System1 had `/mnt/aply/db` and System2 had `/media/aptly/db`. 

Is it possible to switch the path of the database and repair the current one or regenerate the database from scratch?

Thanks!

**Comment by mevatron** [comment]
@smira Actually, I found the source of the corruption. I had two different versions trying to access the databases. System1 had version `1.1.1`, but System2 had version `1.2.0`, which each time the `1.2.0` client tried to list the repo contents corrupted the database. Is there an upgrade procedure I need to follow to upgrade the database for `1.2.0+`?

Thanks!

**Comment by smira** [comment]
@mevatron 

First of all, if your shared mount doesn't correctly implement file system locks, aptly might corrupt its database if it's open concurrently from different systems.

`goleveldb` (database) is using filesystem locks to prevent two processing accessing database at the same time.

There's no specific upgrade procedure for 1.1.1 -> 1.2.0.
