### ISSUE TITLE
How to import local debian repos generated by other tools?

### ISSUE THREAD

**Issue by exaos** [aptly-dev/aptly#671]
I have several local pkg repositories: some are mirrored by `debmirror`, some are generated manually. These repos are used in an environment without network. Usually, I just rsync them with a movable disk between boxes with and without network. In the network-less box, the `/etc/apt/sources.list` is like this:

> deb file:<some-path>/debian  stretch main contrib non-free
> deb-src file:<some-path>/debian  stretch main contrib non-free

I want to manage them with aptly.

First, I tried to mirror them into aptly:

> aptly mirror create local-debian  file:<some-path>/debian stretch main contrib non-free

Then, failed with this error:

> ERROR: unable to fetch mirror: file:///dists/stretch/Release: Get file:///dists/stretch/Release: unsupported protocol scheme "file"

Is there any way to merge these repos into aptly? I think, this scenario may be common.

**Comment by smira** [comment]
Depending on the complexity of the repos, there are many ways to handle that.

1. Mirroring. Like you tried above, but you need some http/ftp server (even on localhost) so that aptly can mirror it.

2. Simply adding package files from `pool/` directory directly in aptly local repo (`aptly repo add ../path/..`)

**Comment by exaos** [comment]
Still confused. If I directly add the `pool/` as a local repo, how to easily handle those `Package.gz` files in paths `dists/<distro>/<...>/`?

**Comment by smira** [comment]
Assuming you have single distribution published with single component, aptly will scan all the files in `pool/` directory and add them to the local repo. When repo is published, aptly will automatically generated indexes in `dists/`. If you have something more complicated, the only way is to set up http webserver & mirror each distribution.
