### ISSUE TITLE
Missing source packages in published repository

### ISSUE THREAD

**Issue by mkoval** [aptly-dev/aptly#68]
I've added several Debian source packages (.dsc files) to my Aptly repository with `aptly repo add ...`. The packages show up in `aptly repo show -with-packages=true` with the `_sources` suffix. After verifying their presence, I updated my repository by running `aptly publish update` as usual.

However, the source packages do not seem to be included in the published repository. No `Sources` files were generated. As a result, I get the following error if I add my repository as a `deb-src` line in my `sources.list` file:

```
W: Failed to fetch http://packages.personalrobotics.ri.cmu.edu/dists/precise/Release  
Unable to find expected entry 'main/source/Sources' in Release file (Wrong
sources.list entry or malformed file)
```

Do I need to `aptly publish` my repository with special flags to include source packages? Any suggestions?

**Comment by ww34ww34ww34** [comment]
Very good tool.
But i have the same issue... I had to search a lot to find solution. I think too it would be helpful to note that in the documentation.

**Comment by smira** [comment]
@ww34ww34ww34 do you mind adding that to docs? 

https://github.com/aptly-dev/aptly-dev.github.io/tree/master
