### ISSUE TITLE
Origin not preserved when publishing snapshots

### ISSUE THREAD

**Issue by dibaciu** [aptly-dev/aptly#685]
## Detailed Description

When a snapshot is created/published the Origin: field is not inherited.

This is what a mirror (for debian jessie updates) looks like:
`root@debian:~# aptly mirror show debian-jessie-updates `
`Name: debian-jessie-updates`
`Archive Root URL: http://mirror.switch.ch/ftp/mirror/debian/`
`Distribution: jessie-updates`
`Components: main, contrib, non-free`
`Architectures: amd64`
`Download Sources: no`
`Download .udebs: no`
`Last update: 2017-12-05 10:27:39 EET`
`Number of packages: 109`
`Information from release file:`
`Architectures: amd64 arm64 armel armhf i386 kfreebsd-amd64 kfreebsd-i386 mips mipsel powerpc ppc64el s390x`
`Codename: jessie-updates`
`Components: main contrib non-free`
`Date: Tue, 05 Dec 2017 02:35:59 UTC`
`Description:  Updated packages for Debian 8`
`Label: Debian`
`Origin: Debian`
`Suite: oldstable-updates`
`Valid-Until: Tue, 12 Dec 2017 02:35:59 UTC`

After creating and publishing a snapshot, this is what the Release file contains (note the changed Origin field value:
`Origin: . jessie-updates`
`Label: . jessie-updates`
`Suite: jessie-updates`
`Codename: jessie-updates`
`Date: Tue, 5 Dec 2017 08:29:54 UTC`
`Architectures: amd64`
`Components: main`
`Description: Generated by aptly`

## Context
I'd like to use the same unattended upgrades configuration with aptly as I do when  using apt-mirror. This issue is putting my plans for switching to aptly on hold.

## Possible Implementation
Ideally, the Origin field should be inherited by snapshots, as per documentation (from [https://www.aptly.info/doc/aptly/publish/snapshot/](url):

> -origin="": value for Origin: field. When not set will be inherited by given snapshot(s) if unique

## Your Environment
Debian8, aptly version: 1.1.1

**Comment by smira** [comment]
@dibaciu how snapshot got generated? was it simple snapshot taken directly from the mirror?

If you could share `aptly graph` diagram, that would be perfect. Thanks

**Comment by dibaciu** [comment]
Simple snapshot, directly from the mirror. Graph below:
![graph-685](https://user-images.githubusercontent.com/19711366/33605061-d56d3414-d9c0-11e7-8a2c-1050a95ca2c0.png)

**Comment by smira** [comment]
I checked source code and tests, I don't see why this might happen. 

@dibaciu could you please provide some steps to reproduce the issue?

**Comment by EzraBrooks** [comment]
I am seeing this same problem - both with the `Origin:` field and the `Codename:` field. It is preventing me from using Aptly mirrors during automated installation of Ubuntu Server 20.04.
