### ISSUE TITLE
Call for the maintainer team

### ISSUE THREAD

**Issue by smira** [aptly-dev/aptly#725]
🎉 I think many of you following recent development of aptly have noticed that my activity on the project is significantly lower than it was few years ago, this graph illustrates it:

![image](https://user-images.githubusercontent.com/55211/38213480-fb2f90fa-36c9-11e8-88b4-88c643542e26.png)

There are few things which are leading to it, but major problem is that I'm no longer using aptly myself, and my current focus is far away from Debian package management. 

The worst thing I could have imagined is aptly project going nowhere because of lack of my attention. 😞 At the moment when I write this, there're 141 open isses and 21 open pull requests, which is not sane state for the project. So today I'm certainly a bottleneck for aptly development.

Over those years there were tons of amazing contributions from the community which allows project to move forward. I would like to move this project from single-maintainer model to maintained by the team model. This covers this repository, https://github.com/smira/aptly and https://github.com/aptly-dev organization (which is mostly www.aptly.info website nowadays). 

Today we have pretty good docs on the [development](https://github.com/smira/aptly/blob/master/CONTRIBUTING.md), templates for PRs & issues, automated CICD, etc. I have (never published) automated aptly release management scripts (nightly & stable releases). Thanks to Sébastien Delafond, aptly is included into Debian/Ubuntu as a package. Website (www.aptly.info) is automatically deployed to Amazon S3 with each `master` build, served by Amazon CDN, TLS certificate is provided by Let's Encrypt. aptly own repository (repo.aptly.info) is hosted on Amazon S3.

I looked into recent contributions, reviews and picked several participants which seemed to be best fit for the maintainer role:

* @queeno 
* @sliverc 
* @lebauce 
* @apachelogger 

(Simon, Oliver, Sylvian, Harald please let me know if this makes sense for you)

This list is open, if anyone wants to become aptly maintainer, please post a comment to this issue.

So in the end goal is to build a team of maintainers and move ownership to this team for the GitHub repository and all the infrastructure around it.

There are many steps to convert this project to be maintainer team owned:

- [x] establish maintainer team
- [ ] establish maintainer mailing list
- [x] update website (maintainer team)
- [x] make sure no personal secrets are left in .travis.yml encrypted
- [x] move smira/aptly to aptly-dev/aptly
- [x] update all references to smira/aptly to point to aptly-dev/aptly
- [x] add maintainers to aptly-dev organization
- [x] switch repo.aptly.info PGP signing keys to be maintainer team owned
- [x] figure out bintray ownership
- [x] publish release management scripts

Even going through the first few steps should speed up aptly development.

❤️ Andrey

**Comment by Conan-Kudo** [comment]
It probably makes sense to move `smira/aptly` to `aptly` organization. GitHub will safely redirect everything. Other related dependencies that need to be maintained alongside aptly should probably be moved, too. Then it's just a matter of granting the rights to the GitHub organization.

(I did this recently with a couple of other projects, so I know this pain well...)

**Comment by smira** [comment]
Unfortunately `aptly` organization is not available (it was occupied by someone before I started aptly), so we have `aptly-dev` org. But that makes perfect sense, thanks, to move smira/aptly to aptly-dev/aptly

**Comment by smira** [comment]
@queeno @sliverc @lebauce @apachelogger any word from you on that?

**Comment by sliverc** [comment]
Thanks @smira for raising this. Generally I am interested but I am wondering what your expectations are towards a maintainer?

**Comment by smira** [comment]
@sliverc I would expect more of [C4 contract](https://rfc.zeromq.org/spec:22/C4/) when maintainers have commit rights to the repository and are active in reviewing PRs, approving changes, building future vision for the project.

As we have a team, we would have less work to do for every person hopefully.

My goal would be to enable every maintainer with all the access and tools requires to do the work efficiently (this is mostly around CI/CD and release management, as GitHub will provide the rest).

**Comment by sliverc** [comment]
@smira This sounds good. I have to see how much time I am able to commit but you can count me in. I guess once the others have also commented how they stand in terms of maintainership it would be good to have a discussion on the vision for the project - this will then help working through the issues (I assume potentially a few can be closed as out of scope).

**Comment by apachelogger** [comment]
I'm on board.

**Comment by smira** [comment]
PR to replace S3 creds + it actually makes S3 tests run on Travis: #730

**Comment by sliverc** [comment]
@smira It seems that the only open point on this list is the mailing list. I am totally content with the github team discussion we are currently using. Do you think we can close this issue or is there still anything open?

**Comment by smira** [comment]
yep, agreed. Closing it, one item still missing (small one) is to add automation to publish release .debs to repo.aptly.info, but I'll get it done (pretty easy). And the very last will be to update www.aptly.info links to point to github for downloads, but that will come with the next release.
