### ISSUE TITLE
jessie mirror doen not contain any package after successfull update

### ISSUE THREAD

**Issue by aelyasi** [aptly-dev/aptly#733]
debian jessie mirror create and update successfully, but Number of packages is '0'
root@Repository:~# aptly mirror show jessie-main 
Name: jessie-main
Archive Root URL: http://ftp.ir.debian.org/debian/
Distribution: jessie
Components: main
Architectures: amd64
Download Sources: no
Download .udebs: no
Filter: libjs-hooker_0.2.3-1_all.deb
Filter With Deps: yes
Last update: 2018-04-24 08:33:10 +0430
Number of packages: 0

what's the problem?

**Comment by apachelogger** [comment]
Your filter doesn't match anything as there is no package **named**  `libjs-hooker_0.2.3-1_all.deb`, so 0 packages are being filtered into your mirror. See documentation for how to write a proper package query https://www.aptly.info/doc/aptly/mirror/create/

It would be nice if you could use the mailing list for future question https://groups.google.com/forum/#!forum/aptly-discuss
