### ISSUE TITLE
aptly ignores $TEMPDIR

### ISSUE THREAD

**Issue by markizano** [aptly-dev/aptly#746]
Typically in any application, if you export the `TEMPDIR` variable, it will adhere to this and write files to that directory. Aptly ignores this and will still write to `/tmp` as if the directory is hardcoded in the source.

## Detailed Description
Aptly should listen and adhere to the `$TEMPDIR` variable if set.

## Context
I have a set amount of disk space available to the root partition. I have a mounted `/var/tmp` directory with additional space that I want the program to use when writing temp files.
When publishing a mirror of the Ubuntu repository, I get a failure with an error:

    ERROR: unable to publish: unable to process packages: write /tmp/aptly986440873/universe_binary-i386_Packages: no space left on device

## Possible Implementation
Do a check for `$TEMPDIR` being set, if so, use that, if not, continue to use `/tmp`

**Comment by smira** [comment]
aptly is following standards and it creates temporary files under `TMPDIR` environment variable (https://en.wikipedia.org/wiki/TMPDIR)

**Comment by mesoterra** [comment]
I am having some issues with Aptly not using the TMPDIR system variable when it is exported from a user's .bashrc. It also does not use it within a script when TMPDIR is declared.

```
$ echo 'TMPDIR according to .bashrc' ; grep TMPDIR .bashrc ; echo ; echo 'TMPDIR according to printenv' ; printenv | grep TMPDIR ; echo ; echo 'Echoing $TMDIR'; echo $TMPDIR ; echo ; echo 'Aptly process pulled from ps faux' ; ps faux | grep 'aptly publish' | grep -v grep | sed 's/-gpg-key.*snapshot/REMOVED_FOR_SECURITY/g' | sed 's/^.*\\/\\/g' ; echo ; echo ; du -ax --max-depth 0 /tmp/aptly742967018/ ; echo 'sleeping for 15 seconds' ; sleep 15 ; du -ax --max-depth 0 /tmp/aptly742967018/ ; echo ; echo -n 'Aptly Version: ' ; aptly version

TMPDIR according to .bashrc
export TMPDIR=~/aptly/tmp

TMPDIR according to printenv
TMPDIR=/home/aptly/aptly/tmp

Echoing $TMDIR
/home/aptly/aptly/tmp

Aptly process pulled from ps faux
\_ aptly publish REMOVED_FOR_SECURITY -component=main,multiverse,restricted,universe dev-xenial_main dev-xenial_multiverse dev-xenial_restricted dev-xenial_universe dev


240100  /tmp/aptly742967018/
sleeping for 15 seconds
240320  /tmp/aptly742967018/

Aptly Version: aptly version: 0.9.6
```

The above command output is being generated during the "Generating metadata files and linking package files..." portion of a snapshot publish. You can see that the file size of the /tmp/aptly* directory is increasing, it should not be showing up in /tmp as the only instance of aptly that is running is under the aptly user.

Is there a change I should be making somewhere to get it to pick up the TMPDIR variable?

**Comment by smira** [comment]
aptly should be using https://godoc.org/os#TempDir for any temp files it creates. 

I'm not sure if your process is launched from the same environment as the script which prints the info

**Comment by mesoterra** [comment]
The script was run from the same environment that the process is running from.

Is there  any more information I can provide to you?

**Comment by Danethz** [comment]
Same thing here.
Debian 11, Aptly 1.5.0
Trying to publish snapshot from user "aptly" which has in .basrc `TMPDIR=/var/aptly/tmp`
And have error:
`ERROR: unable to publish: unable to generate contents index: write /tmp/aptly4168691921/Contents-amd64: no space left on device`
