### ISSUE TITLE
Aptly distribution name is corrupted unable to publish drop

### ISSUE THREAD

**Issue by fluidjeel** [aptly-dev/aptly#748]
If we misplace the -force-overwrite or -architecture option during the `aptly publish repo` the repo gets published with a weird name.

`Published repositories:
  * -architectures=amd64,i386,all/pi11-all [amd64] publishes {main: [pi11-all]}
  * -architectures=amd64,i386,all/vcmts-stretch-addons-amd64 [amd64] publishes {main: [vcmts-stretch-addons-amd64]}
  * -force-overwrite/2_6_0-amd64 [all, amd64, i386] publishes {main: [2_6_0-amd64]}
  * -force-overwrite/2_6_0-amd64-new [all, amd64, i386] publishes {main: [2_6_0-amd64-new]}
  * ./2_6_0-all-new [all, amd64, i386] publishes {main: [2_6_0-all-new]}
`   
However, I am unable to drop the repos starting with distribution -force or -architecture as the command gets confused with the option.

`ubuntu@ip-96-112-231-197:~$ aptly publish drop  "-force-overwrite/2_6_0-amd64-new"
flag provided but not defined: -force-overwrite/2_6_0-amd64-new
Usage: aptly publish drop <distribution> [[<endpoint>:]<prefix>]

aptly publish drop - remove published repository

Options:
  -architectures="": list of architectures to consider during (comma-separated), default to all available
  -config="": location of configuration file (default locations are /etc/aptly.conf, ~/.aptly.conf)
  -db-open-attempts=10: number of attempts to open DB if it's locked by other instance
  -dep-follow-all-variants: when processing dependencies, follow a & b if dependency is 'a|b'
  -dep-follow-recommends: when processing dependencies, follow Recommends
  -dep-follow-source: when processing dependencies, follow from binary to Source packages
  -dep-follow-suggests: when processing dependencies, follow Suggests
  -dep-verbose-resolve: when processing dependencies, print detailed logs
  -force-drop: remove published repository even if some files could not be cleaned up
  -gpg-provider="": PGP implementation ("gpg" for external gpg or "internal" for Go internal implementation)
  -skip-cleanup: don't remove unreferenced files in prefix/component
ERROR: unable to parse flags
`

How can I drop those published repos

**Comment by smira** [comment]
You need to put `--` before distribution name so that aptly knows it's not a flag.

In fact you need to put it in reverse order:

```
$ aptly publish drop -- 2_6_0-amd64-new -force-overwrite
```

**Comment by smira** [comment]
@orex same thing,

```
aptly publish drop -- xenial -architectures=
```

(`publish drop` accepts `distribution prefix` while `publish list` prints `prefix distribution`)

**Comment by orex** [comment]
Thank you! It is working.
