### ISSUE TITLE
aptly publish to custom folder and not public

### ISSUE THREAD

**Issue by fluidjeel** [aptly-dev/aptly#749]
I have couple of repos in which some of the packages have same name but have different hashes. I would like the repos to be published under separate endpoints or context

so today i do the following:

```
deb http://myaptserver/public  repo1 main
deb http://myaptserver/public  repo2 main
```

Instead of this is it possible to do this ?

```
deb http://myaptserver/public1  repo1 main
deb http://myaptserver/public2  repo2 main
```

Kindly let me know if this is feasible

**Comment by apachelogger** [comment]
Sure. For the future it would be super if you could ask questions on the mailing list or on IRC though.

```
➜ aptly publish repo help
Usage: aptly publish repo <name> [[<endpoint>:]<prefix>]
```

The `prefix` argument and defines the prefix you publish under. So you publish one in `public1` and another repo in `public2`.

Also see the full help output on your system as well as the `FILESYSTEM PUBLISHING ENDPOINTS` and `PUBLISH LOCAL REPOSITORY` sections of the aptly manpage.
