### ISSUE TITLE
Dependency Resolution fails if dependencies are from different mirror

### ISSUE THREAD

**Issue by abh23** [aptly-dev/aptly#752]
## Detailed Description

I have created 2 mirrors, trusty-main, and trusty-updates with following commands: 

`aptly mirror create -architectures=amd64 -filter='Priority (required) | Priority (important) | Priority (standard)' trusty-main http://in.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse`

`aptly mirror create -architectures=amd64 -filter='Priority (required) | Priority (important) | Priority (standard) |apache2|bind9|bind9utils|bind9-doc|vim|apparmor-utils|python-pip|python-dev|python2.7-dev' -filter-with-deps trusty-updates http://in.archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse`

After following the usual procedure of creating snapshots from both these mirrors, merging those snapshots with `-latest` or `-no-remove` (tried both options) and publishing the snapshot, I am getting dependencies issues on the client machine. 

Upon investigation, I found that few of the dependencies for installing **python-dev, python2.7-dev** are available only on **trusty-main** repo (_http://in.archive.ubuntu.com_) which obviously aren't available in the mirror **trusty-main** that I created as explained above since I didn't use `-filter-with-deps` option. 

How to handle this kind of situation effectively? 

## Context

It is important from the overall dependency resolution procedure. If a package depends on the specific library from a different mirror, it should be resolved automatically. APT already does that the same. 

## Possible Implementation

Few ideas that I have at this point and I am still trying them out. So, I am listing them below: 

1. Create mirrors with same filters from all the related global mirrors. Like in my case, the same filter can be used for both the `aptly mirror create` commands. Once done, their snapshot can be merged to another snapshot with `-latest/-no-remove`. BUT, this approach needs more space on the disk and also doesn't address dependency resolution effectively as there might a case where pkg-a from mirror-A depends on pkg-B from mirror-B which in turn depends on pkg-c from mirror-A again. So, this approach may fail eventually.

2. Create complete mirrors/snapshot from all the related global mirrors. Once done, a snapshot with required` -filter` and `aptly snapshot pull `command can be created which will fetch all the dependencies along with the pull command. 
Problem with this approach is that it requires huge disk space. 

## Your Environment
Ubuntu 14.04 VM with basic packages. 
aptly version: 1.3.0

**Comment by smira** [comment]
I don't think there's any good solution for this, as certainly dependencies might be different in different distributions. Mirror filtering helps to use less space/bandwith, but dependency issues with complex distributions like main Ubuntu/Debian is hard. I can only propose to try "negative" filtering, like filtering out packages you don't need (e.g. by priority or section).

**Comment by abh23** [comment]
Thanks. I ended filtering the required packages along with their dependencies from both the mirrors (trusty and trusty-updates). After that, I create a snapshot where I merge (with `-no-remove`) from snapshots of the respective mirror. Once done, I fetch the latest version of the package along with version required in an empty snapshot and all the required packages are being fetched as well.
