### ISSUE TITLE
apt-file on debian stretch still won't work with aptly repository

### ISSUE THREAD

**Issue by andsten** [aptly-dev/aptly#756]
On debian _stretch_ I observe that `apt-file udpate` (which on _stretch_
just calls `apt update`) does not download the `Contents-<arch>` index files at all
in case of using an aptly-created mirror. When using an official debian
mirror, it immediately works just fine.

## Detailed Description
(I reviewed the already fixed bug report #667 and that seems not to be the same issue as described here.)

I was able to confirm that those `Contents` files indeed exist in my published
snapshot of a debian mirror and are also listed in the `Release` / `InRelease` files
with correct hashes. However when I compared the `InRelease` file of an official
debian mirror with the one of my aptly mirror, I recognized this difference:

my published aptly mirror:
```
78156fa4c3dc2d9738baeeb4910d6dc4    31931 main/Contents-amd64.gz
```

official mirror:
```
 71ffc92735ac8621dc4bface380b8311 455005144 main/Contents-amd64
 000fc46f21ad2c46d1affa5f8e829527 31399649 main/Contents-amd64.gz
```

So the official mirror also lists the hash of the uncompressed `Contents` file,
but the aptly mirror does not. On both the official mirror and my aptly mirror,
the actual uncompressed file `Contents-amd64` does not exist, just the compressed
`Contents-amd64.gz` exists (as it should be, to my understanding).

For other index files like `Packages`, the file `InRelease` of my aptly mirror
contains both hashes for compressed and uncompressed file, just for `Contents`
files it is different. Why? Might this be the problem? Or did I misinterpret
stuff?

The [debian wiki](https://wiki.debian.org/DebianRepository/Format) says about that:

  _"The checksum and sizes shall match the actual existing files. If indexes are
  compressed, checksum data must be provided for uncompressed files as well, even
  if not present on the server."_

On debian _jessie_ I do not get problems like that. There `apt-file update` was
implemented differently (not using `apt update` in behind... one can easily
see this because on jessie it shows progress output of `curl`, and on _stretch_
the output looks completely different).

## Your Environment
I am using `aptly 1.3.0` (and also tried the latest nightly build `1.3.0+17+g9a704de` with the same result).

**Comment by smira** [comment]
@andsten thanks for detailed report! 

that's certainly bug in aptly, I'll try to fix it for the next release

**Comment by smira** [comment]
Thanks for detailed bug report! 🙇

**Comment by smira** [comment]
bugfix should be available in the next nightly build (in 15-30 minutes)
