### ISSUE TITLE
deb-src

### ISSUE THREAD

**Issue by dmitrievav** [aptly-dev/aptly#77]
Hello

I want to use source packages in my repo, so I do:

<code>
aptly repo add myrepo mypacket_2.36.27.dsc
Loading packages...
[+] mypacket_2.36.27_source added
</code>

And then 

<code>aptly publish repo myrepo myrepo/debian</code>

But when I try to make "apt-get update", I get the follow error 

<code>Failed to fetch http://mydomain/myrepo/debian/dists/wheezy/Release  Unable to find expected entry 'myrepo/source/Sources' in Release file (Wrong sources.list entry or malformed file)</code>

What do I do wrong ?

**Comment by jocama** [comment]
Hi @smira,

I'm having the same issue mentioned by @dmitrievav. The entry in my sources.list file is:
`deb-src http://myhost:9001/qemu-src/ xenial main`

I'm running aptly 0.9.6 on Xenial (Ubuntu 16.04.3)

It appears that there is indeed no source/Sources file. For example, http://us.archive.ubuntu.com/ubuntu/dists/xenial/main/source/ includes a Sources.xz and Sources.gz file, but if I look at ~/.aptly/public/dists/qemu-src/dists/xenial/main, there is no source directory, not to mention the sources files. 

To create the repository, I used aptly mirror create -filter="qemu" -with-sources qemu-src http://archive.ubuntu.com/ xenial main

I think I can work around this by just taking the entries I need from the earlier mentioned, but a fix would be appreciated. 

Cheers.

**Comment by smira** [comment]
@jocama I wonder what goes wrong here, as aptly is supposed to "guess" architecture list from the source of publishing (in your case, snapshot). aptly doesn't update this list after publishing for the first time (so if snapshot doesn't contain "source" packages at the time it is published, "source" won't be published later on if such packages are included).

**Comment by KevinFumbles** [comment]
I also just realized you can’t edit a mirror and `publish switch` after updating - it seems like you have to do a full `publish snapshot` for the source/Sources to exist. Just confirmed, you need to drop the publish (and possibly the snapshots too) and re-publish for it to show up.
