### ISSUE TITLE
Question: mirror that contains a homemade package and all its dependencies

### ISSUE THREAD

**Issue by elboulangero** [aptly-dev/aptly#770]
Hi,

I would like to create a repository that contains a package and all its dependencies. Following the tutorials, I know I could do something like that:

    aptly mirror create -filter="nginx" -filter-with-deps ...

That works if the package is already in the archive I want to mirror. However, what if the package is a package that I build myself? More precisely, it's a metapackage that depends on all the packages I need for a project.

I've been playing a bit with the various primitives of aptly, ie. `mirror`, `repo` and `snapshot`, but I couldn't find a way to do that.

There's a way I can imagine, though I didn't try.

1. Mirror an entire Debian archive, then snapshot it.
2. Create a repo from this snapshot, and add my metapackage.
3. Create an empty repo, then pull my metapackage with deps.
4. I get what I want! A mirror with only my metapackage and its dependencies.

The issue with that method is step 1: I don't want to mirror a complete Debian archive...

**Comment by smira** [comment]
I think what you provided is the only possible way. You can still trim down Debian archive by inverse filtering on `Priority`/`Section` for example. Or you can specify your metapackage dependencies as `-filter` to the mirror, but probably that is not the easiest path.

**Comment by elboulangero** [comment]
> I think what you provided is the only possible way. You can still trim down Debian archive by inverse filtering on Priority/Section for example.

I've thought about that, but my metapackage is for a desktop environment, so it brings in a very diverse crowd of packages. Still... I could compare the sections present in my set of packages, and the sections available in Debian, and come up with a list of sections to blacklist. Maybe that would give me a reasonable mirror (in term of size).

> Or you can specify your metapackage dependencies as -filter to the mirror, but probably that is not the easiest path.

I'm also trying that, but it's more difficult than it seems. I managed to write a hacky bash script for that, but it's a very clumsy approach.

Thanks for the answer, I'm closing that thread.

And thanks for aptly and the great doc and tutorials BTW! Getting started with it is actually quite easy and pleasant :)
