### ISSUE TITLE
Internal GPG provider fails on Ubuntu Cloud repos

### ISSUE THREAD

**Issue by Grimm75** [aptly-dev/aptly#773]
## Detailed Description
When trying to update mirror 'deb http://ubuntu-cloud.archive.canonical.com/ubuntu/ xenial-updates/pike main' using internel gpg provider, aptly fails with:

`
$ /usr/bin/aptly mirror update pike-xenial
Downloading http://ubuntu-cloud.archive.canonical.com/ubuntu/dists/xenial-updates/pike/InRelease...
Downloading http://ubuntu-cloud.archive.canonical.com/ubuntu/dists/xenial-updates/pike/Release...
Downloading http://ubuntu-cloud.archive.canonical.com/ubuntu/dists/xenial-updates/pike/Release.gpg...
ERROR: unable to update: failed to verify detached signature: EOF
`

after switching to external gpg provider, everything works fine.

## Context
Problem is 100% reproducible and affects all repos on ubuntu-cloud.
Their gpg pubkey can be found here: http://keyserver.ubuntu.com/pks/lookup?search=0x5EDB1B62EC4926EA&op=vindex

## Your Environment
aptly 1.3.0 @ Debian Stretch

**Comment by smira** [comment]
Looks like detached signature is not in armor format, we don't support it yet.

**Comment by smira** [comment]
Should be fixed starting with nightly build `aptly_1.3.0+40+gec57d17`

**Comment by furlongm** [comment]
That nightly build doesn't exist when using `deb http://repo.aptly.info/ nightly main`. Is it available elsewhere?
