### ISSUE TITLE
Aptly GPG Key (ED75B5A4483DA07C) not available on sks-keyservers.net

### ISSUE THREAD

**Issue by JonasGroeger** [aptly-dev/aptly#775]
Hey!

I'm running https://travis-ci.org/JonasGroeger/jetbrains-ppa/ and my pipeline recently failed with the following:

```
$ sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED75B5A4483DA07C
Executing: /tmp/tmp.rAIROx9oyS/gpg.1.sh --keyserver pool.sks-keyservers.net --recv-keys ED75B5A4483DA07C
gpg: requesting key 483DA07C from hkp server pool.sks-keyservers.net
gpgkeys: key ED75B5A4483DA07C can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

Was the key pulled from there or is that just a problem with the Keyserver?

URL: http://pool.sks-keyservers.net/pks/lookup?search=ED75B5A4483DA07C

![image](https://user-images.githubusercontent.com/1790638/45518176-f22d9200-b7b0-11e8-971c-26ec5dac4c8a.png)

**Comment by smira** [comment]
I think something is going on with this server, I submitted this key via gpg and via their web interface, but key still seems to be "not found".

**Comment by smira** [comment]
Probably it takes some time for the pool to converge, I will take a look later on

**Comment by JonasGroeger** [comment]
I just found out that http://eu.pool.sks-keyservers.net/pks/lookup?op=get&search=0xED75B5A4483DA07C works. You get that by searching for `0x ED75B5A4483DA07C` instead of just `ED75B5A4483DA07C `. 

```
 docker run -it ubuntu:latest
root@59da23fdef7d:/# apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED75B5A4483DA07C
Executing: /tmp/tmp.9SZQXBp4f5/gpg.1.sh --keyserver
pool.sks-keyservers.net
--recv-keys
ED75B5A4483DA07C
gpg: requesting key 483DA07C from hkp server pool.sks-keyservers.net
gpg: key 483DA07C: public key "Andrey Smirnov <me@smira.ru>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
root@59da23fdef7d:/#
```
A quick test in a docker container worked again.

**Comment by JonasGroeger** [comment]
Works again. Interesting. Seems it was a small hickup. Weird, since I had never issues with the pool.
