### ISSUE TITLE
Using an aptly published mirror to install a new system with debian-installer

### ISSUE THREAD

**Issue by pfelecan** [aptly-dev/aptly#781]
## Detailed Description

I'm trying to use an aptly published mirror to install a new system with a Debian installer, in my case debian-testing-amd64-netinst.iso.

When prompted for a mirror, I choose the local mirror obtained by publishing a snapshot.
Given that the packages are now signed with my key, the installer fails with a message about being unable to verify the signature of the mirror's metadata.

How can I add my public key to the installer in order to being able to use packages from such a mirror when installing a new system with the Debian installer?

**Comment by pfelecan** [comment]
Thank you for your answer.
When I'm in a hurry I can use 2 which, by the way, is what happens when, after selecting a mirror published by aptly, the installation give a message about not being able to verify the signature and, if you ignore the error, it proceeds as is the debian-installer/allow_unauthenticated was set to true.
Otherwise, the third solution is what I use when doing a netinst.

**Comment by pfelecan** [comment]
I reopen this because the 3rd solution doesn't work: when the verification if `InRelease` is done, the error signaling that there no public key available appears even though the file is present in `/usr/share/keyrings`.

**Comment by rhopfer** [comment]
Make sure /usr/share/keyrings/archive.gpg is a keyring, not just a public key.

**Comment by rhopfer** [comment]
Please note, that `trustedkeys.gpg` was just the name I used for the keyring and has nothing to do with a file possible located in `~/.gnupg`.
Also in my solution I fetch the keyring to `/usr/share/keyrings/archive.gpg` on the installer file system, not on the target.

**Comment by pfelecan** [comment]
You're right for the destination directory; I corrected my comment.
In conclusion, we must put the public part of the key used to sign the published snapshot in the above mentioned directory during the early preseeding.

**Comment by pfelecan** [comment]
Having installed another system, I remarked the following subtlety: Installing the public keyring in the installer's `/usr/share/keyrings` as `archive.gpg` copies the keyring over the symbolic link pointing toward `/usr/share/keyrings/debian-archive.gpg`; but that doesn't solve the issue because when the `preseed/early-command` is executed, the target partition is not yet created. However, the installer complains about the non availability of the relevant key for the packages to be installed and, after investigation, it seems that it looks for the keyring in the target partition. The only solution that I found to circumvent this issue is to copy the `>usr/share/keyrings/archive.gpg` to `/target/etc/apt/trusted.gpg.d` and answer *retry* to the installer's question.

**Comment by jirib** [comment]
> Having installed another system, I remarked the following subtlety: Installing the public keyring in the installer's `/usr/share/keyrings` as `archive.gpg` copies the keyring over the symbolic link pointing toward `/usr/share/keyrings/debian-archive.gpg`; but that doesn't solve the issue because when the `preseed/early-command` is executed, the target partition is not yet created. However, the installer complains about the non availability of the relevant key for the packages to be installed and, after investigation, it seems that it looks for the keyring in the target partition. The only solution that I found to circumvent this issue is to copy the `/usr/share/keyrings/archive.gpg` to `/target/etc/apt/trusted.gpg.d` and answer _retry_ to the installer's question.

Any final solution?

**Comment by petrmalkov** [comment]
solution:
copy your signing pub key into iso pool/extras/packages/domain.gpg.key
escape using '@' in filename, it fails on copying

```
        d-i partman/early_command string apt-install gnupg ; \
          echo -e "cp /cdrom/pool/extras/packages/domain.gpg.key /target/tmp/domain.gpg.key\nchroot /target /bin/bash /bin/a
pt-key add /tmp/domain.gpg.key" > /usr/lib/apt-setup/generators/001add-key ; \
          chmod +x /usr/lib/apt-setup/generators/001add-key
```

what's going on:
partman/early_command is used instead of preseed/early_command  - it is a step when all is prepared in memory and /target is going to be done
/usr/lib/apt-setup/generators/001add-key is loading into memory and it will be executed on the stage of apt-setup just before packets installation

**Comment by RolandKaechele** [comment]
I have found a very simple solution for adding an aptly key to debian-installer for bullseye


**Needed files**
[https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/current/amd64/iso-cd/firmware-11.2.0-amd64-netinst.iso](url)
or 
[https://cdimage.debian.org/cdimage/release/11.2.0/amd64/iso-cd/debian-11.2.0-amd64-netinst.iso](url)

[http://ftp.hosteurope.de/pub/linux/debian/indices/override.bullseye.main.gz](url)

**Create aptly-keys deb file**
```
mkdir aptly-keys/aptly-keys-2022.1.0_all/{DEBIAN,etc/apt/trusted.gpg.d}
cat >> aptly-keys/aptly-keys-2022.1.0_all/DEBIAN/control << EOF
Package: aptly-keyring
Version: 2022.1.0
Architecture: all
Maintainer: Automatic Signing Key <ftp-master@example.org>
Section: misc
Priority: important
Multi-Arch: foreign
Essential: yes
Description: GnuPG archive keys for aptly
EOF
 ```
The field "Essential: yes" is important. It causes the debian-installer to install this deb before software will be installed from the aptly repository.

Extract the public key to aptly-keys/aptly-keys-2022.1.0_all/etc/trusted.gpg.d and generate the deb file with
```
cd aptly-keys; dpkg-deb --build aptly-keys-2022.1.0_all; cd..
```


**Modify debian-installer iso**
You can use the official debian-installer image or the unofficial debian-installer image with firmware (which I have used). 

```
mkdir net-inst-image

dd if=firmware-11.2.0-amd64-netinst.iso bs=1 count=432 of=isohdpfx.bin
xorriso -osirrox on -indev firmware-11.2.0-amd64-netinst.iso -extract / net-inst-image/

chmod +w -R net-inst-image/

mkdir net-inst-image/pool/main/a/aptly-keys
cp ./aptly-keys/aptly-keys-2022.1.0_all.deb net-inst-image/pool/main/a/aptly-keys/

```

**Regenerate package archive**
```
mkdir indices
gunzip override.bullseye.main.gz
cp override.bullseye.main indices/
```
```
cat >> config-deb << EOF
Dir {
 ArchiveDir "net-inst-image";
 OverrideDir "indices";
 CacheDir "indices";
};

TreeDefault {
 Directory "pool/";
};

BinDirectory "pool/main" {
 Packages "dists/bullseye/main/binary-amd64/Packages";
 BinOverride "override.bullseye.main";
 #ExtraOverride "override.extra";
};

Default {
 Packages {
  Extensions ".deb";
 };
};
EOF
```
```
apt-ftparchive generate config-deb

sed -i '/MD5Sum:/,$d' net-inst-image/dists/bullseye/Release 
apt-ftparchive release net-inst-image/dists/bullseye >> net-inst-image/dists/bullseye/Release
rm net-inst-image/dists/bullseye/main/binary-amd64/Packages

cd net-inst-image; md5sum `find ! -name "md5sum.txt" ! -path "./isolinux/*" -follow -type f` > md5sum.txt; cd ..

chmod -w -R net-inst-image/
```

**Repack iso image**
```
cp net-inst-image/.disk/mkisofs mkisofs.sh
chmod 775 mkisofs.sh
```
Adapt mkisofs.sh and remove the jigdo entities and some paths
```
xorriso -as mkisofs \
 -r -V 'Debian 11.2.0 amd64 n' \
 -o ./firmware-11.2.0-amd64-netinst-modified.iso \
 -J -J -joliet-long -cache-inodes \
 -isohybrid-mbr isohdpfx.bin \
 -b isolinux/isolinux.bin \
 -c isolinux/boot.cat \
 -boot-load-size 4 -boot-info-table -no-emul-boot \
 -eltorito-alt-boot \
 -e boot/grub/efi.img \
 -no-emul-boot -isohybrid-gpt-basdat -isohybrid-apm-hfsplus \
 net-inst-image
```
```
./mkisofs.sh
```

**Comment by hxlhxl** [comment]
> my goal was to make my own ISO with new packs and key solution: copy your signing pub key into iso pool/extras/packages/domain.gpg.key escape using '@' in filename, it fails on script running
> 
> ```
> d-i partman/early_command string apt-install gnupg ; \
>   echo -e "cp /cdrom/pool/extras/packages/domain.gpg.key /target/tmp/domain.gpg.key\nchroot /target /bin/bash /bin/apt-key add /tmp/domain.gpg.key" > /usr/lib/apt-setup/generators/001add-key ; \
>   chmod +x /usr/lib/apt-setup/generators/001add-key
> ```
> 
> what's going on: 'partman/early_command' is used instead of 'preseed/early_command' - it is a step when all is prepared in memory and /target is going to be done /usr/lib/apt-setup/generators/001add-key is loading into memory and it will be executed on the stage of apt-setup just before packets installation

you saved my day! I slightly modified the commands because apt-key require gpg but not avaiable .here is my preseed

```
d-i partman/early_command string \
  apt-install gnupg ; \
  echo -e "cp /usr/share/keyrings/mykeyring.gpg /target/tmp/mykeyring.gpg\nchroot /target /bin/bash -c '/bin/cp /tmp/mykeyring.gpg /etc/apt/trusted.gpg.d/'" > /usr/lib/apt-setup/generators/001add-key ; \
  chmod +x /usr/lib/apt-setup/generators/001add-key
```

**Comment by bmeyer71** [comment]
@petrmalkov @hxlhxl that helped me perfectly. I did modify a bit since I wanted to pull the gpg key down from a local server instead of modifying the ISO further.
I ended up with this:
```
d-i preseed/early_command string wget -O /tmp/apt_patching_pub.gpg http://repo.home.arpa/keys/apt_patching_pub.gpg
```
```
d-i partman/early_command string echo -e "cp /tmp/apt_patching_pub.gpg /target/tmp/apt_patching_pub.gpg\nchroot /target /bin/bash -c '/bin/cp /tmp/apt_patching_pub.gpg /etc/apt/trusted.gpg.d/'" > /usr/lib/apt-setup/generators/001add-key ; \
chmod +x /usr/lib/apt-setup/generators/001add-key
```

**Comment by neolynx** [comment]
thanks for sharing !

**Comment by bmeyer71** [comment]
I've used what @hxlhxl and @petrmalkov have provided and set things up this way since I didn't want to update the ISO further and made it a bit more flexible for my use.

I download the gpg key and then copy it to the target using:
```
d-i preseed/early_command string wget -O /tmp/apt_patching_pub.gpg http://repo.home.arpa/keys/apt_patching_pub.gpg; \
echo -e "cp /tmp/apt_patching_pub.gpg /target/tmp/apt_patching_pub.gpg\nchroot /target /bin/bash -c '/bin/cp /tmp/apt_patching_pub.gpg /etc/apt/trusted.gpg.d/'" > /usr/lib/apt-setup/generators/001add-key; \
chmod +x /usr/lib/apt-setup/generators/001add-key
```

This seems to be working well so far.
