### ISSUE TITLE
Aptly panic - gpg issue on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by nivi2lon** [aptly-dev/aptly#782]
Aptly panic on ubuntu 16.04 - gpg issue. Aptly version used:1.3.0

## Detailed Description
nextbot@otcpl-manager:~$ aptly publish update unstable
panic: Couldn't find a suitable gpg executable. Make sure gnupg1 is available as either gpg or gpg1 in $PATH [recovered]
        panic: Couldn't find a suitable gpg executable. Make sure gnupg1 is available as either gpg or gpg1 in $PATH

goroutine 1 [running]:
github.com/aptly-dev/aptly/cmd.Run.func1(0xc42030bf50)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/run.go:17 +0x131
panic(0xbe4aa0, 0xc42020a1c0)
        /usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/aptly-dev/aptly/pgp.NewGpgSigner(0xc4201400c0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/pgp/gnupg.go:121 +0xba
github.com/aptly-dev/aptly/context.(*AptlyContext).GetSigner(0xc4201400c0, 0x0, 0x0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/context/context.go:403 +0xd7
github.com/aptly-dev/aptly/cmd.getSigner(0xc4202ed500, 0xc4202ed500, 0xa, 0x1, 0x0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/publish.go:14 +0x7e
github.com/aptly-dev/aptly/cmd.aptlyPublishUpdate(0xc4202e6ea0, 0xc420275660, 0x1, 0x2, 0x1152680, 0xc420217620)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/publish_update.go:47 +0x3dd
github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc4202e6ea0, 0xc420275660, 0x1, 0x2, 0xc4202e5e01, 0xc4202e5e18)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:305 +0x2a7
github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc4202e70e0, 0xc420275650, 0x2, 0x3, 0xc420000101, 0xd0f3c0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:283 +0x151
github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc4202e78c0, 0xc420275640, 0x3, 0x4, 0xc4202ed500, 0xc420275640)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:283 +0x151
github.com/aptly-dev/aptly/cmd.Run(0xc4202e78c0, 0xc42000e090, 0x3, 0x3, 0xc420270001, 0x0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/run.go:41 +0x12a
main.main()
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/main.go:24 +0x151

## Your Environment
All the aptly commands get this panic when run. "gpg" is installed and is included in the $PATH. 
gpg version used is 2.1.11.

Aptly commands can be run successfully when using sudo.

**Comment by smira** [comment]
Please see #657 and linked issues, short version: gpg2 compatibility is coming.

**Comment by smira** [comment]
Closing as duplicate
