### ISSUE TITLE
mirror update ignores packages listed in remote repsitory

### ISSUE THREAD

**Issue by r4sas** [aptly-dev/aptly#784]
I'm trying create mirror of remote repository, but when I try use update command, aptly doesnt downloading packages.

I checked that in `dists/stretch/main/binary-amd64/Packages` packages are listed, but think that problem in package naming of remote repository. They using filename like `<package>_<version>-1ubuntu1_<arch>.deb` (example of what I see in stretch repo).

Is that aptly bug? Or that done specially? How can I bypass that?
Additional info, such like remote repo address, can be provided by request.

## Your Environment
debian 9.5, aptly 1.3.0.

**Comment by smira** [comment]
@r4sas it's not possible to proceed without details on this issue. If the mirror is private, please provide at least redacted output of mirror create/update.

**Comment by r4sas** [comment]
No problem.
Remote repo: https://deb.i2p2.de/
Packages file: https://deb.i2p2.de/dists/stretch/main/binary-amd64/Packages

Console output:
```bash
~$ aptly mirror create stretch-i2p https://deb.i2p2.de/ stretch
Downloading https://deb.i2p2.de/dists/stretch/InRelease...
gpgv: Signature made Fri 05 Oct 2018 06:59:19 PM UTC using RSA key ID 5BCF1346
gpgv: Good signature from "I2P Debian Package Repository <killyourtv@i2pmail.org>"

Mirror [stretch-i2p]: https://deb.i2p2.de/ stretch successfully added.
You can run 'aptly mirror update stretch-i2p' to download repository contents.
~$ aptly mirror update stretch-i2p
Downloading https://deb.i2p2.de/dists/stretch/InRelease...
gpgv: Signature made Fri 05 Oct 2018 06:59:19 PM UTC using RSA key ID 5BCF1346
gpgv: Good signature from "I2P Debian Package Repository <killyourtv@i2pmail.org>"
Downloading & parsing package files...
Downloading https://deb.i2p2.de/dists/stretch/main/binary-amd64/Packages.bz2...
Downloading https://deb.i2p2.de/dists/stretch/main/binary-armel/Packages.bz2...
Downloading https://deb.i2p2.de/dists/stretch/main/binary-armhf/Packages.bz2...
Downloading https://deb.i2p2.de/dists/stretch/main/binary-i386/Packages.bz2...
Building download queue...
Download queue: 0 items (0 B)

Mirror `stretch-i2p` has been successfully updated.

```

**Comment by smira** [comment]
I see no problems with this mirror, but I think you just have it already downloaded, so package files are in the aptly's package pool, and it skips package files which are already downloaded.

You can do quick check:

```
$ aptly mirror show --with-packages stretch-i2p
Name: stretch-i2p
Archive Root URL: https://deb.i2p2.de/
Distribution: stretch
Components: main
Architectures: amd64, armel, armhf, i386
Download Sources: no
Download .udebs: no
Last update: 2018-10-06 00:44:05 MSK
Number of packages: 10

Information from release file:
Architectures: i386 amd64 armel armhf
Codename: stretch
Components: main
Date: Fri, 05 Oct 2018 18:59:19 UTC
Description:  I2P

Label: I2P
Origin: I2P
Suite: newstable
Packages:
  i2p_0.9.37-1ubuntu1_all
  i2p-doc_0.9.37-1ubuntu1_all
  i2p-keyring_2018.09.16_all
  i2p-router_0.9.37-1ubuntu1_all
  killyourtv-keyring_2015.03.27.1_all
  libjbigi-jni_0.9.37-1ubuntu1_amd64
  libjbigi-jni_0.9.37-1ubuntu1_i386
  libjbigi-jni_0.9.20-2~deb7u+1_armhf
  libjbigi-jni_0.9.19-1~deb7u+1_armel
  syndie_1.107b-2ubuntu1_all
```

**Comment by r4sas** [comment]
So, aptly can skip packages, which exists in other mirrors for example?
I think better to print some information like "package already imported in <mirror/repo name, etc.>".

Anyway, thanks!

**Comment by smira** [comment]
Package might exist in the pool for variety of reasons, including being downloaded for mirror which got dropped or added manually, so successful `aptly mirror update` simply means that all the packages are available.
