### ISSUE TITLE
mistake with apt publish list

### ISSUE THREAD

**Issue by 4LeXFiDin** [aptly-dev/aptly#785]
Hello all,
One of my colleague has tried to publish his last snapshot and has made a mistake with the command. Now when we have :
\# aptly publish list --raw
--help dev
. av
. bak
tools
[...]

\# aptly publish list 
  * --help/dev [all, amd64, i386, source]
  * ./av  [all, amd64, i386, source]
  * ./bak  [all, amd64, i386, source]

I can't drop :
aptly publish drop --help*
aptly publish drop \--help*
aptly publish drop "--help\ dev"

Do you know how could we do please ? :(

**Comment by lazyfrosch** [comment]
You need to drop the distribution from a prefix:

It was created with:

`aptly publish repo reponame --help`

You can drop:

`aptly publish drop dev --help`
