### ISSUE TITLE
how to drop aplty dists:xenial

### ISSUE THREAD

**Issue by sahumanoj3119** [aptly-dev/aptly#789]
By mistakenly i created a distributed name  dists:xenial 

But unable to deleted the published repo can any once help me out. 

filesystem:mongodb-xenial-3.6:./dists:xenial [amd64] publishes {multiverse: [mongodb-xenial/mongodb-org/3.6-local-102218]: Snapshot from local repo [mongodb-xenial/mongodb-org/3.6-local]}

 aptly publish drop dists:xenial
ERROR: unable to remove: published repo with storage:prefix/distribution ./dists:xenial not found

**Comment by danwerspb** [comment]
Try shield ":" with backslah "\" in "dists:xenial"

**Comment by smira** [comment]
@sahumanoj3119 you need something like (`aptly publish drop` accepts distribution followed by prefix):

```
aptly publish drop ./dists:xenial filesystem:mongodb-xenial-3.6
```
