### ISSUE TITLE
Error decoding snapshot: Time.UnmarshalBinary: unsupported version Error decoding mirror: Time.UnmarshalBinary: unsupported version

### ISSUE THREAD

**Issue by danwerspb** [aptly-dev/aptly#790]
Aptly 1.3.0, OS Debian 9.5. Any command with aptly generate error:
```
aptly@qa2:~$ aptly publish snapshot -distribution=stretch stretch-final-181026                                                       
Error decoding snapshot: Time.UnmarshalBinary: unsupported version
Error decoding mirror: Time.UnmarshalBinary: unsupported version
```

**Comment by taladar** [comment]
Not sure if it is related but aptly seems to have missed this change in the go codec binary

https://github.com/ugorji/go/issues/269

**Comment by danwerspb** [comment]
I use Debian Testing

**Comment by smira** [comment]
Please use builds from https://www.aptly.info/download/ until packaging problem is fixed (aptly should be built with vendor/)

**Comment by smira** [comment]
See also #791
