### ISSUE TITLE
Error decoding mirror: msgpack decode error

### ISSUE THREAD

**Issue by pfelecan** [aptly-dev/aptly#791]
Since the last update on a Debian testing, 1.3.0+ds1-1 from 1.3.0-6, nothing works anymore.
For example:
```
aptly mirror list
Error decoding mirror: msgpack decode error [pos 200]: invalid length of bytes for decoding time - expecting 4 or 8 or 12, got 15
Error decoding mirror: msgpack decode error [pos 190]: invalid length of bytes for decoding time - expecting 4 or 8 or 12, got 15
No mirrors found, create one with `aptly mirror create ...`.
```
There are mirrors, two of them.

I tried an `aptly db recover`, to no avail.

**Comment by pfelecan** [comment]
I reverted the installation, i.e. removed the new package and reinstalled the old one.
The aforementioned error does not appear anymore.
Consequently, it's a packaging/build error.
Time to open a bug report on the Debian tracker.

**Comment by smira** [comment]
Yep, aptly was built without provided `vendor/`, and `Gopkg.lock` wasn't used as well. 

You can use builds from https://www.aptly.info/download/

**Comment by pfelecan** [comment]
This is quite annoying.
What the Debian packager/maintainer recommends is to "recreate" the database.
Is that possible? How can we recreate the database?

**Comment by smira** [comment]
There's only one way -  drop the database (`~/.aptly/db`) and aptly will create new one, but this will lead to all the aptly data being *erased*.

**Comment by smira** [comment]
What is even worse - DB would be incompatible with aptly builds from repo.aptly.info.

**Comment by smira** [comment]
The best thing I can do is to provide fixed version of aptly which will enforce older encoding with new version of the codec but Debian package should be update

**Comment by smira** [comment]
Workaround is described in ugorji/go#269

**Comment by taladar** [comment]
Wouldn't it make sense to have migration code from old versions of the DB time encoding to new versions? aptly will have to move to the new version of the dependency eventually, especially since we are talking serialization/deserialization libraries and those (in general) tend to be notorious for security issues.

**Comment by pfelecan** [comment]
FYI, I opened an issue on the Debian tracker 911924

**Comment by smira** [comment]
@taladar I'm talking about moving to new version of the library but configuring it in a way to read and write data in the same format as the vendored version today in aptly

**Comment by smira** [comment]
Looks like new version of ugorji/codec is even more broken then I might have assumed. It skips fields tagged as `json:"-"` for msgpack encoding.

**Comment by neolynx** [comment]
this was fixed with updated ugorji/go/codec
