### ISSUE TITLE
Ubuntu Official Mirror "Release" Missing

### ISSUE THREAD

**Issue by Phil795** [aptly-dev/aptly#795]
I've been trying to get aptly running for hours now to mirror the official Ubuntu repository. I don't want a specific version, but the complete repository because we have many different versions on our servers.

Aptly runs so far. However, I always get the error that the file "Release" could not be found with the following command.

```
root@linux-mirror:~$: aptly mirror create ubuntu_mirror http://archive.ubuntu.com/ubuntu ./
Downloading http://archive.ubuntu.com/ubuntu/InRelease...
Downloading http://archive.ubuntu.com/ubuntu/Release...
ERROR: unable to fetch mirror: HTTP code 404 while fetching http://archive.ubuntu.com/ubuntu/Release
```

This is so far also clear, since I specify the Repo Url and no system specify. According to the instructions also correct. Why does aptly not recursively search for the systems automatically? Or do I have to specify additional parameters to copy the complete repository?

**Comment by xx4h** [comment]
As far as i did understand it correctly, aptly needs a Release file to be able to download the repo. I think you need to add all ubuntu versions manually, each with its own mirror.
