### ISSUE TITLE
unable to publish snapshot with error "function not implemented"

### ISSUE THREAD

**Issue by mLaota** [aptly-dev/aptly#810]
We are trying to publish a snapshot but we are getting the following error

ERROR: unable to publish: unable to process packages: link /media/user1/My Book/.aptly/pool/d0/b1/1d1d27fe425bc91ea51fab74ad45_accountsservice_0.6.45-1ubuntu1_amd64.deb /media/user1/My Book/.aptly/public/pool/main/a/accountsservice/accountsservice_0.6.45-1ubuntu1_amd64.deb: function not implemented

The command that we ran was:

 aptly publish snapshot bionic_amd64_main_2019_02_01_10_58_29

The complete log is the following:

Loading packages...
Generating metadata files and linking package files...
ERROR: unable to publish: unable to process packages: link /media/user1/My Book/.aptly/pool/d0/b1/1d1d27fe425bc91ea51fab74ad45_accountsservice_0.6.45-1ubuntu1_amd64.deb /media/user1/My Book/.aptly/public/pool/main/a/accountsservice/accountsservice_0.6.45-1ubuntu1_amd64.deb: function not implemented

We are using a computer running Ubuntu 18.04 Bionic

**Comment by smira** [comment]
This is an error coming from your filesystem. Looks like hardlinks are not implemented on that filesystem.

You have a list of options: https://www.aptly.info/doc/feature/filesystem/

**Comment by mLaota** [comment]
What does the "copy" linkMethod do?
