### ISSUE TITLE
Support for InRelease as fallback if Release does not exist

### ISSUE THREAD

**Issue by digger18** [aptly-dev/aptly#812]
I am trying to mirror the Nvidia-Docker repository, which suprisingly has no **Release** file, but only **InRelease**.

Debian docs says that if **Release** file does not exist, apt will try to pull **InRelease** instead.
I was wondering why this is not the behavior with aptly and how can I workaround this issue?

```
# aptly mirror create -architectures=amd64 -ignore-signatures -force-architectures -force-components nvidia-docker https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64 /
Downloading https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64//Release...
ERROR: unable to fetch mirror: HTTP code 404 while fetching https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64//Release
```

**Comment by smira** [comment]
That happens because you say `-ignore-signatures`, so aptly tries to download cleartext `Release` file. If you drop that flag, it should start with `InRelease`.
