### ISSUE TITLE
Incorrect answer from api

### ISSUE THREAD

**Issue by danwerspb** [aptly-dev/aptly#829]
Request to api:
`aptly@qa2:~$ curl -sS -X PUT -H "Content-Type: application/json" --data "{\"Snapshots\": [{\"Component\": \"main\", \"Name\": \"veil-prod_v3.0.0-20190412143238\"}]}" http://192.168.11.118:8008/api/publish/veil-prod_v3.0.0/veil`

Answer from api:
`{"error":"unable to update: published repo with storage:prefix/distribution veil-prod/v3.0.0/veil not found"}`

Resume: The link is incorrectly parsed in the end line. `veil-prod_v3.0.0/veil` was changed to `veil-prod/v3.0.0/ veil`

**Comment by jdelic** [comment]
@danwerspb 
probably too late, but if you look at [the documentation](https://www.aptly.info/doc/api/publish/)

> if publishing prefix contains slashes /, they should be replaced with underscores (_) and underscores should be replaced with double underscore (__)

So you need to escape the string correctly, like [for example in my aptly-api Python client library](https://github.com/gopythongo/aptly-api-client/blob/1862aa188b53e6274fc311c0eb44709e00a0def3/aptly_api/parts/publish.py#L42).

**Comment by danwerspb** [comment]
@jdelic 
The problem is actual. Thanks for pointing the decision. I will definitely use your library.
