### ISSUE TITLE
Drop package from mirror

### ISSUE THREAD

**Issue by arhue** [aptly-dev/aptly#836]
Is it possible to drop a package version from a mirror. My mirror contains:

```
  chef_15.0.300-1_amd64
  chef_15.0.298-1_amd64
  chef_15.0.293-1_amd64
  chef_14.12.9-1_amd64
  chef_14.12.3-1_amd64
  chef_14.11.21-1_amd64
  chef_14.10.9-1_amd64
  chef_14.9.13-1_amd64
  chef_14.8.12-1_amd64
  chef_14.7.17-1_amd64
  chef_14.6.47-1_amd64
  chef_14.5.33-1_amd64
  chef_14.5.27-1_amd64
  chef_14.4.56-1_amd64
  chef_14.3.37-1_amd64
  chef_14.2.0-1_amd64
  chef_14.1.12-1_amd64
  chef_14.1.1-1_amd64
  chef_13.12.14-1_amd64
  chef_13.12.3-1_amd64
  chef_13.11.3-1_amd64
  chef_13.10.4-1_amd64
  chef_13.10.0-1_amd64
  chef_13.9.4-1_amd64
  chef_12.22.5-1_amd64
```
But I would like to drop chef_15*. Is something like that possible? Thank you.

**Comment by mjb2kmn** [comment]
I believe this should be done with a [package query](https://www.aptly.info/doc/feature/query/) filter on the mirror. You can define the filter when you [create](https://www.aptly.info/doc/aptly/mirror/create/)  or [edit](https://www.aptly.info/doc/aptly/mirror/edit/) the mirror.

Something along the lines of `aptly mirror create -filter-with-deps=true -filter="% chef_15.*" chef https://example.com/chef chef`, or filter on Name and Version `-filter="Name=chef, Version<15"`

**Comment by arhue** [comment]
@mjb2kmn Thanks for the reply. I tried the edit mirror feature but it didn't work. The create would be too difficult to implement for me as I'm using third party automation code. Just simple package locks on clients work well enough for me so closing this reply. Thank you for the help.
