### ISSUE TITLE
Publish an unmodified mirror

### ISSUE THREAD

**Issue by baby-gnu** [aptly-dev/aptly#844]
##  Detailed Description

When publishing an unfiltered and unmodified mirror, aptly generate the indexes and sign them with its own key which must be deployed on apt clients.

It could be very interesting to be able to mirror a repository without touching any thing like `reprepro update` is able to do.

For filtered mirrors, we could add an option to choose between:

* generate new indexes and sign them
* mirror the indexes without touching files to not break signatures and let clients face the `404 Not Found` on filtered packages.

## Context

We are actually using the [Ubuntu mirror tool](https://launchpad.net/ubumirror) to create our local mirrors and we thing the aptly tool could be a good replacement for it (in addition to manage our own repositories).

## Possible Implementation

When doing the mirror, keep the `dists/` files and push them if the proposed new option is set to `touch nothing` instead of generating the files.

## Your Environment

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

```
Package: aptly
Version: 1.3.0+ds1-2.2~deb10u1
```

**Comment by smira** [comment]
This is not that easy to implement with aptly today, so for pure mirroring other solutions might be better. There's an issue for it (#37), so closing this as duplicate.

PRs are welcome, but the way aptly parses the mirror internally makes it really complicated to publish verbatim upstream release which will be required to retain upstream signatures.
