### ISSUE TITLE
Aptly ignores Origin and Label when publishing through API

### ISSUE THREAD

**Issue by aTanW** [aptly-dev/aptly#848]
When publishing through API, aptly ignores parameters "Origin" and "Label".

## Detailed Description
JSON passed to server:

{"Origin":"SFTDCC","Label":"SFTDCC","Signing":{
"GpgKey":"<...>","Batch":true,"PassphraseFile":"<...>"}}

Server responses:
{"AcquireByHash":false,"Architectures":["all","amd64","i386"],"ButAutomaticUpgrades":"","Distribution":"ubuntu","Label":"","NotAutomatic":"","Origin":"","Prefix":".","SkipContents":false,"SourceKind":"local","Sources":[{"Component":"main","Name":"stable"}],"Storage":""}

**Comment by smira** [comment]
I can't reproduce that, and I added the test for it in #860.

Please feel free to reopen with more specifics.

**Comment by aTanW** [comment]
May be it ys my fault.
I attempted to publish already published repo, i.e. update. In this case, as it must be, server ignores this variables. :-)

So, here is no error.
Thank you for useful software!
