### ISSUE TITLE
bind: address already in use

### ISSUE THREAD

**Issue by syphernl** [aptly-dev/aptly#849]
## Detailed Description

In #807 it was introduced that the sock-file will not get removed, because you cannot set permissions on it (reported in #806). 

While this change makes sense, it seems to be causing issues when you restart aptly (e.g. with systemd)

Starting aptly like this:
```
/usr/bin/aptly api serve -no-lock -listen=unix:///tmp/.aptly-api.sock
```
works fine the first time. If you stop the process and start it again, it complains that it is already in use. If you remove the sock-file, aptly starts fine again.

## Your Environment

aptly 1.4.0 on Ubuntu 18.04.

**Comment by smira** [comment]
yep, looks like that change was wrong. I'm going to revert #807
