### ISSUE TITLE
ERROR: unable to update: unable to compute pool location for filename <any package>, MD5 is missing

### ISSUE THREAD

**Issue by jringoot** [aptly-dev/aptly#873]
Can't update updates/security pool for debian buster because md5's are missing 

## Detailed Description

Trying to update a mirror from security.debian.org but it fails on 1 file each time and it is always a different file
ERROR: unable to update: unable to compute pool location for filename libavutil56_4.1.4-1~deb10u1_amd64.deb, MD5 is missing
ERROR: unable to update: unable to compute pool location for filename libreoffice-script-provider-python_6.1.5-3+deb10u3_all.deb, MD5 is missing

`
root@melian:~# aptly mirror list
List of mirrors:
 * [buster-main-amd64]: http://ftp.be.debian.org/debian/ buster
 * [buster-security-amd64]: http://security.debian.org/ buster/updates
 * [buster-updates-amd64]: http://ftp.be.debian.org/debian/ buster-updates
 * [chrome-stretch-amd64]: http://dl.google.com/linux/chrome/deb/ stable
 * [eid-stretch-amd64]: http://files.eid.belgium.be/debian/ stretch
 * [nextcloud-stretch-amd64]: http://ppa.launchpad.net/nextcloud-devs/client/ubuntu/ zesty
 * [stretch-main-amd64]: http://ftp.be.debian.org/debian/ stretch
 * [stretch-security-amd64]: http://security.debian.org/ stretch/updates
 * [stretch-updates-amd64]: http://ftp.be.debian.org/debian/ stretch-updates

To get more information about mirror, run `aptly mirror show <name>`.
root@melian:~# 
root@melian:~# aptly mirror update buster-security-amd64
Downloading http://security.debian.org/dists/buster/updates/InRelease...
gpgv: Signature made Wed 04 Sep 2019 22:40:09 CEST
gpgv:                using RSA key 379483D8B60160B155B372DDAA8E81B4331F7F50
gpgv: Good signature from "Debian Security Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org>"
gpgv: Signature made Wed 04 Sep 2019 22:40:09 CEST
gpgv:                using RSA key 5237CEEEF212F3D51C74ABE0112695A0E562B32A
gpgv: Good signature from "Debian Security Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>"
Downloading & parsing package files...
Downloading http://security.debian.org/dists/buster/updates/main/binary-amd64/Packages.gz...
Downloading http://security.debian.org/dists/buster/updates/contrib/binary-amd64/Packages.gz...
Downloading http://security.debian.org/dists/buster/updates/non-free/binary-amd64/Packages.gz...
Building download queue...
ERROR: unable to update: unable to compute pool location for filename firefox-esr-l10n-hu_60.8.0esr-1~deb10u1_all.deb, MD5 is missing
root@melian:~# 

`
I tried with "-ignore-checksums=true" but it is the same result

## Context

errorfree run

errorfree run
## Possible Implementation

use SHA256 checksums instead, it appears that the md5sums  (which are a deprecated protocol) are no longer available on the security.debian.org server
compare
http://security-cdn.debian.org/dists/stretch/updates/main/by-hash/
with
http://security-cdn.debian.org/dists/buster/updates/main/by-hash/

## Your Environment

debian 9.9  server

**Comment by smira** [comment]
Actually aptly is not using MD5 anymore, but it has fallback enabled by default to support pre-1.1 deployments. 

If MD5 is missing, this file couldn't have been processed by pre-1.1 aptly, so it's safe to ignore legacy pool location.

If your deployment doesn't have package files from versions before 1.1, it's safe to enable `skipLegacyPool` in the config which should be workaround until I do a proper fix.

**Comment by smira** [comment]
oh, it looks like it should be already handled, which version of aptly are you running?

**Comment by jringoot** [comment]
> oh, it looks like it should be already handled, which version of aptly are you running?
root@melian:/etc/apt#  show aptly | grep -i version

Version: 0.9.7-1+b1

the default version in the old stable (9 stretch)

I see that the in debian 10 the current version is

 (1.3.0+ds1-2.2~deb10u1)

I will first upgrade the server then.

Thanks
