### ISSUE TITLE
Specifiying gpg-key: unusable secret key

### ISSUE THREAD

**Issue by micah** [aptly-dev/aptly#885]
I'm trying to publish a snapshot using a specific gpg key that I control the secret-key material (gpg --list-secret-keys shows I have it), but if I specify that gpg-key in aptly, it fails to prompt and then fails to sign the repository.

```
$ aptly publish snapshot -gpg-key=0x1E34A1828E207901 ' -component=buster,bionic,sid,stretch -distribution=release final-buster-release reprepro-release-bionic reprepro-release-sid reprepro-release-stretch filesystem:client:

Loading packages...
Generating metadata files and linking package files...
Finalizing metadata files...
Signing file 'Release' with gpg, please enter your passphrase when prompted:
gpg: skipped "0x1E34A1828E207901": unusable secret key
gpg: signing failed: unusable secret key
ERROR: unable to publish: unable to detached sign file: exit status 2
```

At the place where it says 'please enter your passphrase when prompted:' it does not stop to let me enter the passphrase, it just continues immediately to the error.

**Comment by micah** [comment]
This appears to be because aptly is still using gpg1 behind the scenes, and the public key I had in the gpg1 keystore was expired. I had to import the new extended expirations into gpg1 to get it to work.

**Comment by smira** [comment]
aptly supports GPG2 since 1.4.0: https://github.com/aptly-dev/aptly/releases/tag/v1.4.0
