### ISSUE TITLE
Move to gpg2

### ISSUE THREAD

**Issue by micah** [aptly-dev/aptly#886]
Aptly is using gpg1 internally and should switch to gpg2. The new version of gpg has been available since 2006, and has become the default gpg used in the majority of operating systems. It seems many people run into issues with aptly because they are using gpg2 behind the scenes and it doesn't work with aptly. 

I cannot find any specific issue tracking this, perhaps there is already work being done on it as a milestone for the next release?

**Comment by smira** [comment]
Please see https://github.com/aptly-dev/aptly/releases/tag/v1.4.0
