### ISSUE TITLE
aptly's own debian repository does not work: does not have a Release file

### ISSUE THREAD

**Issue by revast** [aptly-dev/aptly#889]
The repository 'http://repo.aptly.info sqeeze Release' does not have a Release file.Updating from such a repository can't be done securely, and is therefore disabled by default.See apt-secure(8) manpage for repository creation and user configuration details.

apt --version
apt 1.6.12 (amd64)

ubuntu 18.04

**Comment by smira** [comment]
You have a misprint, it should be squeeze

вт, 22 окт. 2019 г., 17:28 revast <notifications@github.com>:

**Comment by revast** [comment]
thanks!
