### ISSUE TITLE
aptly ignores downloadSpeedLimit

### ISSUE THREAD

**Issue by markgraf** [aptly-dev/aptly#897]
## Detailed Description

I'm using aptly version: 1.4.0 on Debian Stretch

I configured `"downloadSpeedLimit": 200,` in /home/aptly/.aptly.conf

When I run `aptly  mirror update stretch-main`, aptly downloads with all the bandwidth available.
I tried `aptly -download-limit=200 mirror update stretch-main` as well, but that disregards the 200KB/sec Limit just the same.

I need to throttle the initial download in order not to block the network for everyone else.

Can you reproduce the issue?

Am I doing something worng?

**Comment by smira** [comment]
Are you talking about package index download (first thing `update mirror` does) or package files download?

**Comment by markgraf** [comment]
Both.

**Comment by smira** [comment]
limiting works just fine:

```
$ aptly mirror update -download-limit=10 deb
Downloading http://ftp.debian.org/debian/dists/stretch/InRelease...
Downloading http://ftp.debian.org/debian/dists/stretch/Release...
Downloading http://ftp.debian.org/debian/dists/stretch/Release.gpg...
openpgp: Signature made Sun, 08 Sep 2019 20:00:11 MSK using RSA key ID 7638D0442B90D010
openpgp: Good signature from "Debian Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org>"
openpgp: Signature made Sun, 08 Sep 2019 20:00:11 MSK using RSA key ID 04EE7237B7D453EC
openpgp: Good signature from "Debian Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org>"
openpgp: Signature made Sun, 08 Sep 2019 20:28:08 MSK using RSA key ID EF0F382A1A7B6500
openpgp: Good signature from "Debian Stable Release Key (9/stretch) <debian-release@lists.debian.org>"
Downloading & parsing package files...
Downloading http://ftp.debian.org/debian/dists/stretch/main/binary-amd64/Packages.gz...
 216.00 KiB / 9.04 MiB [==>----------------------------------------------------------------------------------------------------------]   2.33% 9.98 KiB/s 15m5s
```

So please supply full reproduction case.

**Comment by markgraf** [comment]
You have just successfully reproduced the issue :-)
You are using `-download-limit=10`, but your download speed is 216 KiB/second...

Or do I misunderstand the output above?
Download-Limit is in KB/second, right?

**Comment by smira** [comment]
`KiB` is 1024 bytes: https://ux.stackexchange.com/questions/13815/files-size-units-kib-vs-kb-vs-kb

**Comment by markgraf** [comment]
KiB then, but still roughly downloading 21x faster than expected.

**Comment by smira** [comment]
I think you need to look once more, it is exactly as expected

**Comment by markgraf** [comment]
I don't get it. With a downloadlimit of 10, I'd expect a download-speed of 10 KiB/second, not 216.
Is this 10 concurrent downloads?

And with my configured DownloadSpeedLimit of 200, I'm getting 4.some MiB/second.

**Comment by smira** [comment]
`2.33% 9.98 KiB/s 15m5s`

**Comment by markgraf** [comment]
m( . Sorry about that.

**Comment by Kepler-Br** [comment]
Hi
I've got the same problem
I'm using 1.5.0 version and this command:
`aptly -ignore-signatures -config ./aptly.conf mirror update -download-limit=10 bookworm-non-free`
I've tried to set `downloadConcurrency` in the config but nothing works. I don't want to bombard server with 50 MiB/s so this is a critical feature to me
