### ISSUE TITLE
Aptly source has changed checksum

### ISSUE THREAD

**Issue by fxcoudert** [aptly-dev/aptly#903]
## Detailed Description

We, at Homebrew, are seeing our security checks fail while trying to build Aptly 1.4.0 from source. We are trying to build from the source at `https://github.com/aptly-dev/aptly/archive/v1.4.0.tar.gz`, whose SHA-256 checksum was `d124541c928ad35681b82e8554c4ca56bea04518c648ad44a995f319db53cdb2` when it was first released, and which was confirmed by our CI as correct on Sat Jul 6 11:31:52 2019.

The checksum for that same file is now `4172d54613139f6c34d5a17396adc9675d7ed002e517db8381731d105351fbe5`

Can you confirm that this is a legitimate replacement of the source file / re-release / retagging? And not a malicious replacement of the source code?

**Comment by smira** [comment]
Let me double-check it, this is GitHub-generated archive, not manually uploaded. I believe release date is Jul, 5th, and tag hasn't been moved since that time.

**Comment by smira** [comment]
And looks like I made last-minute fixes to update CI code on Jul 6th:

* https://github.com/aptly-dev/aptly/commit/8b12dccd76cd589f04216c7d5763f6fa277819be
* https://github.com/aptly-dev/aptly/commit/5aefd0b3933c4bfcb431466528be399eb0c36dc4

This might explain the checksum change, as changes were done at 16:04PM on Jul 6th.

Sorry for the inconvience, but I can confirm that current data for 1.4.0 release differs from first published only in CI scripts related to artifact upload (Debian packages), which are not consumed in Homebrew iirc.
