### ISSUE TITLE
when upgrading from aptly 1.3 to 1.4

### ISSUE THREAD

**Issue by jringoot** [aptly-dev/aptly#906]
I can't access mirrors and snapshots anymore, eg:
root@melian:~/.gnupg# aptly mirror list
Error decoding mirror: Time.UnmarshalBinary: unsupported version
Error decoding mirror: Time.UnmarshalBinary: unsupported version
Error decoding mirror: Time.UnmarshalBinary: unsupported version
Error decoding mirror: Time.UnmarshalBinary: unsupported version
Error decoding mirror: Time.UnmarshalBinary: unsupported version
Error decoding mirror: Time.UnmarshalBinary: unsupported version
Error decoding mirror: Time.UnmarshalBinary: unsupported version
Error decoding mirror: Time.UnmarshalBinary: unsupported version
Error decoding mirror: Time.UnmarshalBinary: unsupported version
Error decoding mirror: Time.UnmarshalBinary: unsupported version
Error decoding mirror: Time.UnmarshalBinary: unsupported version
List of mirrors:
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 *

**Comment by jringoot** [comment]
I am unable to find a deb package for 1.3 to roll back either to see the mirrors

**Comment by neolynx** [comment]
this should be fixed by now, closing issue...
