### ISSUE TITLE
ERROR: unable to initialize GPG signer: looks like there are no keys in gpg, please create one (official manual: http://www.gnupg.org/gph/en/manual.html)

### ISSUE THREAD

**Issue by jringoot** [aptly-dev/aptly#907]
I had an expired key and then generated a new one.
Also remove the expiration date of the original key
And now I keep getting this when I try to publish a snapshot. 
(I also upgraded to aptly version 1.4 from version 1.3, which renders all mirrors and snapshots unreadable by aptly: " Time.UnmarshalBinary: unsupported version" (made other ticket for that))

I do have keys, can import them and export them, how do I make it clear to  aptly which key to use?

Thanks

**Comment by jringoot** [comment]
To be sure I tried a new install on  another machine with the default aptly 1.3 from the repository of debian
the publishing fails with this message, even after creating a new key with "gpg --full-generate-key"

**Comment by jringoot** [comment]
BTW: signing of a simple textfile works:
jringoot@len-xxx:~/.gnupg$ gpg -s text.txt
jringoot@len-xxx:~/.gnupg$ cat text.txt
idit is een test

jringoot@len-xx:~/.gnupg$ ls -trl text.txt*
-rw-r--r-- 1 jringoot mecal  17 Jan 20 10:52 text.txt
-rw-r--r-- 1 jringoot mecal 363 Jan 20 10:53 text.txt.gpg

**Comment by copyninja** [comment]
@jringoot  I also faced this issue. But after exporting keys from gpg2 and then reimporting same keys using gpg1 solves issue.
```
gpg --export-secret-keys --armor > secret.asc
gpg1 --import < secret.asc
```
And now aptly happily uses the keys.

**Comment by neolynx** [comment]
closing as migration to gpg2 is recommended
