### ISSUE TITLE
GPG key for the aptly repo has expired

### ISSUE THREAD

**Issue by dasein** [aptly-dev/aptly#911]
## Detailed Description
We are seeing these errors when trying to install from http://repo.aptly.info/

W: GPG error: http://repo.aptly.info squeeze InRelease: The following signatures were invalid: KEYEXPIRED 1584221562 KEYEXPIRED 1584221562 KEYEXPIRED 1584221562

Looks like the key just expired.

----------------------------------
pub   rsa4096 2018-03-15 [SC] [expired: 2020-03-14]
      26DA9D8630302E0B86A7A2CBED75B5A4483DA07C
uid           [ expired] Andrey Smirnov <me@smira.ru>

## Context
apt-get install on debian distros are failing. There may be other packaging systems that are also affected.

## Possible Implementation
N/A

## Your Environment
N/A

**Comment by loeken** [comment]
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://repo.aptly.info squeeze InRelease: The following signatures were invalid: EXPKEYSIG ED75B5A4483DA07C Andrey Smirnov <me@smira.ru>
W: Failed to fetch http://repo.aptly.info/dists/squeeze/InRelease  The following signatures were invalid: EXPKEYSIG ED75B5A4483DA07C Andrey Smirnov <me@smira.ru>
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by realtime-neil** [comment]
Seconded:
```
W: GPG error: http://repo.aptly.info squeeze InRelease: The following signatures were invalid: EXPKEYSIG ED75B5A4483DA07C Andrey Smirnov <me@smira.ru>
E: The repository 'http://repo.aptly.info squeeze InRelease' is not signed.
```

**Comment by berendt** [comment]
Tested on Ubuntu 18.04. Does not work there as well.

**Comment by protenhan** [comment]
This seems to be the same issue as #717

**Comment by berendt** [comment]
@smira Can you please re-sign the packages?

**Comment by realtime-neil** [comment]
> @smira Can you please re-sign the packages?

@smira , preferably with an unexpired key :grin:

**Comment by smira** [comment]
Sorry for being late, I updated expiration date for the key and pushed updated key to the keyservers. It takes some time for the key to propagate. I'll update the website with the new key in a few

**Comment by loeken** [comment]
http://pool.sks-keyservers.net/pks/lookup?op=get&search=0xED75B5A4483DA07C seems to be fixed

**Comment by smira** [comment]
See also: https://github.com/aptly-dev/www.aptly.info/pull/81

**Comment by smira** [comment]
https://www.aptly.info/pubkey.txt should be updated now as well
