### ISSUE TITLE
Aptly repo key expired

### ISSUE THREAD

**Issue by rlueckl** [aptly-dev/aptly#912]
## Detailed Description
The Debian repo key (ED75B5A4483DA07C) of the Aptly repository (http://repo.aptly.info/) has expired on Saturday March 14th. Please update the key!

**Comment by smira** [comment]
Please update the key, one of the easiest ways is to do:

```
wget -qO - https://www.aptly.info/pubkey.txt | sudo apt-key add -
```

**Comment by smira** [comment]
More info: https://www.aptly.info/download/

**Comment by rlueckl** [comment]
Thanks for updating the key so quickly!
