### ISSUE TITLE
Website tutorial missing a lot of code-examples.

### ISSUE THREAD

**Issue by rpier1** [aptly-dev/aptly#914]
The tutorials (on the website)
e.g. https://www.aptly.info/tutorial/mirror/
previously had much more code-examples and images.

What happened?
Thanks.

**Comment by evanjoy** [comment]
:+1: the tutorial is still missing all code blocks and is completely useless without them.

**Comment by evanjoy** [comment]
The pull example is similarly broken and therefore not very helpful.  It has no code blocks at all.

https://www.aptly.info/tutorial/pull/

**Comment by rpier1** [comment]
Till it's fixed, you can use this archived version:

https://web.archive.org/web/20170325133850/https://www.aptly.info/tutorial/

**Comment by j1mc** [comment]
You can also view the github-rendered markdown in the files here: https://github.com/aptly-dev/www.aptly.info/tree/master/content/tutorial

**Comment by neolynx** [comment]
documentation is being updated...
