### ISSUE TITLE
Key for official aptly APT repository (repo.aptly.info) expired

### ISSUE THREAD

**Issue by taladar** [aptly-dev/aptly#916]
The key for the repo.aptly.info APT repository expired

```
  The following signatures were invalid: EXPKEYSIG ED75B5A4483DA07C Andrey Smirnov <me@smira.ru>
Reading package lists...
W: GPG error: http://repo.aptly.info squeeze InRelease: The following signatures were invalid: EXPKEYSIG ED75B5A4483DA07C Andrey Smirnov <me@smira.ru>
E: The repository 'http://repo.aptly.info squeeze InRelease' is not signed.
```

**Comment by taladar** [comment]
You probably need to update the key id on https://www.aptly.info/download/ too once you signed the repository with a new key.

**Comment by smira** [comment]
Key expriation date was extended, please download the key as stated on  https://www.aptly.info/download/  to get it updated on your host.
