### ISSUE TITLE
Is Aptly still maintained?

### ISSUE THREAD

**Issue by NielsH** [aptly-dev/aptly#920]
Hi,

We're considering switching to Aptly, however we are having some doubts because it seems somewhat abandoned; the last commits stop around october 2019 and when I look at the website regarding the Roadmap I see planned releases for Dec 2019 and Jun 2020 which appear to be out-of-date ( https://www.aptly.info/download/ ) since it has already been Dec 2019 of course.

Is it still maintained or no more?

Cheers

**Comment by sjquinney** [comment]
I've recently been wondering the same thing. The website is in a poor state with the tutorials having lost all the examples which makes it very hard to get started. Also questions on the mailing list go unanswered. Would be a shame as aptly looks really good compared to other tools which I've found lacking in features.

**Comment by adam-kosseck** [comment]
Take a look at the developer's Github activity, he is still very active just not on this project.
It seems he is working at a Kubernetes startup and doesn't have time for this project anymore. 

What are the best alternatives to Aptly?  Well I've tried both the aptmirror and debmirror CLI tools, at the time debmirror seemed more mature but didn't have the delta or lifecycle support that Aptly has.  In the UI space I've tried both Foreman (katello) and its commercial (.deb focussed) offshoot Orcharhino, both seemed promising and had all of the required features but had trouble working reliably in our admittedly highly complex environments.

My next point of investigation was going to be Pulp3, as this is the CLI tool that Foreman/Katello & Orcharhino use under the hood...

**Comment by berendt** [comment]
@adam-kosseck We have also used Aptly so far and will now look at Pulp3 as we also need mirrors for Docker/Podman images and Ansible roles. I think Pulp3 is a good solution then. Aptly is definitely no longer an option for us.

**Comment by cgallay** [comment]
Hi, @adam-kosseck which alternative did you end up using?

**Comment by adam-kosseck** [comment]
I'm still using Aptly due to the amount of time I've already invested in wrapper scripts to automate processes across multiple environments.
However I remain keen to investigate Pulp 3 when time permits.

**Comment by seitzbg** [comment]
Any comments from either of the maintainers regarding Aptly?  Would love to start using it but not if it is a dead project.  Pulp3 looks interesting but no CLI right now (which isn't a deal breaker but that's why I want to use aptly).

**Comment by berendt** [comment]
@seitzbg Have a look at https://github.com/pulp/pulp_ansible. This makes it easy to manage.

**Comment by oberones** [comment]
For anyone considering using Pulp3, it's a great solution but it will not fill all of Aptly's use-cases. If you just need a way to create versioned repositories, either hosted or proxied, then Pulp3 is a great alternative. It has a really robust API and it does have a CLI or two out there floating around out there, along with client libraries for several languages. However, if you're looking to synchronize a hosted repo with an S3 bucket in order to serve your content from an S3 endpoint, then Pulp3 is not going to work for you. 

Also consider that the documentation for Pulp3 is still evolving and sometimes does not match the reality of whichever version of pulp-core you happen to be using. It's getting much, much better though. Definitely worth testing out and seeing if it will work for you.

**Comment by realtime-neil** [comment]
> What are the best alternatives to Aptly? Well I've tried both the aptmirror and debmirror CLI tools, at the time debmirror seemed more mature but didn't have the delta or lifecycle support that Aptly has.

It's also worth noting that `debmirror` doesn't support https endpoints.

**Comment by pmhahn** [comment]
I just asked @smira by private mail about a missing feature; his answer contained this:
> Hey Philipp, I'm no longer maintaining aptly, so I don't think I will be able to answer your question.

So at least from that point `aptly` looks dead.

**Comment by realtime-neil** [comment]
@pmhahn what kind of interest do you have (if any) in "adopting" this project? My expertise tends toward Debian packaging and not golang, otherwise I'd volunteer my services.

**Comment by berendt** [comment]
But then a public notice from @smira (a comment here in the issue) would be good and a corresponding note in the documentation, on the website and in the README.

**Comment by berendt** [comment]
@realtime-neil We check from our side whether a further development of Aptly is in our interest. And whether we have the necessary knowledge and resources. Actually we like it quite a lot. But for the moment, I think that marking it as unmaintained would be correct.

**Comment by pmhahn** [comment]
> @pmhahn what kind of interest do you have (if any) in "adopting" this project? My expertise tends toward Debian packaging and not golang, otherwise I'd volunteer my services.

I'm a Debian Developer (DD) myself, but completely new to golang. I just started learning it, but I consider myself to be far away from using it in production. For my work as Open Source Software Engineer I'm mostly a Python guy, but I'm also using C and perl for over 30 years.
My motivation for using `aptly` is currently motivated by my day job, where I need a Debian package repository until [GitLab has its own Package Manager ready](https://gitlab.com/gitlab-org/gitlab/-/issues/5835). Previously I've bad been using [RepRepRe](https://wiki.debian.org/DebianRepository/SetupWithReprepro) for other projects, but needed something more modern than that.
We're currently evaluating `aptly` as an alternative to [apt-mirror](https://github.com/apt-mirror/apt-mirror), which we're still using, but it shows its age. I haven't yet looked at [pulp](https://pulpproject.org/) which I only recently learned about.

So currently I lack the required golang knowledge, but consider me in if someone want to team-maintain `aptly` and is looking for more hands.

**Comment by karras** [comment]
Maybe we can throw some (virtual) money at @sliverc to accept some of the PRs. ;)

**Comment by cr1xu5** [comment]
For mirroring/caching there is also https://github.com/cybozu-go/aptutil

**Comment by adam-kosseck** [comment]
@cr1xu5 aptutil shows no maintainer activity for 6 months.

**Comment by Smarre** [comment]
@pmhahn maybe just send private message to one (or all) members of the aptly-dev group to ask for admin privileges? I think the most important thing here is time to review and merge pull requests, as things are building up.

**Comment by peylight** [comment]
@Smarre Or maybe we need to just fork it.

**Comment by Smarre** [comment]
@peylight I can’t promise enough time that I should take it, even though I’d want to. I can help someone else though.

**Comment by rm5248** [comment]
While I don't have any golang experience(and I don't have a particular desire to learn at the moment), I would be willing to support in other ways - hosting, testing, monetary support, etc.  Aptly is useful enough to me that I would gladly donate some money to anyone who did step up to maintain it.

**Comment by pabs3** [comment]
I've sent a mail to the three @aptly-dev members asking them to add more people to the organisation.

**Comment by pabs3** [comment]
Looping in @sdelafond, the maintainer of the Debian package of aptly.

**Comment by smira** [comment]
First of all, fixing my mistake, now @sliverc and @apachelogger are both owners of this organization, so they can manage members. 

If there are volunteers to take over the project, I would be happy to help with that. Besides the GitHub itself, there's some infrastructure in AWS I'm paying out of my pocket mostly, but I can hand it over to the interested people.

**Comment by sliverc** [comment]
Let me speak up for the co-maintainers as well. A while back @apachelogger and I joined to help @smira maintaining Aptly. Both of our focus changed quite a bit though and therefore we do not have time anymore to help maintain Aptly. I would love to see Aptly continue though. When reading through this thread there seems to be an interest for continuation but so far I do not see a concrete suggestion of someone/a group to take up this responsibility. 

So if someone is willing to continue maintaining the project, please speak up and we can add you as a maintainer. I am happy to answer questions of a new maintainer if this helps in any way.

**Comment by smira** [comment]
I will second everything @sliverc said above.

Happy to host couple of video calls to hand over stuff and help to unblock things.

**Comment by aol-nnov** [comment]
It's sad, so sad
It's a sad, sad situation
And it's getting more and more absurd
It's sad, so sad
Why can't we talk it over?
Oh, it seems to me
Sorry seems to be the hardest word

Everybody needs aptly, but no one is willing to maintain it.. The curse of aptly, eh, @smira ? ))

Same sh*t here, bummer... :( Many of our processes depend on aptly, but we have no resources to maintain it, too...

**Comment by karras** [comment]
I'll have some discussions with the people at @adfinis-sygroup and also @erickellerek1 to see what we can do.

**Comment by pabs3** [comment]
A [number of Debian-based distros use aptly](https://wiki.debian.org/Derivatives/CensusFull?action=fullsearch&context=180&value=title%3ADerivatives%2FCensus%2F+regex%3Aaptly&fullsearch=Text) so I have [invited](https://lists.debian.org/msgid-search/c65e59a4b9a112479c97904aa21d8967d591cb60.camel@debian.org) them to consider helping maintain aptly.

**Comment by neolynx** [comment]
Hi all,

We are a group of 4 developers and would like to volunteer for the maintenance of aptly !

We use several aptly instances daily at work and we have experience in debugging and fixing issues. We also maintain the Molior Debian Build System [0] which is based on aptly and a set of aptly patches [1] (mainly adding a mirror API which can run asynchronously and some smaller fixes). These patches were done in collaboration with the @adfinis-sygroup mentioned above. 

Reading from this thread and the open issues, I think the main focus would be:
- Update go version / modules / build method
- Fix bugs, improve error handling and messages
- Respond to and process issues
- Update aptly.info
- Do regular releases

But this just from the top of my head. Any advice on priorities and expected direction and estimated effort is welcome. 

We cannot promise to do 10 releases a year, but I think we can do more than the last 2 years ;-)

Kind Regards, 

 André Roth 

[0] https://github.com/molior-dbs/molior/tree/1.4#screenshots
[1] https://github.com/molior-dbs/aptly/commits/molior

**Comment by apachelogger** [comment]
Neat! Can we get a list of people to add to the team? ;)

**Comment by neolynx** [comment]
Could you add: @neolynx @szakalboss @dario-gallucci @lbolla

thanks !

**Comment by smira** [comment]
@neolynx nice, thank you!

I sent out the invitations. @neolynx you're the owner of the org now, so you can manage org settings.

Please let me know if you have any questions, I'm happy to help with infrastructure or any other questions.

**Comment by karras** [comment]
@smira @neolynx I'd like to offer my help as well and mainly focus on the infrastructure, planning, etc. part or sourcing in some colleagues from @adfinis-sygroup.

**Comment by clemsciences** [comment]
We use aptly in my company, I don't know enough of Go to help a lot, but I can try. It would be a shame to let this tool die.

**Comment by obol89** [comment]
Hey,
@smira , @neolynx I'm happy to help with this tool as well.
Thanks!

**Comment by szakalboss** [comment]
> Hey,
> @smira , @neolynx I'm happy to help with this tool as well.
> Thanks!

Hey Artur,

it is appreciated you are willing to help,

how would you like to contribute? do you already have pull request?

Kind regards / Pozdrawiam
Karol

**Comment by obol89** [comment]
> 
> Hey Artur,
> 
> it is appreciated you are willing to help,
> 
> how would you like to contribute? do you already have pull request?
> 
> Kind regards / Pozdrawiam
> Karol

@szakalboss, thank you for the reply,

Nope, I don't have any pull request yet. I thought more about reviewing current pull requests if any and improve documentation on the website and of course, I'm keen to create new pull requests and code improvements that can solve some reported issues.

Thanks,
Artur

**Comment by kfiresmith** [comment]
One area that might pay dividends would be to start hacking the cruft out of https://www.aptly.info/.  This would make Aptly look a lot less like a dead project and I suspect more potential contributors who may have missed this thread might show up for the party.
IMO /blog/ should be done away with entirely to start.  

If there is any possible way to remove the ads that would help with credibility as well.

Removing dated references in roadmaps to points in time in the past would be good.

**Comment by clemsciences** [comment]
For example, the link to the Twitter account https://twitter.com/AptlyDev is dead.

**Comment by neolynx** [comment]
> For example, the link to the Twitter account https://twitter.com/AptlyDev is dead.

@smira would you be able to share the twitter account ?

**Comment by neolynx** [comment]
> One area that might pay dividends would be to start hacking the cruft out of https://www.aptly.info/. This would make Aptly look a lot less like a dead project and I suspect more potential contributors who may have missed this thread might show up for the party.
> IMO /blog/ should be done away with entirely to start.
> 
> If there is any possible way to remove the ads that would help with credibility as well.
> 
> Removing dated references in roadmaps to points in time in the past would be good.

sounds good ! what would you need for that ?

**Comment by apachelogger** [comment]
> > For example, the link to the Twitter account https://twitter.com/AptlyDev is dead.
> 
> @smira would you be able to share the twitter account ?

The account is run as a team. If you tell me the `@handles ` of who to add I think I can get you sorted.

**Comment by freakinhippie** [comment]
There is a lot of good discussion in this thread but it doesn't appear to have resulted in updates to the project. Is there any way I can help? I've got some experience with golang, though I am not a guru.

I'd like to create a PR for the `-json` flags on the CLI but I don't want to go to the trouble if it has no chance of getting merged.

**Comment by lbolla** [comment]
@freakinhippie There is a big PR in the making (https://github.com/aptly-dev/aptly/pull/971) which is taking some effort.

Please do submit your PR and I'll be more than happy to review and merge.

**Comment by lbolla** [comment]
#971 merged. We are closer to doing an official release. We are still trying to sort out credentials for deployments from the original maintainer.

**Comment by foss4ever** [comment]
@lbolla 

Any news on when we might see a new major version release?

**Comment by lbolla** [comment]
> @lbolla
> 
> Any news on when we might see a new major version release?
> 
> I'm not a developer so can't contribute in terms of coding, but if there's any need for help writing documentation or similar, I could probably help out...

@neolynx @randombenj Maybe you have an idea about the above?

**Comment by randombenj** [comment]
@lbolla @foss4ever In order for us to do a release, a few things had to be done:

- Migrate to github actions (https://github.com/aptly-dev/aptly/pull/1010)
- Fix failing integration tests (https://github.com/aptly-dev/aptly/pull/1024)
- Migrate aptly.info to github pages and change it's domain ownership (https://github.com/aptly-dev/www.aptly.info/pull/91)
- Migrate repo.aplty.info to our own hosting (and host our own aptly)

Now the main thing that is open, is to fix some deprecations (https://github.com/golang/go/issues/44226) and see how we can publish in the newly hosted repo.aptly.info.

**Comment by felicianotech** [comment]
Hey folks, I would like to step in and maintain this project. All of it, including running/paying for the domain, hosting the apt repo for Aptly itself, etc.

Over the past years this awesome project has had its struggles. The website went down, the apt repo went down, and the releases have been infrequent and far inbetween. I saw that there's been at least two movements to bring this project back to an active state but it seems to keep stalling. I've used Aptly for a few years now and it's a shame to see it not shine to its brightest potential.

For my own needs, I want to really modernize my own infrastructure and tooling and with that came creating an Aptly Docker image, run it in Kubernetes, create a Go-based client to communicate with the Aptly API remotely . While I begin to do that work, it would be a good time to lead this project as well.

I know there can also be security concerns when handing over the keys to a project so I'm more than willing to chat with someone on a call, Zoom, etc. You can also look me up on my [personal website](https://www.feliciano.tech/) and [LinkedIn](https://www.linkedin.com/in/ricardofeliciano/).

If the team here ignores this or passes on the offer, I might end of forking the repos but that would disconnect it from all the open issues and PRs that this project has. Working directly with those issues/PRs makes project management much easier to catch up on the backlog.

cc @randombenj @lbolla @hsitter

**Comment by felicianotech** [comment]
Hey folks. Just following up here.

Other than lbolla above, I've yet to hear from anyone. I know first-hand that when you're involved in a lot of GitHub projects sometimes GitHub emails/notifications can get lost in the noise. On that thought, I have reached out to @randombenj via email.

One way or another, I am hoping on getting things moving forward by December the latest.

**Comment by felicianotech** [comment]
Another day, another update. :)

I was contacted via email on November 8th (11 days ago) but then the communication went dead again.

I REALLY don't want to have to fork the repo with over 200 issues here and many open PRs. I don't want to have to waste anyone's work opening them but I'm running out of options here.

**Comment by neolynx** [comment]
Hi Ricardo,

Sorry for the late answer, things have been busy.

Thanks a lot for opening issues and supporting aptly ! We appreciate
every help, and we are ramping up more support for 2024.

Let's get in touch and figure out how we can move things forward...

Kind Regards,

 André

> Another day, another update. :)
> 
> I was contacted via email on November 8th (11 days ago) but then the
> communication went dead again.
> 
> I REALLY don't want to have to fork the repo with over 200 issues
> here and many open PRs. I don't want to have to waste anyone's work
> opening them but I'm running out of options here.
>

**Comment by owaiskhanafridi** [comment]
Hi there! Our team is planning to use aptly for managing debian package releases. Went through this whole thread. Is it a good idea to start working on Aptly or we should explore other debian release management tools mentioned in this thread ? 

I see a lot of communication regarding support/not supporting aptly.. Just need the final take on the product.
Thanks.

**Comment by neolynx** [comment]
Hi all,

Yes, aptly is maintained !

Most of the work was behind the scenes, updating infrastructure, updating golang version and fixing tests. Many of the tests were relying on Internet downloads, which caused them to break every couple of months. To mitigate this, such resources have been copied to S3, making the testing robust and stable now.  This allows to continue cleaning up the code base and open issues in a controlled way now.

We are going through all merge requests, rebaseing/fixing/testing them, making sure we do not break existing functionality or behavior. Thanks to everyone submitting bug fixes or features, aptly relies on your use cases to be working and every input is valuable. 

We need help with testing merge requests, updating the website and of course new merge requests fixing bugs or adding functionality. If you would like to contribute, please reach out !

Kind Regards,
 Andre
