### ISSUE TITLE
How to store aptly output in a distributed version control system?

### ISSUE THREAD

**Issue by yamatt** [aptly-dev/aptly#93]
We use a distributed version control system to manage our projects and I was wondering how best to store aptly generated repositories. I can see that aptly in some ways is a version control system itself and generates a lot of binary files. However I need a way of allowing other distributed members of our team to change the repos, rollback, add, change, etc. before publish.

What would be the best way of doing that?

**Comment by yamatt** [comment]
I haven't a clue what I was balthering on about any more.

**Comment by lbolla** [comment]
@yamatt I guess I'll close it then ;-) Thanks for chiming in.
