### ISSUE TITLE
"--passphrase-file" and/or "--passphrase" options for aptly publish snapshot/switch/etc

### ISSUE THREAD

**Issue by ghost** [aptly-dev/aptly#94]
Hi,

It would be interesting to provide a --passphrase-file and --passphrase options for the command aptly publish/switch snapshot, in order to be able to automatically publish new GPG-signed snapshots.

In fact in continuous integration use, we automatically upload new packages in our Debian repository in order to provide new packages for each new app release. So in the aptly workflow if I understand correctly I need a repository -> snapshot -> publish. In order to fully automatize this process,  a --passphrase-file and passphrase options for aptly publish snapshot/switch would be great.

e.g:

```
# aptly publish switch --passphrase "V3rYS3cR3t" debian-snapshots-14082014-150313
```

or even better

```
# aptly publish switch --passphrase-file /etc/aptly/passphrase debian-snapshots-14082014-150313
```

Regards,
Carl Chenet

**Comment by melt7777** [comment]
Thank you very much, this is very useful for Jenkins users!
