### ISSUE TITLE
adding error

### ISSUE THREAD

**Issue by moshengrenzenme** [aptly-dev/aptly#944]
adding error

## Detailed Description
Unable to read file keeweb-desktop_1.16.7-1_amd64.deb: unable to read .deb archive keeweb-desktop_1.16.7-1_amd64.deb: strconv.ParseInt: parsing "1609432645.4": invalid syntax

## Your Environment
ubuntu server 2004
aptly version

**Comment by neolynx** [comment]
thanks for reporting! 
could you please specify the versions of aptly (i.e. dpkg -l aptly) and what you tried to mirror ?

**Comment by moshengrenzenme** [comment]
> thanks for reporting!
> could you please specify the versions of aptly (i.e. dpkg -l aptly) and what you tried to mirror ?



Sorry,aptly version is 1.3.0+ds1-4.In fact, I have added 400 + software to the mirror, and only one of them reported an error
