### ISSUE TITLE
Keyserver referenced in readme is deprecated 

### ISSUE THREAD

**Issue by Kapersyx** [aptly-dev/aptly#966]
## Detailed Description

pool.sks-keyservers.net no longer has a DNS record, and the service is deprecated according to their homepage https://sks-keyservers.net/

## Context
The Download instructions on your readme page no longer work.

**Comment by jeverett1522** [comment]
Try using `keyserver.ubuntu.com`

**Comment by neolynx** [comment]
readme was updated
