### ISSUE TITLE
Cannot set "no" values for '-with-' arguments 

### ISSUE THREAD

**Issue by akarasulu** [aptly-dev/aptly#969]
The `-with-*` arguments for the `aptly mirror edit` command when used with value `="no"` or `="yes"` return `ERROR: unable to parse flags`:

* -with-installer
* -with-udebs
* -with-sources

## Context

There's no other way to unset these properties for a mirror unless you drop the mirror and recreate it. It is also very misleading to users when they show the property with the `aptly mirror show` command and see that it is a boolean `yes|no` field. It's natural to expect to be able to set these boolean arguments with yes or no on the CLI.

## Your Environment

Fresh Debian 10.10 on a KVM virtual machine.
Aptly version: 1.4.0

**Comment by freakinhippie** [comment]
Try using `true`|`false` instead of `yes`|`no`. eg: `aptly mirror edit -with-installer=false -with-udebs=false <mirror>`
