### ISSUE TITLE
apt-key returns 'No name'

### ISSUE THREAD

**Issue by jkorinth** [aptly-dev/aptly#990]
The key for the aptly repo can no longer be obtained:
```
apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED75B5A4483DA07C
Executing: /tmp/apt-key-gpghome.o3YoaNAhy8/gpg.1.sh --keyserver pool.sks-keyservers.net --recv-keys ED75B5A4483DA07C
gpg: keyserver receive failed: No name
```
This breaks Armbian docker-based build scripts.

**Comment by jdbarnes-isi** [comment]
http://repo.aptly.info/ shows pre-commit server message, so this continues to be an issue until that commit is released or someone manually updates the page. @lbolla @Vitexus

**Comment by lbolla** [comment]
Fixed in https://github.com/aptly-dev/www.aptly.info/commit/da6731cd04134cef0241b59e152d5b7a0d62b00b
